// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/streaming/metrics/types was imported by recovered sources but absent from sourcemap recovery.
export const ChatOutcomeRecorderOptions: any = undefined as any;
export const RecordOutcomeParams: any = undefined as any;
export const RequestMetadata: any = undefined as any;
