// @generated by drool.exe extraction
// Generated from packages/drool-core/src/llms/client/enums; source module was missing in Bun sourcemap recovery.
export enum RetryStrategy {
  Interactive = "interactive", // high-inferred; compactCamel; bundle hits=17
  NonInteractive = "nonInteractive", // high-inferred; compactCamel; bundle hits=5
}

export enum StreamingContentBlockType {
  RedactedThinking = "redacted_thinking", // high-inferred; lower_snake; bundle hits=36
  Text = "text", // medium-cluster; compactCamel; bundle hits=92
  Thinking = "thinking", // high-inferred; compactCamel; bundle hits=70
  ToolUse = "toolUse", // high-inferred; compactCamel; bundle hits=15
}

export enum ThinkingDowngradeReason {
  CrossProvider = "cross_provider", // high-inferred; lower_snake; bundle hits=1
  EmptySignature = "empty_signature", // high-inferred; lower_snake; bundle hits=1
  InvalidSignature = "invalid_signature", // high-inferred; lower_snake; bundle hits=3
  OpenAIHeuristic, // value unresolved
}

export enum ToolSearchPhase {
  Disabled = "disabled", // high-inferred; compactCamel; bundle hits=64
  PostToolSearch = "post_tool_search", // high-inferred; lower_snake; bundle hits=2
  PreToolSearch = "pre_tool_search", // high-inferred; lower_snake; bundle hits=1
}

