// @generated by drool.exe extraction
// Generated from src/utils/terminalSegments/enums; source module was missing in Bun sourcemap recovery.
export enum TerminalTruncationPosition {
  End = "end", // medium-cluster; compactCamel; bundle hits=65
  Middle = "middle", // medium-cluster; compactCamel; bundle hits=31
  Start = "start", // medium-cluster; compactCamel; bundle hits=61
}

