// @generated by drool.exe extraction
// Stub generated because src/utils/terminalSegments/types was imported by recovered sources but absent from sourcemap recovery.
export type TerminalSegment = any;
export type TerminalStyle = any;
export type TwoSidedTerminalRowInput = any;
