// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/llms/openai-reexport was imported by recovered sources but absent from sourcemap recovery.
export const OpenAI: any = undefined as any;
