// @generated by drool.exe extraction
// Stub generated because src/services/automations/types was imported by recovered sources but absent from sourcemap recovery.
export type AutomationScheduleChip = any;
export type LocalAutomationRunRecord = any;
