// @generated by drool.exe extraction
// Generated from packages/daemon-core/src/server/handlers/enums; source module was missing in Bun sourcemap recovery.
export enum PendingDaemonRequestDispatchResult {
  Failed = "failed", // medium-cluster; compactCamel; bundle hits=73
  Missing = "missing", // medium-cluster; compactCamel; bundle hits=28
  Sent = "sent", // medium-cluster; compactCamel; bundle hits=25
}

