// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server/handlers/types was imported by recovered sources but absent from sourcemap recovery.
export type BaseResponse = any;
export type DroolRequestHandlerDeps = any;
export type PersistedSessionIndex = any;
export type RelayControl = any;
export type SessionIndexEntry = any;
