// @generated by drool.exe extraction
// Generated from src/components/tools/registry/enums; source module was missing in Bun sourcemap recovery.
export enum ToolHeaderRenderMode {
  Confirmation = "confirmation", // high-inferred; compactCamel; bundle hits=10
  Detailed = "detailed", // high-inferred; compactCamel; bundle hits=7
  Standard = "standard", // high-inferred; compactCamel; bundle hits=43
}

