// @generated by drool.exe extraction
// Stub generated because src/components/tools/registry/types was imported by recovered sources but absent from sourcemap recovery.
export const ToolComponent: any = undefined as any;
export const ToolComponentProps: any = undefined as any;
export const ToolDisplayOverride: any = undefined as any;
export const ToolHeaderBadge: any = undefined as any;
