// @generated by drool.exe extraction
// Stub generated because src/services/review/types was imported by recovered sources but absent from sourcemap recovery.
export const BranchFetchResult: any = undefined as any;
export const ReviewMessageComponents: any = undefined as any;
