// @generated by drool.exe extraction
// Stub generated because src/components/SetupIncidentResponseFlow/types was imported by recovered sources but absent from sourcemap recovery.
export type WizardSelections = any;
