// @generated by drool.exe extraction
// Generated from src/services/diagnostics/enums; source module was missing in Bun sourcemap recovery.
export enum DiagnosticFailureType {
  McpParse, // value unresolved
  OrgOverride, // value unresolved
  RuntimeSettings, // value unresolved
  SettingsParse, // value unresolved
}

