// @generated by drool.exe extraction
// Stub generated because src/services/diagnostics/types was imported by recovered sources but absent from sourcemap recovery.
export type DiagnosticFailure = any;
export type DiagnosticsState = any;
