// @generated by drool.exe extraction
// Stub generated because packages/utils/src/function/types was imported by recovered sources but absent from sourcemap recovery.
export const RetryOptions: any = undefined as any;
