// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/session/messages/createSessionStoreSubscribe was imported by recovered sources but absent from sourcemap recovery.
export const createSessionStoreSubscribe: any = undefined as any;
