// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/messages/enums was imported by recovered sources but absent from sourcemap recovery.
export const AssemblyMessageRole: any = undefined as any;
export const MessageContentType: any = undefined as any;
