// @generated by drool.exe extraction
// Generated from packages/runtime/computer/src/enums; source module was missing in Bun sourcemap recovery.
export enum ComputerRegistrationClearedReason {
  BackendMissing = "backend-missing", // high-inferred; lower-kebab; bundle hits=1
  HostConflict = "host-conflict", // high-inferred; lower-kebab; bundle hits=2
}

export enum ComputerRegistrationReconcileStatus {
  Cleared = "cleared", // medium-cluster; compactCamel; bundle hits=9
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Missing = "missing", // medium-cluster; compactCamel; bundle hits=28
  Registered = "registered", // high-inferred; compactCamel; bundle hits=14
  Stale = "stale", // medium-cluster; compactCamel; bundle hits=6
}

