// @generated by drool.exe extraction
// Stub generated because packages/runtime/computer/src/types was imported by recovered sources but absent from sourcemap recovery.
export type ComputerRegistrationBackend = any;
export type ReconcileComputerRegistrationParams = any;
export type ReconcileComputerRegistrationResult = any;
export type RegisteredHostIdentity = any;
