// @generated by drool.exe extraction
// Generated from packages/common/src/integrations/enums; source module was missing in Bun sourcemap recovery.
export enum IntegrationType {
  CONFLUENCE = "confluence", // high-inferred; compactCamel; bundle hits=3
  FIGMA = "figma", // medium-cluster; compactCamel; bundle hits=5
  GITHUB = "github", // medium-cluster; compactCamel; bundle hits=40
  GITHUB_ES = "github-es", // high-inferred; lower-kebab; bundle hits=2
  GITHUB_PERSONAL = "github-personal", // high-inferred; lower-kebab; bundle hits=3
  GITLAB = "gitlab", // medium-cluster; compactCamel; bundle hits=6
  GITLAB_PERSONAL = "gitlab-personal", // high-inferred; lower-kebab; bundle hits=3
  GITLAB_SH = "gitlab-sh", // high-inferred; lower-kebab; bundle hits=2
  GOOGLE_DOCS, // value unresolved
  JIRA = "jira", // medium-cluster; compactCamel; bundle hits=7
  LINEAR = "linear", // medium-cluster; compactCamel; bundle hits=21
  NOTION = "notion", // medium-cluster; compactCamel; bundle hits=5
  PAGERDUTY = "pagerduty", // high-inferred; compactCamel; bundle hits=1
  SENTRY = "sentry", // medium-cluster; compactCamel; bundle hits=5
  SLACK = "slack", // medium-cluster; compactCamel; bundle hits=17
  WEB_PAGE = "web-page", // high-inferred; lower-kebab; bundle hits=2
}

