// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/types was imported by recovered sources but absent from sourcemap recovery.
export type OAuthTokenConfig = any;
export type SelfHostedOAuthTokenConfig = any;
