// @generated by drool.exe extraction
// Stub generated because src/utils/drools/types was imported by recovered sources but absent from sourcemap recovery.
export type ClaudeCodeSubagent = any;
export type ImportResult = any;
