// @generated by drool.exe extraction
// Generated from src/components/mission-control/enums; source module was missing in Bun sourcemap recovery.
export enum MissionControlView {
  FeatureDetail = "featureDetail", // high-inferred; compactCamel; bundle hits=5
  Features = "features", // high-inferred; compactCamel; bundle hits=51
  HandoffViewer = "handoffViewer", // high-inferred; compactCamel; bundle hits=5
  Main = "main", // medium-cluster; compactCamel; bundle hits=63
  MissionModelSelector = "missionModelSelector", // high-inferred; compactCamel; bundle hits=8
  MissionModels = "missionModels", // high-inferred; compactCamel; bundle hits=5
  SessionViewer = "sessionViewer", // high-inferred; compactCamel; bundle hits=5
  Workers = "workers", // medium-cluster; compactCamel; bundle hits=19
}

export enum MissionModelTarget {
  Validation = "validation", // high-inferred; compactCamel; bundle hits=46
  Worker = "worker", // medium-cluster; compactCamel; bundle hits=47
}

export enum SubagentState {
  Completed = "completed", // high-inferred; compactCamel; bundle hits=82
  Initializing = "initializing", // high-inferred; compactCamel; bundle hits=45
  LiveActivity, // value unresolved
}

