// @generated by drool.exe extraction
// Stub generated because src/utils/getReadinessHint/types was imported by recovered sources but absent from sourcemap recovery.
export type CachedReadinessHintState = any;
export type GapReadinessHint = any;
export type ReadinessHint = any;
