// @generated by drool.exe extraction
// Stub generated because packages/drool-sdk-ext/src/protocol/llm/types was imported by recovered sources but absent from sourcemap recovery.
export type BuiltInModelID = any;
export type ConcreteModelID = any;
export type CustomModelID = any;
export type FirestoreLLMModel = any;
export type RouterID = any;
