// @generated by drool.exe extraction
// Stub generated because src/utils/modelResolution/types was imported by recovered sources but absent from sourcemap recovery.
export type ResolveModelResult = any;
