// @generated by drool.exe extraction
// Stub generated because packages/environment/src/types was imported by recovered sources but absent from sourcemap recovery.
export type CreateEnvLoaderOptions = any;
export type EnvLoader = any;
export type EnvironmentInput = any;
export type EnvironmentVariableName = any;
export type IndustryEnvType = any;
export type IndustryEnvironment = any;
export type IndustryEnvironmentBase = any;
export type ResolveDeploymentEnvOptions = any;
export type ResolveEnvOptions = any;
