// @generated by drool.exe extraction
// Generated from src/components/review/enums; source module was missing in Bun sourcemap recovery.
export enum ReviewPresetType {
  BaseBranch = "baseBranch", // high-inferred; compactCamel; bundle hits=32
  Commit = "commit", // medium-cluster; compactCamel; bundle hits=33
  Custom = "custom", // medium-cluster; compactCamel; bundle hits=66
  Uncommitted = "uncommitted", // high-inferred; compactCamel; bundle hits=7
}

export enum ReviewStep {
  BaseBranch = "baseBranch", // high-inferred; compactCamel; bundle hits=32
  Commit = "commit", // medium-cluster; compactCamel; bundle hits=33
  CustomInstructions = "customInstructions", // high-inferred; compactCamel; bundle hits=24
  Preset = "preset", // medium-cluster; compactCamel; bundle hits=20
  Progress = "progress", // high-inferred; compactCamel; bundle hits=25
  Results = "results", // medium-cluster; compactCamel; bundle hits=30
}

