// @generated by drool.exe extraction
// Stub generated because src/components/review/types was imported by recovered sources but absent from sourcemap recovery.
export type BranchInfo = any;
export type CommitInfo = any;
export type ReviewPreset = any;
export type ReviewResults = any;
