// @generated by drool.exe extraction
// Generated from packages/common/src/llm/enums; source module was missing in Bun sourcemap recovery.
export enum VariantBadge {
  ResearchPreview, // value unresolved
}

