// @generated by drool.exe extraction
// Stub generated because packages/common/src/llm/types was imported by recovered sources but absent from sourcemap recovery.
export type ApiProviderLockInfo = any;
export type CommonToolDependencies = any;
export type LLMModel = any;
export type LLMModelWithProvider = any;
export type UserModelSelection = any;
export type getLLMModelParams = any;
