// @generated by drool.exe extraction
// Generated from packages/daemon-core/src/drool/enums; source module was missing in Bun sourcemap recovery.
export enum ActiveListenerLifecycleEventType {
  Connected = "connected", // high-inferred; compactCamel; bundle hits=61
  Disconnected = "disconnected", // high-inferred; compactCamel; bundle hits=34
  SessionClosed = "session_closed", // high-inferred; lower_snake; bundle hits=15
}

