// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/drool/types was imported by recovered sources but absent from sourcemap recovery.
export const DaemonSessionState: any = undefined as any;
export const DroolRegistryOptions: any = undefined as any;
export const RegisterClientParams: any = undefined as any;
