// @generated by drool.exe extraction
// Generated from packages/drool-sdk/src/enums; source module was missing in Bun sourcemap recovery.
export enum DroolClientEvent {
  ASK_USER = "askUser", // high-inferred; compactCamel; bundle hits=11
  REQUEST_PERMISSION = "request_permission", // high-inferred; lower_snake; bundle hits=3
  SESSION_NOTIFICATION = "sessionNotification", // high-inferred; compactCamel; bundle hits=4
}

export enum DroolProcessMode {
  Acp = "acp", // medium-cluster; compactCamel; bundle hits=19
  StreamJsonRpc, // value unresolved
}

export enum TransportDirection {
  In = "in", // medium-cluster; compactCamel; bundle hits=62
  Out = "out", // medium-cluster; compactCamel; bundle hits=47
  OutFailed = "out_failed", // high-inferred; lower_snake; bundle hits=3
}

