// @generated by drool.exe extraction
// Stub generated because packages/drool-sdk/src/types was imported by recovered sources but absent from sourcemap recovery.
export const DroolEventMap: any = undefined as any;
export const DroolProcessConfig: any = undefined as any;
export const ManagedProcess: any = undefined as any;
export const SpawnWithRetryOptions: any = undefined as any;
