// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/llms/client/structured-output/types was imported by recovered sources but absent from sourcemap recovery.
export type StructuredOutputErrorInfo = any;
export type StructuredOutputValidationResult = any;
