// @generated by drool.exe extraction
// Generated from src/services/squad/enums; source module was missing in Bun sourcemap recovery.
export enum SquadAgentStatus {
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Pending = "pending", // medium-cluster; compactCamel; bundle hits=67
  Running = "running", // medium-cluster; compactCamel; bundle hits=69
  Stopped = "stopped", // medium-cluster; compactCamel; bundle hits=27
}

export enum SquadNotificationType {
  DM = "dm", // medium-cluster; compactCamel; bundle hits=14
  Mention = "mention", // medium-cluster; compactCamel; bundle hits=13
  Thread = "thread", // medium-cluster; compactCamel; bundle hits=15
}

export enum SquadRole {
  Orchestrator = "orchestrator", // high-inferred; compactCamel; bundle hits=41
  Worker = "worker", // medium-cluster; compactCamel; bundle hits=47
}

export enum SquadStatus {
  Running = "running", // medium-cluster; compactCamel; bundle hits=69
  Starting = "starting", // high-inferred; compactCamel; bundle hits=15
  Stopped = "stopped", // medium-cluster; compactCamel; bundle hits=27
}

