// @generated by drool.exe extraction
// Stub generated because src/services/squad/types was imported by recovered sources but absent from sourcemap recovery.
export type SquadAgent = any;
export type SquadBoardMessage = any;
export type SquadBoardNotification = any;
export type SquadBoardSnapshot = any;
export type SquadBootstrapResult = any;
export type SquadDmConversationSnapshot = any;
export type SquadLane = any;
export type SquadOverview = any;
export type SquadRuntimeState = any;
export type SquadSessionTagMetadata = any;
export type SquadState = any;
