// @generated by drool.exe extraction
// Generated from packages/common/src/organization/onboarding/enums; source module was missing in Bun sourcemap recovery.
export enum OnboardingWorkRole {
  Design = "design", // medium-cluster; compactCamel; bundle hits=2
  Engineering = "engineering", // high-inferred; compactCamel; bundle hits=3
  Finance = "finance", // medium-cluster; compactCamel; bundle hits=1
  Marketing = "marketing", // high-inferred; compactCamel; bundle hits=1
  Operations = "operations", // high-inferred; compactCamel; bundle hits=18
  Product = "product", // medium-cluster; compactCamel; bundle hits=8
  Sales = "sales", // medium-cluster; compactCamel; bundle hits=1
  SomethingElse = "something-else", // high-inferred; lower-kebab; bundle hits=2
}

