// @generated by drool.exe extraction
// Generated from src/exec/enums; source module was missing in Bun sourcemap recovery.
export enum ExecSummarySubtype {
  Failure = "failure", // medium-cluster; compactCamel; bundle hits=45
  Success = "success", // medium-cluster; compactCamel; bundle hits=81
}

export enum ExecSummaryType {
  Result = "result", // medium-cluster; compactCamel; bundle hits=66
}

