// @generated by drool.exe extraction
// Generated from src/i18n/enums; source module was missing in Bun sourcemap recovery.
export enum SupportedLocale {
  English = "en", // exact: recovered from i18n resource keys and SUPPORTED_LOCALES order
  Italian = "it", // exact: recovered from i18n resource keys and SUPPORTED_LOCALES order
  Japanese = "ja", // exact: recovered from i18n resource keys and SUPPORTED_LOCALES order
  ChineseSimplified = "zh-CN", // exact: recovered from i18n resource keys and SUPPORTED_LOCALES order
  Korean = "ko", // exact: recovered from i18n resource keys and SUPPORTED_LOCALES order
}

