// @generated by drool.exe extraction
// Generated from packages/logging/src/errors/enums; source module was missing in Bun sourcemap recovery.
export enum HttpStatusCode {
  Ok = 200, // exact: recovered from HttpStatusTitle bundle map ("OK")
  Created = 201, // exact: recovered from HttpStatusTitle bundle map ("Created")
  Accepted = 202, // exact: recovered from HttpStatusTitle bundle map ("Accepted")
  NoContent = 204, // exact: recovered from HttpStatusTitle bundle map ("No Content")
  BadRequest = 400, // exact: recovered from HttpStatusTitle bundle map ("Bad Request")
  Unauthorized = 401, // exact: recovered from HttpStatusTitle bundle map ("Unauthorized")
  PaymentRequired = 402, // exact: recovered from HttpStatusTitle bundle map ("Payment Required")
  Forbidden = 403, // exact: recovered from HttpStatusTitle bundle map ("Forbidden")
  NotFound = 404, // exact: recovered from HttpStatusTitle bundle map ("Not Found")
  MethodNotAllowed = 405, // exact: recovered from HttpStatusTitle bundle map ("Method Not Allowed")
  Conflict = 409, // exact: recovered from HttpStatusTitle bundle map ("Conflict")
  Gone = 410, // exact: recovered from HttpStatusTitle bundle map ("Gone")
  ContentTooLarge = 413, // exact: recovered from HttpStatusTitle bundle map ("Content Too Large")
  InvalidData = 422, // exact: recovered from HttpStatusTitle bundle map ("Invalid Data")
  FailedDependency = 424, // exact: recovered from HttpStatusTitle bundle map ("Failed Dependency")
  PreconditionRequired = 428, // exact: recovered from HttpStatusTitle bundle map ("Precondition Required")
  RateLimitExceeded = 429, // exact: recovered from HttpStatusTitle bundle map ("Rate Limit Exceeded")
  UnavailableForLegalReasons = 451, // exact: recovered from HttpStatusTitle bundle map ("Unavailable For Legal Reasons")
  ClientClosedRequest = 499, // exact: recovered from HttpStatusTitle bundle map ("Client Closed Request")
  InternalServerError = 500, // exact: recovered from HttpStatusTitle bundle map ("Internal Server Error")
  NotImplemented = 501, // exact: recovered from HttpStatusTitle bundle map ("Not Implemented")
  BadGateway = 502, // exact: recovered from HttpStatusTitle bundle map ("Bad Gateway")
  ServiceUnavailable = 503, // exact: recovered from HttpStatusTitle bundle map ("Service Unavailable")
  GatewayTimeout = 504, // exact: recovered from HttpStatusTitle bundle map ("Gateway Timeout")
}

