// @generated by drool.exe extraction
// Stub generated because packages/logging/src/errors/types was imported by recovered sources but absent from sourcemap recovery.
export const PublicErrorResponse: any = undefined as any;
