// @generated by drool.exe extraction
// Generated from packages/daemon-client/src/enums; source module was missing in Bun sourcemap recovery.
export enum DaemonAuthenticationMode {
  Token = "token", // medium-cluster; compactCamel; bundle hits=39
  Trusted = "trusted", // medium-cluster; compactCamel; bundle hits=3
}

export enum DaemonClientErrorCode {
  ClientDestroyed, // value unresolved
  ComputeLimitExceeded = "compute_limit_exceeded", // high-inferred; lower_snake; bundle hits=3
  ConnectionClosed, // value unresolved
  JsonRpcError, // value unresolved
  RelayConnection = "relayConnection", // high-inferred; compactCamel; bundle hits=1
  RequestTimeout = "requestTimeout", // high-inferred; compactCamel; bundle hits=21
  WsConnectionError, // value unresolved
}

