// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/types was imported by recovered sources but absent from sourcemap recovery.
export type BuildDaemonRequestOptions = any;
export type DaemonClientConfig = any;
export type IDaemonClient = any;
export type PendingRequest = any;
export type RelayAuthTransport = any;
export type TunnelConnectionEvents = any;
export type TunnelConnectionOptions = any;
export type WebSocketConnectionConfig = any;
