// @generated by drool.exe extraction
// Stub generated because src/acp/types was imported by recovered sources but absent from sourcemap recovery.
export type AcpChildOptions = any;
export type AvailableCommand = any;
