// @generated by drool.exe extraction
// Stub generated because packages/utils/src/secretScrubber/types was imported by recovered sources but absent from sourcemap recovery.
export type CommandHook = any;
export type GitExecutor = any;
export type GitExecutorParams = any;
export type PreExecContext = any;
export type SecretFinding = any;
export type SecretScanOptions = any;
