// @generated by drool.exe extraction
// Stub generated because src/components/chat/types was imported by recovered sources but absent from sourcemap recovery.
export const ChatFileSuggestionsOptions: any = undefined as any;
export const ChatInputApi: any = undefined as any;
export const ChatInputProps: any = undefined as any;
export const ColorPalette: any = undefined as any;
export const FileSuggestion: any = undefined as any;
