// @generated by drool.exe extraction
// Generated from packages/logging/src/tracing/enums; source module was missing in Bun sourcemap recovery.
export enum ClientUiSurface {
  CliAcp = "cli_acp", // high-inferred; lower_snake; bundle hits=7
  CliExec = "cli_exec", // high-inferred; lower_snake; bundle hits=7
  CliTui = "cli_tui", // high-inferred; lower_snake; bundle hits=11
  Desktop = "desktop", // medium-cluster; compactCamel; bundle hits=16
  Web = "web", // medium-cluster; compactCamel; bundle hits=25
}

export enum IndustryDaemonTransport {
  InProcess = "in_process", // high-inferred; lower_snake; bundle hits=4
  Ipc = "ipc", // medium-cluster; compactCamel; bundle hits=9
  WsDirect = "ws_direct", // high-inferred; lower_snake; bundle hits=1
  WsLocalhost = "ws_localhost", // high-inferred; lower_snake; bundle hits=2
  WsRelay = "ws_relay", // high-inferred; lower_snake; bundle hits=3
}

export enum SessionKind {
  Automation = "automation", // high-inferred; compactCamel; bundle hits=40
  Delegation = "delegation", // high-inferred; compactCamel; bundle hits=1
  MissionWorker = "mission_worker", // high-inferred; lower_snake; bundle hits=1
  Subagent = "subagent", // high-inferred; compactCamel; bundle hits=13
  User = "user", // medium-cluster; compactCamel; bundle hits=80
}

export enum SpanAttribute {
  ERROR_TYPE = "errorType", // high-inferred; compactCamel; bundle hits=30
  INDUSTRY_CLIENT_SURFACE = "industry.client.surface", // high-inferred; lower.dot; bundle hits=4
  INDUSTRY_DAEMON_CONNECT_ATTEMPTS, // value unresolved
  INDUSTRY_DAEMON_CONNECT_ATTEMPT_INDEX, // value unresolved
  INDUSTRY_DAEMON_TRANSPORT = "industry.daemon.transport", // high-inferred; lower.dot; bundle hits=7
  INDUSTRY_MACHINE_PROVIDER = "industry.machine.provider", // high-inferred; lower.dot; bundle hits=4
  INDUSTRY_MACHINE_TYPE = "industry.machine.type", // high-inferred; lower.dot; bundle hits=7
  INDUSTRY_RELAY_AUTH_REQUIREMENT, // value unresolved
  INDUSTRY_RELAY_CLIENT_ID, // value unresolved
  INDUSTRY_RELAY_COMPUTER_ID, // value unresolved
  INDUSTRY_RELAY_CONNECT_CREDENTIAL_MS, // value unresolved
  INDUSTRY_RELAY_CONNECT_HANDSHAKE_MS, // value unresolved
  INDUSTRY_RELAY_CONNECT_IS_INITIAL, // value unresolved
  INDUSTRY_RELAY_CONNECT_PROBE_MS, // value unresolved
  INDUSTRY_RELAY_CONNECT_SOCKET_MS, // value unresolved
  INDUSTRY_RELAY_CONNECT_TOTAL_MS, // value unresolved
  INDUSTRY_RELAY_DIRECTION = "industry.relay.direction", // high-inferred; lower.dot; bundle hits=4
  INDUSTRY_RELAY_TUNNEL = "industry.relay.tunnel", // high-inferred; lower.dot; bundle hits=4
  INDUSTRY_RPC_TIMED_OUT, // value unresolved
  INDUSTRY_SESSION_CALLING_TOOL_USE_ID, // value unresolved
  INDUSTRY_SESSION_KIND = "industry.session.kind", // high-inferred; lower.dot; bundle hits=2
  INDUSTRY_SESSION_ORIGIN = "industry.session.origin", // high-inferred; lower.dot; bundle hits=2
  INDUSTRY_SESSION_PARENT_ID, // value unresolved
  NOTIFICATION_TYPE = "notificationType", // high-inferred; compactCamel; bundle hits=14
  RPC_INDUSTRY_PROTOCOL_VERSION = "rpc.industry_protocol_version", // high-inferred; domain.rest_snake; bundle hits=2
  RPC_METHOD = "rpc.method", // high-inferred; lower.dot; bundle hits=26
  RPC_REQUEST_ID = "rpc.request_id", // high-inferred; domain.rest_snake; bundle hits=18
  RPC_RESPONSE_STATUS_CODE, // value unresolved
  SESSION_ID = "sessionId", // high-inferred; compactCamel; bundle hits=36
  WEBSOCKET_CLOSE_CODE = "websocket.close_code", // high-inferred; domain.rest_snake; bundle hits=2
  WEBSOCKET_CLOSE_REASON = "websocket.close_reason", // high-inferred; domain.rest_snake; bundle hits=2
  WEBSOCKET_CONNECTION_ID = "websocket.connection_id", // high-inferred; domain.rest_snake; bundle hits=4
  WEBSOCKET_URL = "websocket.url", // high-inferred; lower.dot; bundle hits=4
}

export enum SpanEvent {
  CLOSED = "closed", // medium-cluster; compactCamel; bundle hits=8
  CONNECTED = "connected", // high-inferred; compactCamel; bundle hits=61
  CONNECTING = "connecting", // high-inferred; compactCamel; bundle hits=48
  ERROR = "error", // medium-cluster; compactCamel; bundle hits=96
  SENDING = "sending", // medium-cluster; compactCamel; bundle hits=4
  SENT = "sent", // medium-cluster; compactCamel; bundle hits=25
  TIMEOUT = "timeout", // medium-cluster; compactCamel; bundle hits=61
}

export enum SpanName {
  CLI_CREATE_SESSION = "cli.create_session", // high-inferred; domain.rest_snake; bundle hits=1
  CLI_RECEIVE_ASK_USER_REQUEST = "cli.receive_ask_user_request", // high-inferred; domain.rest_snake; bundle hits=1
  CLI_RECEIVE_NOTIFICATION = "cli.receive_notification", // high-inferred; domain.rest_snake; bundle hits=1
  CLI_RECEIVE_PERMISSION_REQUEST = "cli.receive_permission_request", // high-inferred; domain.rest_snake; bundle hits=1
  CLI_REQUEST_ASK_USER = "cli.request_ask_user", // high-inferred; domain.rest_snake; bundle hits=1
  CLI_REQUEST_PERMISSION = "cli.request_permission", // high-inferred; domain.rest_snake; bundle hits=2
  CLI_RPC_REQUEST = "cli.rpc_request", // high-inferred; domain.rest_snake; bundle hits=2
  CLI_SEND_NOTIFICATION = "cli.send_notification", // high-inferred; domain.rest_snake; bundle hits=1
  COMPUTER_ENSURE_RUNNING = "computer.ensure_running", // high-inferred; domain.rest_snake; bundle hits=2
  DAEMON_AUTHENTICATE = "daemon.authenticate", // high-inferred; lower.dot; bundle hits=11
  DAEMON_DROOL_SPAWN = "daemon.drool_spawn", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_IDLE_UPDATE = "daemon.idle_update", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RECEIVE_ASK_USER_REQUEST = "daemon.receive_ask_user_request", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RECEIVE_NOTIFICATION = "daemon.receive_notification", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RECEIVE_PERMISSION_REQUEST = "daemon.receive_permission_request", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RELAY_CONNECT = "daemon.relay_connect", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RPC_DISPATCH = "daemon.rpc_dispatch", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_RPC_REQUEST = "daemon.rpc_request", // high-inferred; domain.rest_snake; bundle hits=1
  DAEMON_TERMINAL_CREATE = "daemon.terminal_create", // high-inferred; domain.rest_snake; bundle hits=1
  RELAY_FORWARD = "relay.forward", // high-inferred; lower.dot; bundle hits=2
  WEBSOCKET_CONNECT = "websocket.connect", // high-inferred; lower.dot; bundle hits=2
  WEB_DAEMON_AUTHENTICATE = "web.daemon.authenticate", // high-inferred; lower.dot; bundle hits=1
  WEB_DAEMON_CONNECT_ATTEMPT, // value unresolved
  WEB_RECEIVE_ASK_USER_REQUEST = "web.receive_ask_user_request", // high-inferred; domain.rest_snake; bundle hits=1
  WEB_RECEIVE_NOTIFICATION = "web.receive_notification", // high-inferred; domain.rest_snake; bundle hits=1
  WEB_RECEIVE_PERMISSION_REQUEST = "web.receive_permission_request", // high-inferred; domain.rest_snake; bundle hits=1
  WEB_RELAY_AUTH = "web.relay_auth", // high-inferred; domain.rest_snake; bundle hits=1
  WEB_RELAY_AUTH_HANDSHAKE, // value unresolved
  WEB_RELAY_AUTH_PROBE, // value unresolved
  WEB_RELAY_AUTH_TOKEN_FETCH, // value unresolved
  WEB_RPC_REQUEST = "web.rpc_request", // high-inferred; domain.rest_snake; bundle hits=1
}

