// @generated by drool.exe extraction
// Stub generated because packages/logging/src/tracing/types was imported by recovered sources but absent from sourcemap recovery.
export type DerivedSessionAttribution = any;
export type IndustryCreateSessionSpanParams = any;
export type IndustrySessionAttributionParams = any;
export type IndustrySessionOrigin = any;
export type SessionAttributionPlatform = any;
