// @generated by drool.exe extraction
// Stub generated because packages/utils/src/api/types was imported by recovered sources but absent from sourcemap recovery.
export const IndustryApiConfig: any = undefined as any;
