// @generated by drool.exe extraction
// Stub generated because packages/utils/src/workspaces/download was imported by recovered sources but absent from sourcemap recovery.
export const downloadFromUrl: any = undefined as any;
export const downloadTextFile: any = undefined as any;
