// @generated by drool.exe extraction
// Stub generated because packages/utils/src/workspaces/logs was imported by recovered sources but absent from sourcemap recovery.
export const formatBuildTimestamp: any = undefined as any;
export const formatWorkspaceLogs: any = undefined as any;
