// @generated by drool.exe extraction
// Stub generated because packages/utils/src/workspaces/outdated was imported by recovered sources but absent from sourcemap recovery.
export const workspaceOutOfDate: any = undefined as any;
