// @generated by drool.exe extraction
// Stub generated because packages/utils/src/workspaces/sandbox was imported by recovered sources but absent from sourcemap recovery.
export const getSandboxWebSocketUrl: any = undefined as any;
