// @generated by drool.exe extraction
// Stub generated because packages/utils/src/workspaces/types was imported by recovered sources but absent from sourcemap recovery.
export type FormattedLogLine = any;
