// @generated by drool.exe extraction
// Stub generated because src/utils/toolAvailability/types was imported by recovered sources but absent from sourcemap recovery.
export const ToolEnablementResult: any = undefined as any;
