// @generated by drool.exe extraction
// Generated from src/services/btw/enums; source module was missing in Bun sourcemap recovery.
export enum BtwEntryStatus {
  Complete = "complete", // high-inferred; compactCamel; bundle hits=38
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Pending = "pending", // medium-cluster; compactCamel; bundle hits=67
  Streaming = "streaming", // high-inferred; compactCamel; bundle hits=21
}

