// @generated by drool.exe extraction
// Stub generated because packages/runtime/auth/src/auth/workos/types was imported by recovered sources but absent from sourcemap recovery.
export type WorkosConfig = any;
export type WorkosConfigInput = any;
