// @generated by drool.exe extraction
// Stub generated because packages/utils/src/agent-browser was imported by recovered sources but absent from sourcemap recovery.
export const isAgentBrowserCommand: any = undefined as any;
