// @generated by drool.exe extraction
// Stub generated because packages/utils/src/format was imported by recovered sources but absent from sourcemap recovery.
export const formatCompactNumber: any = undefined as any;
const defaultExport: any = undefined as any;
export default defaultExport;
