// @generated by drool.exe extraction
// Stub generated because packages/utils/src/time was imported by recovered sources but absent from sourcemap recovery.
export const sleep: any = undefined as any;
const defaultExport: any = undefined as any;
export default defaultExport;
