// @generated by drool.exe extraction
// Stub generated because packages/common/src/cli/types was imported by recovered sources but absent from sourcemap recovery.
export type HookCommand = any;
export type HookConfig = any;
export type HooksSettings = any;
export type StatusLineConfig = any;
export type TuiModelConfig = any;
