// @generated by drool.exe extraction
// Stub generated because packages/utils/src/format/types was imported by recovered sources but absent from sourcemap recovery.
export type FormatCompactNumberOptions = any;
