// @generated by drool.exe extraction
// Generated from src/services/enums; source module was missing in Bun sourcemap recovery.
export enum PrProvider {
  GitHub, // value unresolved
  GitLab, // value unresolved
}

export enum PrStatus {
  Found = "found", // medium-cluster; compactCamel; bundle hits=33
  Idle = "idle", // medium-cluster; compactCamel; bundle hits=42
  Loading = "loading", // medium-cluster; compactCamel; bundle hits=37
  NotFound = "notFound", // high-inferred; compactCamel; bundle hits=30
}

export enum TokenLimitAction {
  Cancel = "cancel", // medium-cluster; compactCamel; bundle hits=57
  DroolCore = "droolCore", // high-inferred; compactCamel; bundle hits=19
  OpenBilling = "openBilling", // high-inferred; compactCamel; bundle hits=5
}

export enum VSCodeExtensionPromptState {
  COMPLETED = "completed", // high-inferred; compactCamel; bundle hits=82
  ERROR = "error", // medium-cluster; compactCamel; bundle hits=96
  INSTALLING = "installing", // high-inferred; compactCamel; bundle hits=51
  PROMPT = "prompt", // medium-cluster; compactCamel; bundle hits=61
}

export enum VSCodeExtensionStatus {
  CHECKING = "checking", // high-inferred; compactCamel; bundle hits=33
  INSTALLED = "installed", // high-inferred; compactCamel; bundle hits=30
  INSTALLING = "installing", // high-inferred; compactCamel; bundle hits=51
  NOT_INSTALLED = "not-installed", // high-inferred; lower-kebab; bundle hits=5
  SHOULD_PROMPT = "should-prompt", // high-inferred; lower-kebab; bundle hits=4
  SKIP = "skip", // medium-cluster; compactCamel; bundle hits=29
  UNAVAILABLE = "unavailable", // high-inferred; compactCamel; bundle hits=32
}

