// @generated by drool.exe extraction
// Generated from packages/utils/src/automations/enums; source module was missing in Bun sourcemap recovery.
export enum VisualPolicyBranch {
  Create = "create", // medium-cluster; compactCamel; bundle hits=68
  Preserve = "preserve", // high-inferred; compactCamel; bundle hits=13
  Rebuild = "rebuild", // medium-cluster; compactCamel; bundle hits=4
}

