// @generated by drool.exe extraction
// Stub generated because packages/utils/src/automations/types was imported by recovered sources but absent from sourcemap recovery.
export type AutomationRunFailureReason = any;
export type AutomationRunTriggerSource = any;
export type BuildAutomationRunLabelsInput = any;
export type DetectedVisualBrandIssue = any;
export type VisualPolicyDecision = any;
