// @generated by drool.exe extraction
// Generated from packages/drool-core/src/streaming/enums; source module was missing in Bun sourcemap recovery.
export enum LanguageModelFinishReason {
  ContentFilter = "content_filter", // high-inferred; lower_snake; bundle hits=5
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Length = "length", // medium-cluster; compactCamel; bundle hits=62
  ModelContextWindowExceeded = "model_context_window_exceeded", // high-inferred; lower_snake; bundle hits=2
  PauseTurn = "pause_turn", // high-inferred; lower_snake; bundle hits=2
  Stop = "stop", // medium-cluster; compactCamel; bundle hits=35
  ToolCalls = "toolCalls", // high-inferred; compactCamel; bundle hits=5
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
}

