// @generated by drool.exe extraction
// Generated from packages/drool-core/src/tools/definitions/cli/enums; source module was missing in Bun sourcemap recovery.
export enum ExecuteCliRuntimeShell {
  Posix = "posix", // medium-cluster; compactCamel; bundle hits=9
  PowerShell5, // value unresolved
  PowerShell7, // value unresolved
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
  WslBash = "wsl-bash", // high-inferred; lower-kebab; bundle hits=4
}

