// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/tools/definitions/cli/types was imported by recovered sources but absent from sourcemap recovery.
export type SessionModelUpgradeToolInput = any;
