// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/llms/client/bedrock/types was imported by recovered sources but absent from sourcemap recovery.
export type BedrockClientConfig = any;
export type CachedCredentials = any;
export type ResolveBedrockClientConfigParams = any;
export type ResolvedCredentials = any;
