// @generated by drool.exe extraction
// Stub generated because builtin-skills/install-triage/assets/run_triage.py was imported by recovered sources but absent from sourcemap recovery.
const defaultExport: any = undefined as any;
export default defaultExport;
