// @generated by drool.exe extraction
// Generated from src/services/mcp/enums; source module was missing in Bun sourcemap recovery.
export enum McpServiceEventType {
  AUTH_COMPLETED = "auth_completed", // high-inferred; lower_snake; bundle hits=4
  AUTH_REQUIRED = "authRequired", // high-inferred; compactCamel; bundle hits=1
  ERROR = "error", // medium-cluster; compactCamel; bundle hits=96
  OAUTH_SUPPORT_UPDATED = "oauth_support_updated", // high-inferred; lower_snake; bundle hits=4
  SERVERS_RELOADED = "servers_reloaded", // high-inferred; lower_snake; bundle hits=13
  SERVERS_RELOADING = "servers_reloading", // high-inferred; lower_snake; bundle hits=6
  SERVER_STARTED = "server_started", // high-inferred; lower_snake; bundle hits=6
  SERVER_STOPPED = "server_stopped", // high-inferred; lower_snake; bundle hits=3
  TOOLS_UPDATED = "tools_updated", // high-inferred; lower_snake; bundle hits=8
}

