// @generated by drool.exe extraction
// Stub generated because src/services/mcp/types was imported by recovered sources but absent from sourcemap recovery.
export type McpAuthCompletedInfo = any;
export type McpAuthRequiredInfo = any;
export type McpServiceEventMap = any;
