import { TuiSpinnerPresetName } from '@/utils/tuiSpinner/enums';
import type { TuiSpinnerPresetDefinition } from '@/utils/tuiSpinner/types';

export const TUI_SPINNER_DEFAULT_PRESET = TuiSpinnerPresetName.Dots;

export const tuiSpinnerPresets = {
  [TuiSpinnerPresetName.Arrow]: {
    frames: ['←', '↖', '↑', '↗', '→', '↘', '↓', '↙'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Arc]: {
    frames: ['◜', '◠', '◝', '◞', '◡', '◟'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Balloon]: {
    frames: ['.', 'o', 'O', 'o', '.'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.Bounce]: {
    frames: ['⠁', '⠂', '⠄', '⡀', '⠄', '⠂'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.Breathe]: {
    frames: [
      '⠀',
      '⠂',
      '⠌',
      '⡑',
      '⢕',
      '⢝',
      '⣫',
      '⣟',
      '⣿',
      '⣟',
      '⣫',
      '⢝',
      '⢕',
      '⡑',
      '⠌',
      '⠂',
      '⠀',
    ],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.CircleHalves]: {
    frames: ['◐', '◓', '◑', '◒'],
    intervalMs: 50,
  },
  [TuiSpinnerPresetName.Dots]: {
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots2]: {
    frames: ['⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots3]: {
    frames: ['⠋', '⠙', '⠚', '⠞', '⠖', '⠦', '⠴', '⠲', '⠳', '⠓'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots4]: {
    frames: [
      '⠄',
      '⠆',
      '⠇',
      '⠋',
      '⠙',
      '⠸',
      '⠰',
      '⠠',
      '⠰',
      '⠸',
      '⠙',
      '⠋',
      '⠇',
      '⠆',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots5]: {
    frames: [
      '⠋',
      '⠙',
      '⠚',
      '⠒',
      '⠂',
      '⠂',
      '⠒',
      '⠲',
      '⠴',
      '⠦',
      '⠖',
      '⠒',
      '⠐',
      '⠐',
      '⠒',
      '⠓',
      '⠋',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots6]: {
    frames: [
      '⠁',
      '⠉',
      '⠙',
      '⠚',
      '⠒',
      '⠂',
      '⠂',
      '⠒',
      '⠲',
      '⠴',
      '⠤',
      '⠄',
      '⠄',
      '⠤',
      '⠴',
      '⠲',
      '⠒',
      '⠂',
      '⠂',
      '⠒',
      '⠚',
      '⠙',
      '⠉',
      '⠁',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots7]: {
    frames: [
      '⠈',
      '⠉',
      '⠋',
      '⠓',
      '⠒',
      '⠐',
      '⠐',
      '⠒',
      '⠖',
      '⠦',
      '⠤',
      '⠠',
      '⠠',
      '⠤',
      '⠦',
      '⠖',
      '⠒',
      '⠐',
      '⠐',
      '⠒',
      '⠓',
      '⠋',
      '⠉',
      '⠈',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots8]: {
    frames: [
      '⠁',
      '⠁',
      '⠉',
      '⠙',
      '⠚',
      '⠒',
      '⠂',
      '⠂',
      '⠒',
      '⠲',
      '⠴',
      '⠤',
      '⠄',
      '⠄',
      '⠤',
      '⠠',
      '⠠',
      '⠤',
      '⠦',
      '⠖',
      '⠒',
      '⠐',
      '⠐',
      '⠒',
      '⠓',
      '⠋',
      '⠉',
      '⠈',
      '⠈',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots9]: {
    frames: ['⢹', '⢺', '⢼', '⣸', '⣇', '⡧', '⡗', '⡏'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots10]: {
    frames: ['⢄', '⢂', '⢁', '⡁', '⡈', '⡐', '⡠'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Dots11]: {
    frames: ['⠁', '⠂', '⠄', '⡀', '⢀', '⠠', '⠐', '⠈'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Dots13]: {
    frames: ['⣼', '⣹', '⢻', '⠿', '⡟', '⣏', '⣧', '⣶'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.DotsClockwise]: {
    frames: [
      '⠙',
      '⠘',
      '⠸',
      '⠰',
      '⢰',
      '⢠',
      '⣠',
      '⣀',
      '⣄',
      '⡄',
      '⡆',
      '⠆',
      '⠇',
      '⠃',
      '⠋',
      '⠉',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.CircleQuarters]: {
    frames: ['◴', '◷', '◶', '◵'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.Clock]: {
    frames: [
      '🕛',
      '🕐',
      '🕑',
      '🕒',
      '🕓',
      '🕔',
      '🕕',
      '🕖',
      '🕗',
      '🕘',
      '🕙',
      '🕚',
    ],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.DoubleArrow]: {
    frames: ['⇐', '⇖', '⇑', '⇗', '⇒', '⇘', '⇓', '⇙'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Dqpb]: {
    frames: ['d', 'q', 'p', 'b'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Earth]: {
    frames: ['🌍', '🌎', '🌏'],
    intervalMs: 180,
  },
  [TuiSpinnerPresetName.GrowHorizontal]: {
    frames: ['▏', '▎', '▍', '▌', '▋', '▊', '▉', '▊', '▋', '▌', '▍', '▎'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.GrowVertical]: {
    frames: ['▁', '▃', '▄', '▅', '▆', '▇', '▆', '▅', '▄', '▃'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.Hearts]: {
    frames: ['🩷', '🧡', '💛', '💚', '💙', '🩵', '💜', '🤎', '🖤', '🩶', '🤍'],
    intervalMs: 120,
  },
  [TuiSpinnerPresetName.Moon]: {
    frames: ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘'],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Orbit]: {
    frames: ['⠃', '⠉', '⠘', '⠰', '⢠', '⣀', '⡄', '⠆'],
    intervalMs: 100,
  },
  [TuiSpinnerPresetName.Sand]: {
    frames: [
      '⠁',
      '⠂',
      '⠄',
      '⡀',
      '⡈',
      '⡐',
      '⡠',
      '⣀',
      '⣁',
      '⣂',
      '⣄',
      '⣌',
      '⣔',
      '⣤',
      '⣥',
      '⣦',
      '⣮',
      '⣶',
      '⣷',
      '⣿',
      '⡿',
      '⠿',
      '⢟',
      '⠟',
      '⡛',
      '⠛',
      '⠫',
      '⢋',
      '⠋',
      '⠍',
      '⡉',
      '⠉',
      '⠑',
      '⠡',
      '⢁',
    ],
    intervalMs: 80,
  },
  [TuiSpinnerPresetName.Speaker]: {
    frames: ['🔈', '🔉', '🔊', '🔉'],
    intervalMs: 160,
  },
  [TuiSpinnerPresetName.SquareCorners]: {
    frames: ['◰', '◳', '◲', '◱'],
    intervalMs: 180,
  },
  [TuiSpinnerPresetName.Toggle]: {
    frames: ['⊶', '⊷'],
    intervalMs: 250,
  },
  [TuiSpinnerPresetName.Triangle]: {
    frames: ['◢', '◣', '◤', '◥'],
    intervalMs: 50,
  },
  [TuiSpinnerPresetName.Weather]: {
    frames: ['☀️', '🌤', '⛅️', '🌥', '☁️', '🌧', '🌨', '⛈'],
    intervalMs: 100,
  },
} as const satisfies Record<TuiSpinnerPresetName, TuiSpinnerPresetDefinition>;
