// @generated by drool.exe extraction
// Generated from src/utils/tuiSpinner/enums; source module was missing in Bun sourcemap recovery.
export enum TuiSpinnerPresetName {
  Arc = "arc", // medium-cluster; compactCamel; bundle hits=5
  Arrow = "arrow", // medium-cluster; compactCamel; bundle hits=39
  Balloon = "balloon", // medium-cluster; compactCamel; bundle hits=1
  Bounce = "bounce", // medium-cluster; compactCamel; bundle hits=1
  Breathe = "breathe", // medium-cluster; compactCamel; bundle hits=1
  CircleHalves = "circleHalves", // high-inferred; compactCamel; bundle hits=1
  CircleQuarters = "circleQuarters", // high-inferred; compactCamel; bundle hits=1
  Clock = "clock", // medium-cluster; compactCamel; bundle hits=2
  Dots = "dots", // medium-cluster; compactCamel; bundle hits=5
  Dots10 = "dots10", // medium-cluster; compactCamel; bundle hits=2
  Dots11 = "dots11", // medium-cluster; compactCamel; bundle hits=1
  Dots13 = "dots13", // medium-cluster; compactCamel; bundle hits=1
  Dots2 = "dots2", // medium-cluster; compactCamel; bundle hits=1
  Dots3 = "dots3", // medium-cluster; compactCamel; bundle hits=1
  Dots4 = "dots4", // medium-cluster; compactCamel; bundle hits=1
  Dots5 = "dots5", // medium-cluster; compactCamel; bundle hits=1
  Dots6 = "dots6", // medium-cluster; compactCamel; bundle hits=1
  Dots7 = "dots7", // medium-cluster; compactCamel; bundle hits=1
  Dots8 = "dots8", // medium-cluster; compactCamel; bundle hits=1
  Dots9 = "dots9", // medium-cluster; compactCamel; bundle hits=1
  DotsClockwise = "dotsClockwise", // high-inferred; compactCamel; bundle hits=2
  DoubleArrow = "doubleArrow", // high-inferred; compactCamel; bundle hits=1
  Dqpb = "dqpb", // medium-cluster; compactCamel; bundle hits=1
  Earth = "earth", // medium-cluster; compactCamel; bundle hits=1
  GrowHorizontal = "growHorizontal", // high-inferred; compactCamel; bundle hits=1
  GrowVertical = "growVertical", // high-inferred; compactCamel; bundle hits=1
  Hearts = "hearts", // medium-cluster; compactCamel; bundle hits=1
  Moon = "moon", // medium-cluster; compactCamel; bundle hits=2
  Orbit = "orbit", // medium-cluster; compactCamel; bundle hits=1
  Sand = "sand", // medium-cluster; compactCamel; bundle hits=6
  Speaker = "speaker", // medium-cluster; compactCamel; bundle hits=2
  SquareCorners = "squareCorners", // high-inferred; compactCamel; bundle hits=1
  Toggle = "toggle", // medium-cluster; compactCamel; bundle hits=16
  Triangle = "triangle", // high-inferred; compactCamel; bundle hits=2
  Weather = "weather", // medium-cluster; compactCamel; bundle hits=1
}

