// @generated by drool.exe extraction
// Stub generated because src/utils/tuiSpinner/types was imported by recovered sources but absent from sourcemap recovery.
export type TuiSpinnerPresetDefinition = any;
export type TuiSpinnerPresetInput = any;
export type TuiSpinnerStatusBannerConfig = any;
export type TuiSpinnerStatusBannerInput = any;
