// @generated by drool.exe extraction
// Stub generated because src/utils/markdown/types was imported by recovered sources but absent from sourcemap recovery.
export const MarkdownConfig: any = undefined as any;
export const MarkdownToken: any = undefined as any;
