// @generated by drool.exe extraction
// Generated from src/contexts/enums; source module was missing in Bun sourcemap recovery.
export enum KeypressLayer {
  AgentControl, // value unresolved
  Input = "input", // medium-cluster; compactCamel; bundle hits=74
  Navigation = "navigation", // high-inferred; compactCamel; bundle hits=11
  Observer, // value unresolved
  Overlay = "overlay", // medium-cluster; compactCamel; bundle hits=7
  System = "system", // medium-cluster; compactCamel; bundle hits=62
}

