// @generated by drool.exe extraction
// Stub generated because src/contexts/types was imported by recovered sources but absent from sourcemap recovery.
export type KeyEvent = any;
export type KeypressContextValue = any;
export type KeypressHandler = any;
export type KeypressHandlerResult = any;
export type ReadlineKey = any;
