// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/jira/types was imported by recovered sources but absent from sourcemap recovery.
export type JiraConfig = any;
export type JiraProject = any;
export type JiraProjectMap = any;
export type JiraSite = any;
export type JiraSitesMap = any;
