// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/capabilities/settings/types was imported by recovered sources but absent from sourcemap recovery.
export type SettingsCapabilityDeps = any;
