// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server/same-process/types was imported by recovered sources but absent from sourcemap recovery.
export type SameProcessTransportOptions = any;
