// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/envelope-helpers was imported by recovered sources but absent from sourcemap recovery.
export const createInternalErrorResponse: any = undefined as any;
export const createMethodNotFoundResponse: any = undefined as any;
export const parseEnvelope: any = undefined as any;
