// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/notification-forwarding was imported by recovered sources but absent from sourcemap recovery.
export const shouldForwardNotificationToFilteredListener: any = undefined as any;
