// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server-types was imported by recovered sources but absent from sourcemap recovery.
export type DaemonUser = any;
export type ServerTransport = any;
