// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/types was imported by recovered sources but absent from sourcemap recovery.
export const DaemonCoreConfig: any = undefined as any;
export const DaemonUserAuthEnv: any = undefined as any;
export const TerminalManagerConfig: any = undefined as any;
