// @generated by drool.exe extraction
// Stub generated because packages/common/src/feature-flags/types was imported by recovered sources but absent from sourcemap recovery.
export const DynamicConfigKey: any = undefined as any;
export const DynamicConfigTypes: any = undefined as any;
export const IndustryFeatureFlag: any = undefined as any;
