// @generated by drool.exe extraction
// Stub generated because packages/utils/src/security/types.ts was imported by recovered sources but absent from sourcemap recovery.
export type CSPSources = any;
