// @generated by drool.exe extraction
// Generated from src/utils/transcriptTurnNavigation/enums; source module was missing in Bun sourcemap recovery.
export enum TranscriptAnchorMode {
  Any = "any", // medium-cluster; compactCamel; bundle hits=60
  UserOnly = "userOnly", // high-inferred; compactCamel; bundle hits=4
}

