// @generated by drool.exe extraction
// Stub generated because src/utils/transcriptTurnNavigation/types was imported by recovered sources but absent from sourcemap recovery.
export type TranscriptAnchor = any;
export type TranscriptItem = any;
