import {
  DaemonAuthenticateResultSchema,
  DaemonAuthenticateRequestSchema,
  DaemonLogoutRequestSchema,
  DaemonLogoutResultSchema,
  DaemonLogoutResponseSchema,
  DaemonConnectionStatusNotificationSchema,
} from './schemas/connection';
import {
  ConnectionState,
  DaemonConnectionMethod,
  DaemonConnectionEvent,
  DaemonCronEvent,
  DaemonDroolEvent,
  DaemonDroolMethod,
  DaemonGetGitDiffUnavailableReason,
  DaemonManagementMethod,
  DaemonRelayEvent,
  DaemonRelayMethod,
  DaemonSettingsMethod,
  DaemonTerminalEvent,
  DaemonTerminalMethod,
  CreateTerminalError,
  SessionLoadState,
} from './schemas/enums';
import {
  CreateTerminalResultSchema,
  WriteDataResultSchema,
  ResizeResultSchema,
  CloseTerminalResultSchema,
  ListTerminalsResultSchema,
  DaemonCreateTerminalRequestParamsSchema,
  DaemonWriteDataRequestParamsSchema,
  DaemonResizeRequestParamsSchema,
  DaemonCloseTerminalRequestParamsSchema,
  DaemonListTerminalsRequestParamsSchema,
  DaemonCreateTerminalRequestSchema,
  DaemonWriteDataRequestSchema,
  DaemonResizeRequestSchema,
  DaemonCloseTerminalRequestSchema,
  DaemonListTerminalsRequestSchema,
} from './schemas/terminal';

export {
  ConnectionState,
  DaemonConnectionMethod,
  DaemonConnectionEvent,
  DaemonDroolEvent,
  DaemonCronEvent,
  DaemonTerminalEvent,
  DaemonTerminalMethod,
  DaemonDroolMethod,
  DaemonGetGitDiffUnavailableReason,
  DaemonManagementMethod,
  DaemonRelayEvent,
  DaemonRelayMethod,
  DaemonSettingsMethod,
  CreateTerminalError,
  SessionLoadState,
};
export {
  DaemonAuthenticateResultSchema,
  DaemonAuthenticateRequestSchema,
  DaemonLogoutRequestSchema,
  DaemonLogoutResultSchema,
  DaemonLogoutResponseSchema,
  DaemonConnectionStatusNotificationSchema,
};
export {
  CronRecordSchema,
  CronStatusSchema,
  CronKindSchema,
  CronScopeSchema,
  CronCreateScopeSchema,
  CronPayloadSchema,
  DaemonListCronsRequestSchema,
  DaemonListCronsResultSchema,
  DaemonCreateCronRequestSchema,
  DaemonCreateCronResultSchema,
  DaemonUpdateCronRequestSchema,
  DaemonUpdateCronResultSchema,
  DaemonDeleteCronRequestSchema,
  DaemonDeleteCronResultSchema,
  DaemonHoldSessionCronsRequestSchema,
  DaemonHoldSessionCronsResultSchema,
  DaemonResumeSessionCronsRequestSchema,
  DaemonResumeSessionCronsResultSchema,
  DaemonCronStateChangedNotificationSchema,
} from './schemas/crons';
export {
  DaemonListFilesResultSchema,
  DaemonListFilesRequestSchema,
  DaemonSearchFilesResultSchema,
  DaemonSearchFilesRequestSchema,
  DaemonSearchSessionsResultSchema,
  DaemonSearchSessionsRequestSchema,
  DaemonLoadSessionSpawnOptionsSchema,
  DaemonInitializeSessionResultSchema,
  DaemonLoadSessionResultSchema,
  DaemonAddUserMessageResultSchema,
  DaemonResolveQueuedUserMessageResultSchema,
  DaemonInterruptSessionResultSchema,
  DaemonCloseSessionResultSchema,
  DaemonCloseSessionRequestSchema,
  DaemonKillWorkerSessionResultSchema,
  DaemonKillWorkerSessionRequestSchema,
  DaemonListOpenedSessionsResultSchema,
  DaemonListAvailableSessionsResultSchema,
  DaemonGetSessionMessagesResultSchema,
  DaemonUpdateSessionSettingsResultSchema,
  DaemonValidateWorkingDirectoryResultSchema,
  DaemonInitializeSessionRequestSchema,
  DaemonLoadSessionRequestSchema,
  DaemonAddUserMessageRequestSchema,
  DaemonResolveQueuedUserMessageRequestSchema,
  DaemonInterruptSessionRequestSchema,
  DaemonListOpenedSessionsRequestSchema,
  DaemonListAvailableSessionsRequestSchema,
  DaemonGetSessionMessagesRequestSchema,
  DaemonUpdateSessionSettingsRequestSchema,
  DaemonValidateWorkingDirectoryRequestSchema,
  DaemonCommandAckResultSchema,
  DaemonRequestPermissionResultSchema,
  DaemonRequestPermissionSchema,
  DaemonAskUserResultSchema,
  DaemonAskUserSchema,
  DaemonSessionNotificationParamsSchema,
  DaemonSessionNotificationSchema,
  DaemonSessionListFilterSchema,
  DaemonListAvailableSessionsFilterSchema,
  // Archive/Unarchive session schemas
  DaemonArchiveSessionResultSchema,
  DaemonArchiveSessionRequestSchema,
  DaemonUnarchiveSessionResultSchema,
  DaemonUnarchiveSessionRequestSchema,
  DaemonRenameSessionResultSchema,
  DaemonRenameSessionRequestSchema,
  // Git Diff schemas
  DaemonGetGitDiffDataSchema,
  DaemonGetGitDiffResultSchema,
  DaemonGetGitDiffSuccessResultSchema,
  DaemonGetGitDiffUnavailableResultSchema,
  DaemonGetGitDiffRequestSchema,
  // Inspect Mission Readiness schemas
  DaemonInspectMissionReadinessRequestParamsSchema,
  DaemonInspectMissionReadinessResultSchema,
  DaemonInspectMissionReadinessRequestSchema,
  DaemonInspectMissionReadinessResponseSchema,
  // Git Push schemas
  DaemonGitPushResultSchema,
  DaemonGitPushRequestSchema,
  // Git Commit schemas
  DaemonGitCommitResultSchema,
  DaemonGitCommitRequestSchema,
  // Create PR schemas
  DaemonCreatePRResultSchema,
  DaemonCreatePRRequestSchema,
  // Semantic Diff Cache schemas
  DaemonGetSemanticDiffCacheResultSchema,
  DaemonGetSemanticDiffCacheRequestSchema,
  DaemonSaveSemanticDiffCacheResultSchema,
  DaemonSaveSemanticDiffCacheRequestSchema,
  // Generate Semantic Diff schemas
  DaemonGenerateSemanticDiffResultSchema,
  DaemonGenerateSemanticDiffRequestSchema,
  // Proxy Token schemas
  DaemonGetProxyTokenResultSchema,
  DaemonGetProxyTokenRequestSchema,
  DaemonGetProxyTokenResponseSchema,
  // Workspace file content schemas
  DaemonGetWorkspaceFileContentResultSchema,
  DaemonGetWorkspaceFileContentRequestSchema,
  DaemonGetWorkspaceFileContentResponseSchema,
  // Rewind schemas
  DaemonGetRewindInfoResultSchema,
  DaemonGetRewindInfoRequestSchema,
  DaemonGetRewindInfoResponseSchema,
  DaemonExecuteRewindResultSchema,
  DaemonExecuteRewindRequestSchema,
  DaemonExecuteRewindResponseSchema,
  // Compact session schemas
  DaemonCompactSessionResultSchema,
  DaemonCompactSessionRequestSchema,
  DaemonCompactSessionResponseSchema,
  DaemonForkSessionResultSchema,
  DaemonForkSessionRequestSchema,
  DaemonForkSessionResponseSchema,
  DaemonWarmupCacheRequestSchema,
  DaemonWarmupCacheResponseSchema,
  // Get context breakdown schemas
  DaemonGetContextBreakdownRequestSchema,
  DaemonGetContextBreakdownResultSchema,
  DaemonGetContextBreakdownResponseSchema,
  DaemonRequestSchema,
} from './schemas/drool';

export { SessionSearchDocKind } from './schemas/enums';

// Relay schemas
export {
  DaemonRelayStartRequestSchema,
  DaemonRelayStartResultSchema,
  DaemonRelayStopRequestSchema,
  DaemonRelayStopResultSchema,
  DaemonRelayGetStatusRequestSchema,
  DaemonRelayGetStatusResultSchema,
  DaemonRelayStatusChangedNotificationSchema,
} from './schemas/relay';

export {
  DaemonCustomModelSummarySchema,
  DaemonDeleteCustomModelRequestSchema,
  DaemonDeleteCustomModelResultSchema,
  DaemonGetDefaultSettingsRequestSchema,
  DaemonGetDefaultSettingsResultSchema,
  DaemonListCustomModelsRequestSchema,
  DaemonListCustomModelsResultSchema,
  DaemonSessionDefaultsManagementMapSchema,
  DaemonUpdateSessionDefaultsRequestSchema,
  DaemonUpdateSessionDefaultsResultSchema,
  DaemonUpsertCustomModelRequestSchema,
  DaemonUpsertCustomModelResultSchema,
} from './schemas/settings';

export {
  DaemonGetMcpConfigRequestSchema,
  DaemonGetMcpConfigResultSchema,
  DaemonUpdateMcpConfigRequestSchema,
  DaemonUpdateMcpConfigResultSchema,
  DaemonToggleMcpServerRequestSchema,
  DaemonAuthenticateMcpServerRequestSchema,
  DaemonCancelMcpAuthRequestSchema,
  DaemonClearMcpAuthRequestSchema,
  DaemonAddMcpServerRequestSchema,
  DaemonRemoveMcpServerRequestSchema,
  DaemonListMcpRegistryRequestSchema,
  DaemonListMcpRegistryResultSchema,
  DaemonListMcpToolsRequestSchema,
  DaemonListMcpToolsResultSchema,
  DaemonListMcpServersRequestSchema,
  DaemonListMcpServersResultSchema,
  DaemonToggleMcpToolRequestSchema,
  DaemonSubmitMcpAuthCodeRequestSchema,
  DaemonSubmitMcpAuthErrorRequestSchema,
  McpSuccessResultSchema,
} from './schemas/mcp';

// Skills schemas
export {
  DaemonListSkillsRequestSchema,
  DaemonListSkillsResultSchema,
} from './schemas/skills';

export {
  DaemonListCommandsRequestSchema,
  DaemonListCommandsResultSchema,
} from './schemas/commands';

// Plugin schemas
export {
  DaemonListAvailablePluginsRequestSchema,
  DaemonListAvailablePluginsResultSchema,
  DaemonListInstalledPluginsRequestSchema,
  DaemonListInstalledPluginsResultSchema,
  DaemonInstallPluginRequestSchema,
  DaemonInstallPluginResultSchema,
  DaemonUninstallPluginRequestSchema,
  DaemonUninstallPluginResultSchema,
  DaemonSetPluginEnabledRequestSchema,
  DaemonSetPluginEnabledResultSchema,
  DaemonUpdatePluginRequestSchema,
  DaemonUpdatePluginResultSchema,
  DaemonListMarketplacesRequestSchema,
  DaemonListMarketplacesResultSchema,
  DaemonAddMarketplaceRequestSchema,
  DaemonAddMarketplaceResultSchema,
  DaemonRemoveMarketplaceRequestSchema,
  DaemonRemoveMarketplaceResultSchema,
  DaemonUpdateMarketplaceRequestSchema,
  DaemonUpdateMarketplaceResultSchema,
} from './schemas/plugins';

// Management schemas
export {
  DaemonTriggerUpdateRequestSchema,
  DaemonTriggerUpdateResultSchema,
  DaemonInstallSshKeyRequestSchema,
  DaemonInstallSshKeyResultSchema,
} from './schemas/management';

// Bug report schemas
export {
  DaemonSubmitBugReportRequestSchema,
  DaemonSubmitBugReportResultSchema,
} from './schemas/bug-report';

// Automations schemas
export {
  DaemonListAutomationsRequestSchema,
  DaemonListAutomationsResultSchema,
  DaemonRunAutomationRequestSchema,
  DaemonRunAutomationResultSchema,
  DaemonPauseAutomationRequestSchema,
  DaemonPauseAutomationResultSchema,
  DaemonResumeAutomationRequestSchema,
  DaemonResumeAutomationResultSchema,
  DaemonGetAutomationHistoryRequestSchema,
  DaemonGetAutomationHistoryResultSchema,
  DaemonGetAutomationVisualRequestSchema,
  DaemonGetAutomationVisualResultSchema,
  DaemonCreateAutomationRequestSchema,
  DaemonCreateAutomationResultSchema,
  DaemonUpdateAutomationModelRequestSchema,
  DaemonUpdateAutomationModelResultSchema,
  DaemonUpdateAutomationPrivacyRequestSchema,
  DaemonUpdateAutomationPrivacyResultSchema,
  DaemonUpdateAutomationPromptRequestSchema,
  DaemonUpdateAutomationPromptResultSchema,
  DaemonUpdateAutomationScheduleRequestSchema,
  DaemonUpdateAutomationScheduleResultSchema,
  DaemonRenameAutomationRequestSchema,
  DaemonRenameAutomationResultSchema,
  DaemonDeleteAutomationRequestSchema,
  DaemonDeleteAutomationResultSchema,
  DaemonForkAutomationRequestSchema,
  DaemonForkAutomationResultSchema,
  DaemonApplyAutomationConfigRequestSchema,
  DaemonApplyAutomationConfigResultSchema,
} from './schemas/automations';

export { DaemonSpecificNotificationType } from './schemas/enums';

// Re-export terminal schemas
export {
  CreateTerminalResultSchema,
  WriteDataResultSchema,
  ResizeResultSchema,
  CloseTerminalResultSchema,
  ListTerminalsResultSchema,
  // Daemon terminal schemas
  DaemonCreateTerminalRequestParamsSchema,
  DaemonWriteDataRequestParamsSchema,
  DaemonResizeRequestParamsSchema,
  DaemonCloseTerminalRequestParamsSchema,
  DaemonListTerminalsRequestParamsSchema,
  DaemonCreateTerminalRequestSchema,
  DaemonWriteDataRequestSchema,
  DaemonResizeRequestSchema,
  DaemonCloseTerminalRequestSchema,
  DaemonListTerminalsRequestSchema,
};

// Drool types
export {
  DAEMON_HEARTBEAT_INTERVAL_MS,
  LOCAL_MACHINE_ID,
  WS_SERVER_CONFIG,
  DEFAULT_LOCAL_DAEMON_WS_URL,
} from './constants';

export {
  DesktopDaemonDisconnectReason,
  DesktopDaemonTransportMode,
  MachineType,
} from './enums';

export type {
  DesktopDaemonDisconnectEvent,
  DaemonConnectionMetadata,
  DaemonAuthenticateRequestParams,
  DaemonAuthenticateResult,
  DaemonAuthenticateRequest,
  DaemonAuthenticateResponse,
  DaemonLogoutRequestParams,
  DaemonLogoutRequest,
  DaemonLogoutResult,
  DaemonLogoutResponse,
  DaemonConnectionStatusNotificationParams,
  DaemonConnectionStatusNotification,
  DaemonRelayStatusChangedNotificationParams,
  DaemonRelayStatusChangedNotification,
  DaemonInitializeSessionRequestParams,
  DaemonLoadSessionRequestParams,
  DaemonLoadSessionSpawnOptions,
  DaemonAddUserMessageRequestParams,
  DaemonResolveQueuedUserMessageRequestParams,
  DaemonInterruptSessionRequestParams,
  DaemonCloseSessionRequestParams,
  DaemonListOpenedSessionsRequestParams,
  DaemonSessionListFilter,
  DaemonListAvailableSessionsFilter,
  DaemonListAvailableSessionsRequestParams,
  DaemonGetSessionMessagesRequestParams,
  DaemonUpdateSessionSettingsRequestParams,
  DaemonGetDefaultSettingsRequestParams,
  DaemonUpdateSessionDefaultsRequestParams,
  DaemonCustomModelSummary,
  DaemonListCustomModelsRequestParams,
  DaemonListCustomModelsRequest,
  DaemonListCustomModelsResult,
  DaemonListCustomModelsResponse,
  DaemonUpsertCustomModelRequestParams,
  DaemonUpsertCustomModelRequest,
  DaemonUpsertCustomModelResult,
  DaemonUpsertCustomModelResponse,
  DaemonDeleteCustomModelRequestParams,
  DaemonDeleteCustomModelRequest,
  DaemonDeleteCustomModelResult,
  DaemonDeleteCustomModelResponse,
  DaemonGetUserInfoRequestParams,
  DaemonValidateWorkingDirectoryRequestParams,
  DaemonInitializeSessionResult,
  DaemonLoadSessionResult,
  DaemonAddUserMessageResult,
  DaemonResolveQueuedUserMessageResult,
  DaemonInterruptSessionResult,
  DaemonCloseSessionResult,
  DaemonKillWorkerSessionResult,
  DaemonKillWorkerSessionRequest,
  DaemonKillWorkerSessionRequestParams,
  DaemonOpenedSessionInfo,
  DaemonAvailableSessionInfo,
  DaemonListOpenedSessionsResult,
  DaemonListAvailableSessionsResult,
  DaemonGetSessionMessagesResult,
  DaemonUpdateSessionSettingsResult,
  DaemonGetDefaultSettingsResult,
  DaemonUpdateSessionDefaultsResult,
  DaemonGetUserInfoResult,
  DaemonValidateWorkingDirectoryResult,
  DaemonCommandAckResult,
  DaemonInitializeSessionRequest,
  DaemonLoadSessionRequest,
  DaemonAddUserMessageRequest,
  DaemonResolveQueuedUserMessageRequest,
  DaemonInterruptSessionRequest,
  DaemonCloseSessionRequest,
  DaemonListOpenedSessionsRequest,
  DaemonListAvailableSessionsRequest,
  DaemonGetSessionMessagesRequest,
  DaemonUpdateSessionSettingsRequest,
  DaemonGetDefaultSettingsRequest,
  DaemonSessionDefaultsManagementMap,
  DaemonUpdateSessionDefaultsRequest,
  DaemonTriggerUpdateResult,
  DaemonTriggerUpdateRequest,
  DaemonTriggerUpdateResponse,
  // Relay types
  DaemonRelayStartResult,
  DaemonRelayStartRequest,
  DaemonRelayStartResponse,
  DaemonRelayStopResult,
  DaemonRelayStopRequest,
  DaemonRelayStopResponse,
  DaemonRelayGetStatusResult,
  DaemonRelayGetStatusRequest,
  DaemonRelayGetStatusResponse,
  CronRecord,
  CronStatus,
  CronKind,
  CronScope,
  CronCreateScope,
  CronPayload,
  DaemonListCronsRequestParams,
  DaemonListCronsRequest,
  DaemonListCronsResult,
  DaemonCreateCronRequestParams,
  DaemonCreateCronRequest,
  DaemonCreateCronResult,
  DaemonUpdateCronRequestParams,
  DaemonUpdateCronRequest,
  DaemonUpdateCronResult,
  DaemonDeleteCronRequestParams,
  DaemonDeleteCronRequest,
  DaemonDeleteCronResult,
  DaemonHoldSessionCronsRequestParams,
  DaemonHoldSessionCronsRequest,
  DaemonHoldSessionCronsResult,
  DaemonResumeSessionCronsRequestParams,
  DaemonResumeSessionCronsRequest,
  DaemonResumeSessionCronsResult,
  DaemonCronStateChangedNotificationParams,
  DaemonCronStateChangedNotification,
  DaemonValidateWorkingDirectoryRequest,
  DaemonRequest,
  DaemonInitializeSessionResponse,
  DaemonLoadSessionResponse,
  DaemonAddUserMessageResponse,
  DaemonResolveQueuedUserMessageResponse,
  DaemonInterruptSessionResponse,
  DaemonCloseSessionResponse,
  DaemonListOpenedSessionsResponse,
  DaemonListAvailableSessionsResponse,
  DaemonGetSessionMessagesResponse,
  DaemonUpdateSessionSettingsResponse,
  DaemonGetDefaultSettingsResponse,
  DaemonUpdateSessionDefaultsResponse,
  DaemonValidateWorkingDirectoryResponse,
  // Permission types
  DaemonRequestPermissionParams,
  DaemonRequestPermissionResult,
  // AskUser types
  DaemonAskUserParams,
  DaemonAskUserResult,
  // Session notification types
  DaemonSessionNotificationParams,
  DaemonSessionNotification,
  SessionInactivityNotification,
  // Permission request types
  DaemonRequestPermission,
  // AskUser request types
  DaemonAskUser,
  // Broadcast message union
  DaemonBroadcastMessage,
  // File listing types
  DaemonListFilesRequestParams,
  DaemonListFilesResult,
  DaemonListFilesRequest,
  DaemonListFilesResponse,
  // File search types
  DaemonSearchFilesRequestParams,
  DaemonSearchFilesResult,
  DaemonSearchFilesRequest,
  DaemonSearchFilesResponse,
  // Session search types
  DaemonSearchSessionsRequestParams,
  DaemonSearchSessionsHit,
  DaemonSearchSessionsSessionResult,
  DaemonSearchSessionsResult,
  DaemonSearchSessionsRequest,
  DaemonSearchSessionsResponse,
  // Terminal types
  CreateTerminalRequestParams,
  WriteDataRequestParams,
  ResizeRequestParams,
  CloseTerminalRequestParams,
  ListTerminalsRequestParams,
  CreateTerminalResult,
  WriteDataResult,
  ResizeResult,
  CloseTerminalResult,
  TerminalInfo,
  ListTerminalsResult,
  CreateTerminalRequest,
  WriteDataRequest,
  ResizeRequest,
  CloseTerminalRequest,
  ListTerminalsRequest,
  TerminalRequest,
  CreateTerminalResponse,
  WriteDataResponse,
  ResizeResponse,
  CloseTerminalResponse,
  ListTerminalsResponse,
  // Terminal notification types
  TerminalDataNotification,
  TerminalExitNotification,
  TerminalNotification,
  // Daemon terminal types
  DaemonCreateTerminalRequestParams,
  DaemonWriteDataRequestParams,
  DaemonResizeRequestParams,
  DaemonCloseTerminalRequestParams,
  DaemonListTerminalsRequestParams,
  DaemonCreateTerminalRequest,
  DaemonWriteDataRequest,
  DaemonResizeRequest,
  DaemonCloseTerminalRequest,
  DaemonListTerminalsRequest,
  // MCP types
  DaemonGetMcpConfigRequest,
  DaemonGetMcpConfigResult,
  DaemonUpdateMcpConfigRequestParams,
  DaemonUpdateMcpConfigRequest,
  DaemonUpdateMcpConfigResult,
  DaemonToggleMcpServerRequest,
  DaemonAuthenticateMcpServerRequest,
  DaemonCancelMcpAuthRequest,
  DaemonClearMcpAuthRequest,
  DaemonAddMcpServerRequest,
  DaemonRemoveMcpServerRequest,
  DaemonListMcpRegistryRequest,
  DaemonListMcpRegistryResult,
  DaemonMcpRegistryServer,
  DaemonListMcpToolsRequest,
  DaemonListMcpToolsResult,
  DaemonListMcpServersRequest,
  DaemonListMcpServersResult,
  DaemonMcpToolInfo,
  DaemonToggleMcpToolRequest,
  DaemonSubmitMcpAuthCodeRequest,
  DaemonSubmitMcpAuthErrorRequest,
  McpSuccessResult,
  McpServerConfig,
  McpServerInfo,
  // Archive/Unarchive session types
  DaemonArchiveSessionRequestParams,
  DaemonArchiveSessionResult,
  DaemonArchiveSessionRequest,
  DaemonArchiveSessionResponse,
  DaemonUnarchiveSessionRequestParams,
  DaemonUnarchiveSessionResult,
  DaemonUnarchiveSessionRequest,
  DaemonUnarchiveSessionResponse,
  DaemonRenameSessionRequestParams,
  DaemonRenameSessionResult,
  DaemonRenameSessionRequest,
  DaemonRenameSessionResponse,
  // Skills types
  DaemonListSkillsRequestParams,
  DaemonListSkillsRequest,
  DaemonListSkillsResult,
  // Custom command types
  DaemonListCommandsRequestParams,
  DaemonListCommandsRequest,
  DaemonListCommandsResult,
  // Plugin types
  DaemonListAvailablePluginsRequestParams,
  DaemonListAvailablePluginsRequest,
  DaemonListAvailablePluginsResult,
  DaemonListInstalledPluginsRequestParams,
  DaemonListInstalledPluginsRequest,
  DaemonListInstalledPluginsResult,
  DaemonInstallPluginRequestParams,
  DaemonInstallPluginRequest,
  DaemonInstallPluginResult,
  DaemonUninstallPluginRequestParams,
  DaemonUninstallPluginRequest,
  DaemonUninstallPluginResult,
  DaemonSetPluginEnabledRequestParams,
  DaemonSetPluginEnabledRequest,
  DaemonSetPluginEnabledResult,
  DaemonUpdatePluginRequestParams,
  DaemonUpdatePluginRequest,
  DaemonUpdatePluginResult,
  DaemonListMarketplacesRequestParams,
  DaemonListMarketplacesRequest,
  DaemonListMarketplacesResult,
  DaemonAddMarketplaceRequestParams,
  DaemonAddMarketplaceRequest,
  DaemonAddMarketplaceResult,
  DaemonRemoveMarketplaceRequestParams,
  DaemonRemoveMarketplaceRequest,
  DaemonRemoveMarketplaceResult,
  DaemonUpdateMarketplaceRequestParams,
  DaemonUpdateMarketplaceRequest,
  DaemonUpdateMarketplaceResult,
  // Bug report types
  DaemonSubmitBugReportRequestParams,
  DaemonSubmitBugReportRequest,
  DaemonSubmitBugReportResult,
  // Automations types
  AutomationEntry,
  DaemonListAutomationsRequestParams,
  DaemonListAutomationsRequest,
  DaemonListAutomationsResult,
  DaemonRunAutomationRequestParams,
  DaemonRunAutomationRequest,
  DaemonRunAutomationResult,
  DaemonPauseAutomationRequest,
  DaemonPauseAutomationRequestParams,
  DaemonPauseAutomationResult,
  DaemonResumeAutomationRequest,
  DaemonResumeAutomationRequestParams,
  DaemonResumeAutomationResult,
  DaemonGetAutomationHistoryRequest,
  DaemonGetAutomationHistoryRequestParams,
  DaemonGetAutomationHistoryResult,
  DaemonGetAutomationVisualRequest,
  DaemonGetAutomationVisualRequestParams,
  DaemonGetAutomationVisualResult,
  DaemonCreateAutomationRequest,
  DaemonCreateAutomationRequestParams,
  DaemonCreateAutomationResult,
  DaemonUpdateAutomationModelRequest,
  DaemonUpdateAutomationModelRequestParams,
  DaemonUpdateAutomationModelResult,
  DaemonUpdateAutomationPrivacyRequest,
  DaemonUpdateAutomationPrivacyRequestParams,
  DaemonUpdateAutomationPrivacyResult,
  DaemonUpdateAutomationPromptRequest,
  DaemonUpdateAutomationPromptRequestParams,
  DaemonUpdateAutomationPromptResult,
  DaemonUpdateAutomationScheduleRequest,
  DaemonUpdateAutomationScheduleRequestParams,
  DaemonUpdateAutomationScheduleResult,
  DaemonRenameAutomationRequest,
  DaemonRenameAutomationRequestParams,
  DaemonRenameAutomationResult,
  DaemonDeleteAutomationRequest,
  DaemonDeleteAutomationRequestParams,
  DaemonDeleteAutomationResult,
  DaemonForkAutomationRequest,
  DaemonForkAutomationRequestParams,
  DaemonForkAutomationResult,
  DaemonApplyAutomationConfigRequest,
  DaemonApplyAutomationConfigResult,
  // Git Diff types
  DaemonGetGitDiffRequestParams,
  DaemonGetGitDiffData,
  DaemonGetGitDiffResult,
  DaemonGetGitDiffSuccessResult,
  DaemonGetGitDiffUnavailableResult,
  DaemonGetGitDiffFile,
  DaemonGetGitDiffCommit,
  // Inspect Mission Readiness types
  DaemonInspectMissionReadinessRequestParams,
  DaemonInspectMissionReadinessResult,
  DaemonInspectMissionReadinessRequest,
  DaemonInspectMissionReadinessResponse,
  DaemonGetGitDiffRequest,
  DaemonGetGitDiffResponse,
  // Git Push types
  DaemonGitPushRequestParams,
  DaemonGitPushResult,
  DaemonGitPushRequest,
  DaemonGitPushResponse,
  // Git Commit types
  DaemonGitCommitRequestParams,
  DaemonGitCommitResult,
  DaemonGitCommitRequest,
  DaemonGitCommitResponse,
  // Create PR types
  DaemonCreatePRRequestParams,
  DaemonCreatePRResult,
  DaemonCreatePRRequest,
  DaemonCreatePRResponse,
  // Semantic Diff Cache types
  DaemonGetSemanticDiffCacheRequestParams,
  DaemonGetSemanticDiffCacheResult,
  DaemonGetSemanticDiffCacheRequest,
  DaemonGetSemanticDiffCacheResponse,
  DaemonSaveSemanticDiffCacheRequestParams,
  DaemonSaveSemanticDiffCacheResult,
  DaemonSaveSemanticDiffCacheRequest,
  DaemonSaveSemanticDiffCacheResponse,
  // Generate Semantic Diff types
  DaemonGenerateSemanticDiffRequestParams,
  DaemonGenerateSemanticDiffResult,
  DaemonGenerateSemanticDiffRequest,
  DaemonGenerateSemanticDiffResponse,
  // Proxy Token types
  DaemonGetProxyTokenResult,
  DaemonGetProxyTokenRequest,
  DaemonGetProxyTokenResponse,
  // Workspace file content types
  DaemonGetWorkspaceFileContentRequestParams,
  DaemonGetWorkspaceFileContentResult,
  DaemonGetWorkspaceFileContentRequest,
  DaemonGetWorkspaceFileContentResponse,
  DaemonGetRewindInfoRequest,
  DaemonGetRewindInfoResult,
  DaemonGetRewindInfoResponse,
  DaemonExecuteRewindRequest,
  DaemonExecuteRewindResult,
  DaemonExecuteRewindResponse,
  DaemonCompactSessionRequestParams,
  DaemonCompactSessionResult,
  DaemonCompactSessionRequest,
  DaemonCompactSessionResponse,
  DaemonForkSessionRequestParams,
  DaemonForkSessionResult,
  DaemonForkSessionRequest,
  DaemonForkSessionResponse,
  DaemonWarmupCacheRequestParams,
  DaemonWarmupCacheRequest,
  DaemonWarmupCacheResponse,
  // Get context breakdown types
  DaemonGetContextBreakdownRequestParams,
  DaemonGetContextBreakdownRequest,
  DaemonGetContextBreakdownResult,
  DaemonGetContextBreakdownResponse,
} from './types';
