// @generated by drool.exe extraction
// Stub generated because src/acp/session/types was imported by recovered sources but absent from sourcemap recovery.
export type ConfigOption = any;
export type ConfigOptionsModelEntry = any;
export type ConfigOptionsState = any;
