// @generated by drool.exe extraction
// Generated from packages/common/src/updater/enums; source module was missing in Bun sourcemap recovery.
export enum UpdateArch {
  Arm64 = "arm64", // medium-cluster; compactCamel; bundle hits=18
  X64 = "x64", // medium-cluster; compactCamel; bundle hits=26
  X64Baseline, // value unresolved
}

export enum UpdatePlatform {
  Darwin = "darwin", // medium-cluster; compactCamel; bundle hits=45
  Linux = "linux", // medium-cluster; compactCamel; bundle hits=50
  Windows = "windows", // medium-cluster; compactCamel; bundle hits=25
}

