// @generated by drool.exe extraction
// Generated from src/commands/mcp/views/enums; source module was missing in Bun sourcemap recovery.
export enum AuthStatus {
  Authenticated = "authenticated", // high-inferred; compactCamel; bundle hits=21
  AuthenticatedWithoutOrg, // value unresolved
  Checking = "checking", // high-inferred; compactCamel; bundle hits=33
  InvalidApiKey = "invalid-api-key", // high-inferred; lower-kebab; bundle hits=7
  NeedsAuth = "needsAuth", // high-inferred; compactCamel; bundle hits=19
  NotApplicable = "not_applicable", // high-inferred; lower_snake; bundle hits=3
}

export enum ServerAction {
  Authenticate = "authenticate", // high-inferred; compactCamel; bundle hits=26
  ClearAuth = "clearAuth", // high-inferred; compactCamel; bundle hits=15
  Disable = "disable", // medium-cluster; compactCamel; bundle hits=23
  Enable = "enable", // medium-cluster; compactCamel; bundle hits=21
  Reauthenticate = "reauthenticate", // high-inferred; compactCamel; bundle hits=16
  Remove = "remove", // medium-cluster; compactCamel; bundle hits=43
  Retry = "retry", // medium-cluster; compactCamel; bundle hits=35
  ViewTools = "viewTools", // high-inferred; compactCamel; bundle hits=8
}

export enum ToolAction {
  Back = "back", // medium-cluster; compactCamel; bundle hits=55
  Disable = "disable", // medium-cluster; compactCamel; bundle hits=23
  Enable = "enable", // medium-cluster; compactCamel; bundle hits=21
}

export enum ViewType {
  AddServer = "addServer", // high-inferred; compactCamel; bundle hits=10
  RegistryDetail = "registryDetail", // high-inferred; compactCamel; bundle hits=5
  RegistryList = "registryList", // high-inferred; compactCamel; bundle hits=5
  ServerDetail = "serverDetail", // high-inferred; compactCamel; bundle hits=5
  ServerList = "serverList", // high-inferred; compactCamel; bundle hits=5
  ToolDetail = "toolDetail", // high-inferred; compactCamel; bundle hits=5
  ToolsList = "toolsList", // high-inferred; compactCamel; bundle hits=6
  ToolsOverview = "toolsOverview", // high-inferred; compactCamel; bundle hits=5
}

