// @generated by drool.exe extraction
// Stub generated because src/commands/mcp/views/types was imported by recovered sources but absent from sourcemap recovery.
export type McpMenuListItem = any;
export type McpMenuListProps = any;
export type ServerActionItem = any;
export type ServerToolsGroup = any;
export type ServerWithStatus = any;
export type ToolActionItem = any;
export type ToolInfo = any;
export type ViewStackItem = any;
