// @generated by drool.exe extraction
// Stub generated because packages/updater/src/types was imported by recovered sources but absent from sourcemap recovery.
export type PendingUpdateMarker = any;
export type RemoteConfig = any;
export type UpdateInfo = any;
export type UpdaterConfig = any;
export type UpdaterState = any;
