// @generated by drool.exe extraction
// Stub generated because packages/utils/src/text/types was imported by recovered sources but absent from sourcemap recovery.
export type DiffLine = any;
export type DiffLineSegment = any;
export type DiffLineStats = any;
