// @generated by drool.exe extraction
// Generated from packages/utils/src/relay/enums; source module was missing in Bun sourcemap recovery.
export enum RelayAuthRequirement {
  LegacyRelay = "legacy_relay", // high-inferred; lower_snake; bundle hits=2
  ProbeFailed = "probe_failed", // high-inferred; lower_snake; bundle hits=4
  RequiresAuth = "requiresAuth", // high-inferred; compactCamel; bundle hits=13
}

