// @generated by drool.exe extraction
// Generated from src/hooks/compaction/enums; source module was missing in Bun sourcemap recovery.
export enum CompactionSummaryKind {
  LlmSummary = "llm_summary", // high-inferred; lower_snake; bundle hits=15
  ProviderSwitchSerialization = "provider_switch_serialization", // high-inferred; lower_snake; bundle hits=6
}

