// @generated by drool.exe extraction
// Stub generated because src/hooks/compaction/types was imported by recovered sources but absent from sourcemap recovery.
export type CompactAnchoredAtLastMessageParams = any;
export type CompactParams = any;
export type CompactResult = any;
export type LastSummaryMeta = any;
export type SerializeOptions = any;
export type SummarizeFn = any;
