// @generated by drool.exe extraction
// Generated from src/telemetry/enums; source module was missing in Bun sourcemap recovery.
export enum SkillActivationSource {
  SlashCommand = "slash_command", // high-inferred; lower_snake; bundle hits=4
  Tool = "tool", // medium-cluster; compactCamel; bundle hits=63
}

