// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/capabilities/relay/types was imported by recovered sources but absent from sourcemap recovery.
export type RelayCapabilityDeps = any;
export type RelayCapabilityHostDeps = any;
