// @generated by drool.exe extraction
// Generated from src/utils/terminalAppearanceDetector/enums; source module was missing in Bun sourcemap recovery.
export enum TerminalAppearance {
  Dark = "dark", // medium-cluster; compactCamel; bundle hits=22
  Light = "light", // medium-cluster; compactCamel; bundle hits=52
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
}

