// @generated by drool.exe extraction
// Stub generated because src/utils/terminalAppearanceDetector/types was imported by recovered sources but absent from sourcemap recovery.
export type DetectOptions = any;
export type DetectorStdin = any;
export type DetectorStdout = any;
