// @generated by drool.exe extraction
// Stub generated because src/services/mcp/oauth/core/types was imported by recovered sources but absent from sourcemap recovery.
export type AuthenticateOAuthParams = any;
export type McpOAuthDriverMetadata = any;
export type McpOAuthDriverOptions = any;
