// @generated by drool.exe extraction
// Stub generated because src/services/snapshots/types was imported by recovered sources but absent from sourcemap recovery.
export type BoundaryQueueEntry = any;
export type BoundaryRestoreInfo = any;
export type ContentStoreMetadata = any;
export type ContentStoreStats = any;
export type EvictionResult = any;
export type FileCreation = any;
export type FileDeletion = any;
export type FileRestoreSelection = any;
export type FileSnapshot = any;
export type GlobalSnapshotIndex = any;
export type MessageBoundarySnapshot = any;
export type RestoreResult = any;
export type SessionSnapshotManifestData = any;
export type SnapshotSettings = any;
