// @generated by drool.exe extraction
// Stub generated because src/tools/executors/client/shell/types was imported by recovered sources but absent from sourcemap recovery.
export const InteractiveCommandMatch: any = undefined as any;
export const InteractiveWaitMatch: any = undefined as any;
export const SummarizeCLIOptions: any = undefined as any;
