// @generated by drool.exe extraction
// Stub generated because src/services/crons/types was imported by recovered sources but absent from sourcemap recovery.
export type CadenceChip = any;
export type CreateSessionCronParams = any;
export type CronRecipe = any;
export type CronStatusBadge = any;
export type EditCronParams = any;
export type LoopSchedule = any;
export type ParsedDuration = any;
