// @generated by drool.exe extraction
// Stub generated because packages/runtime/settings/src/types was imported by recovered sources but absent from sourcemap recovery.
export type AgentSettingsPathsResult = any;
export type McpOAuthReconnectionBannerOptions = any;
export type McpOAuthReconnectionBannerStatus = any;
export type McpSettingsProvider = any;
export type MergeHierarchyWithChainResult = any;
export type PathCompareOptions = any;
export type PluginMarketplaceSettingsProvider = any;
export type PluginSettingsLoadResult = any;
export type SettingsChangedEvent = any;
export type SettingsFolder = any;
export type SettingsFolderIndustry = any;
export type SettingsHierarchyLevel = any;
export type SettingsPathsResult = any;
export type SettingsUpdate = any;
export type SkillImportSettingsProvider = any;
