// @generated by drool.exe extraction
// Stub generated because src/agent/types was imported by recovered sources but absent from sourcemap recovery.
export const ApprovedSpecNewSessionPayload: any = undefined as any;
export const ExitSpecModeResult: any = undefined as any;
export const PermissionRequestFn: any = undefined as any;
export const PermissionResponse: any = undefined as any;
export const SpecHandoffPrompt: any = undefined as any;
export const ToolConfirmationBatch: any = undefined as any;
export const ToolExecutionContext: any = undefined as any;
