// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/terminal/types was imported by recovered sources but absent from sourcemap recovery.
export const CreateTerminalParams: any = undefined as any;
export const Terminal: any = undefined as any;
export const TerminalInfo: any = undefined as any;
export const TerminalSnapshot: any = undefined as any;
export const TimerHandle: any = undefined as any;
