// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/notion/types was imported by recovered sources but absent from sourcemap recovery.
export type NotionConfig = any;
