// @generated by drool.exe extraction
// Generated from packages/drool-core/src/core/enums; source module was missing in Bun sourcemap recovery.
export enum ChatFailureReason {
  ContentModerationError = "contentModerationError", // high-inferred; compactCamel; bundle hits=2
  EmptyResponse = "emptyResponse", // high-inferred; compactCamel; bundle hits=1
  InvalidRequest = "invalidRequest", // high-inferred; compactCamel; bundle hits=2
  InvalidResponseData = "invalidResponseData", // high-inferred; compactCamel; bundle hits=1
  LLMContextExceeded = "llmContextExceeded", // high-inferred; compactCamel; bundle hits=2
  LLMInternalError = "llmInternalError", // high-inferred; compactCamel; bundle hits=2
  NetworkError = "networkError", // high-inferred; compactCamel; bundle hits=22
  Overloaded = "overloaded", // high-inferred; compactCamel; bundle hits=8
  PaymentRequired = "paymentRequired", // high-inferred; compactCamel; bundle hits=1
  RetryExhausted = "retryExhausted", // high-inferred; compactCamel; bundle hits=1
  StreamError = "streamError", // high-inferred; compactCamel; bundle hits=2
  TextFieldsTooLarge = "textFieldsTooLarge", // high-inferred; compactCamel; bundle hits=1
  Throttling = "throttling", // high-inferred; compactCamel; bundle hits=2
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
}

export enum DroolRuntime {
  Local = "local", // medium-cluster; compactCamel; bundle hits=63
}

