// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/schema was imported by recovered sources but absent from sourcemap recovery.
export type IndustryLocalProcess = any;
export type FirestoreLocalProcess = any;
export type FirestoreLocalProcessWithId = any;
export type LocalProcess = any;
