// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/types was imported by recovered sources but absent from sourcemap recovery.
export type IndustryMissionArtifactMetadata = any;
export type FirestoreMissionArtifactMetadata = any;
export type FirestoreSession = any;
export type FirestoreSessionWithId = any;
export type SessionVersion = any;
export type SlackAskUserDelegationState = any;
