// @generated by drool.exe extraction
// Generated from src/mcp/clients/http/enums; source module was missing in Bun sourcemap recovery.
export enum McpRemoteTransport {
  Sse = "sse", // medium-cluster; compactCamel; bundle hits=35
  StreamableHttp = "streamable-http", // high-inferred; lower-kebab; bundle hits=2
}

