// @generated by drool.exe extraction
// Stub generated because src/mcp/clients/http/types was imported by recovered sources but absent from sourcemap recovery.
export type ConnectedHttpClient = any;
export type HttpClientTransport = any;
export type InitializeHttpClientArgs = any;
export type OnAuthFlowCompleted = any;
export type SseConnectionArgs = any;
export type StreamableHttpConnectionArgs = any;
