// @generated by drool.exe extraction
// Stub generated because src/tools/executors/client/connectors/types was imported by recovered sources but absent from sourcemap recovery.
export type ConnectorToolsReminder = any;
export type FetchConnectorToolsOptions = any;
