// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/agent-effectiveness-report/types was imported by recovered sources but absent from sourcemap recovery.
export type AgentEffectivenessCodingUsageRow = any;
export type AgentEffectivenessDailyUsageRows = any;
export type AgentEffectivenessHtmlReportRenderOptions = any;
export type AgentEffectivenessMetrics = any;
export type AgentEffectivenessOrganizationTotalUsage = any;
export type AgentEffectivenessPullRequest = any;
export type AgentEffectivenessTokenEfficiencyTrendPoint = any;
export type AgentEffectivenessUserReportRow = any;
export type AgentEffectivenessWorkItem = any;
export type ResolvedAgentEffectivenessReportRequest = any;
