// @generated by drool.exe extraction
// Stub generated because packages/runtime/host/src/types was imported by recovered sources but absent from sourcemap recovery.
export type HostIdentityAuthContext = any;
export type HostIdentityServiceOptions = any;
export type SaveComputerRegistrationParams = any;
