// @generated by drool.exe extraction
// Generated from packages/utils/src/mcp/enums; source module was missing in Bun sourcemap recovery.
export enum McpServerAuthUiState {
  Authenticated = "authenticated", // high-inferred; compactCamel; bundle hits=21
  NeedsAuth = "needsAuth", // high-inferred; compactCamel; bundle hits=19
  NotApplicable = "not_applicable", // high-inferred; lower_snake; bundle hits=3
}

