// @generated by drool.exe extraction
// Stub generated because packages/utils/src/mcp/types was imported by recovered sources but absent from sourcemap recovery.
export type GetMcpServerUiStateOptions = any;
export type McpAuthPendingState = any;
export type McpAuthPendingStatusSource = any;
export type McpOAuthCallbackDelivery = any;
export type McpOAuthCallbackDeliveryParts = any;
export type McpServerUiStateInfo = any;
export type McpServerUiStateSource = any;
export type ShouldHandleMcpAuthRequiredEventOptions = any;
