// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/slack/types was imported by recovered sources but absent from sourcemap recovery.
export type SlackChannel = any;
export type SlackChannelResponse = any;
export type SlackChannelSettings = any;
export type SlackChannelToggleRequest = any;
export type SlackConfig = any;
export type SlackConversationsListResponse = any;
