// @generated by drool.exe extraction
// Generated from packages/drool-core/src/tools/utils/enums; source module was missing in Bun sourcemap recovery.
export enum FileOperation {
  Create = "create", // medium-cluster; compactCamel; bundle hits=68
  Update = "update", // medium-cluster; compactCamel; bundle hits=64
}

