// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/tools/utils/types was imported by recovered sources but absent from sourcemap recovery.
export const ApplyPatchResult: any = undefined as any;
export const ApplyPatchTuiResult: any = undefined as any;
export const ChangeChunk: any = undefined as any;
export const FileAction: any = undefined as any;
export const FileCommit: any = undefined as any;
export const FileEditChange: any = undefined as any;
export const FileEditResult: any = undefined as any;
export const FileEditResultWithDiff: any = undefined as any;
export const ParsedPatch: any = undefined as any;
export const ToolkitStatus: any = undefined as any;
