// @generated by drool.exe extraction
// Generated from src/services/update/enums; source module was missing in Bun sourcemap recovery.
export enum UpdateDrainKind {
  None = "none", // medium-cluster; compactCamel; bundle hits=55
  Settled = "settled", // medium-cluster; compactCamel; bundle hits=2
  Timeout = "timeout", // medium-cluster; compactCamel; bundle hits=61
}

