// @generated by drool.exe extraction
// Generated from packages/daemon-client/src/session/enums; source module was missing in Bun sourcemap recovery.
export enum ConnectionEvent {
  StatusChanged, // value unresolved
}

export enum ConnectionFailureReason {
  AuthRejected = "auth_rejected", // high-inferred; lower_snake; bundle hits=8
  ComputeLimitExceeded = "compute_limit_exceeded", // high-inferred; lower_snake; bundle hits=3
  ComputerDisconnected = "computer_disconnected", // high-inferred; lower_snake; bundle hits=2
  ComputerOffline = "computer_offline", // high-inferred; lower_snake; bundle hits=2
  ConnectionLost = "connection_lost", // high-inferred; lower_snake; bundle hits=2
  DaemonTimeout = "daemon_timeout", // high-inferred; lower_snake; bundle hits=4
  DaemonUnreachable = "daemon_unreachable", // high-inferred; lower_snake; bundle hits=8
  IdentityMismatch = "identity_mismatch", // high-inferred; lower_snake; bundle hits=2
  NoToken = "noToken", // high-inferred; compactCamel; bundle hits=6
  ProtocolMismatch = "protocol_mismatch", // high-inferred; lower_snake; bundle hits=2
  RelayAuthRejected = "relay_auth_rejected", // high-inferred; lower_snake; bundle hits=4
  RelayTimeout = "relay_timeout", // high-inferred; lower_snake; bundle hits=3
  RelayUnauthorized = "relay_unauthorized", // high-inferred; lower_snake; bundle hits=3
  RelayUnreachable = "relay_unreachable", // high-inferred; lower_snake; bundle hits=3
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
}

export enum DroolEvent {
  AskUserRequested = "askUserRequested", // high-inferred; compactCamel; bundle hits=5
  AskUserResolved = "askUserResolved", // high-inferred; compactCamel; bundle hits=6
  CronStateChanged = "cronStateChanged", // high-inferred; compactCamel; bundle hits=4
  DroolWorkingStateChanged = "droolWorkingStateChanged", // high-inferred; compactCamel; bundle hits=9
  McpAuthCompleted = "mcpAuthCompleted", // high-inferred; compactCamel; bundle hits=2
  McpAuthRequired = "mcpAuthRequired", // high-inferred; compactCamel; bundle hits=1
  McpStatusChanged = "mcpStatusChanged", // high-inferred; compactCamel; bundle hits=4
  MessageAdded = "messageAdded", // high-inferred; compactCamel; bundle hits=1
  MessageCreated = "messageCreated", // high-inferred; compactCamel; bundle hits=3
  MessageQueued = "messageQueued", // high-inferred; compactCamel; bundle hits=1
  MissionFeaturesChanged = "missionFeaturesChanged", // high-inferred; compactCamel; bundle hits=1
  MissionProgressEntry = "missionProgressEntry", // high-inferred; compactCamel; bundle hits=1
  MissionStateChanged = "missionStateChanged", // high-inferred; compactCamel; bundle hits=1
  MissionWorkerCompleted = "missionWorkerCompleted", // high-inferred; compactCamel; bundle hits=1
  MissionWorkerStarted = "missionWorkerStarted", // high-inferred; compactCamel; bundle hits=3
  PermissionRequested = "permissionRequested", // high-inferred; compactCamel; bundle hits=6
  PermissionResolved = "permissionResolved", // high-inferred; compactCamel; bundle hits=5
  PermissionTimeout = "permissionTimeout", // high-inferred; compactCamel; bundle hits=2
  QueuedMessagesDiscarded = "queuedMessagesDiscarded", // high-inferred; compactCamel; bundle hits=1
  RelayStatusChanged = "relayStatusChanged", // high-inferred; compactCamel; bundle hits=3
  SelfResumeFailed = "selfResumeFailed", // high-inferred; compactCamel; bundle hits=1
  SessionInactive = "sessionInactive", // high-inferred; compactCamel; bundle hits=1
  SessionInitialized = "sessionInitialized", // high-inferred; compactCamel; bundle hits=1
  SessionInterrupted = "sessionInterrupted", // high-inferred; compactCamel; bundle hits=6
  SessionLoaded = "sessionLoaded", // high-inferred; compactCamel; bundle hits=1
  SessionNotFound = "sessionNotFound", // high-inferred; compactCamel; bundle hits=11
  SessionNotification = "sessionNotification", // high-inferred; compactCamel; bundle hits=4
  SessionSettingsUpdated = "sessionSettingsUpdated", // high-inferred; compactCamel; bundle hits=3
  SessionTitleUpdated = "sessionTitleUpdated", // high-inferred; compactCamel; bundle hits=2
  SessionTokenUsageChanged = "sessionTokenUsageChanged", // high-inferred; compactCamel; bundle hits=1
  SessionUnsubscribed = "sessionUnsubscribed", // high-inferred; compactCamel; bundle hits=1
  TerminalClosed = "terminalClosed", // high-inferred; compactCamel; bundle hits=1
  TerminalCreated = "terminalCreated", // high-inferred; compactCamel; bundle hits=1
  TerminalDataWritten = "terminalDataWritten", // high-inferred; compactCamel; bundle hits=1
  TerminalExit = "terminalExit", // high-inferred; compactCamel; bundle hits=1
  TerminalResized = "terminalResized", // high-inferred; compactCamel; bundle hits=1
  TerminalsListed = "terminalsListed", // high-inferred; compactCamel; bundle hits=1
  ToolProgressUpdate = "toolProgressUpdate", // high-inferred; compactCamel; bundle hits=1
  ToolResult = "toolResult", // high-inferred; compactCamel; bundle hits=20
  UnsupportedSessionNotification = "unsupportedSessionNotification", // high-inferred; compactCamel; bundle hits=3
}

export enum TransportState {
  Connected = "connected", // high-inferred; compactCamel; bundle hits=61
  Disconnected = "disconnected", // high-inferred; compactCamel; bundle hits=34
}

