// @generated by drool.exe extraction
// Generated from packages/utils/src/mission/enums; source module was missing in Bun sourcemap recovery.
export enum MissionArtifactReadOperation {
  MissionJson = "mission_json", // high-inferred; lower_snake; bundle hits=4
  MissionProgressLog = "mission_progress_log", // high-inferred; lower_snake; bundle hits=2
  MissionProgressLogEntry = "mission_progress_log_entry", // high-inferred; lower_snake; bundle hits=2
  MissionText = "mission_text", // high-inferred; lower_snake; bundle hits=2
}

