// @generated by drool.exe extraction
// Stub generated because packages/utils/src/mission/missionMetadataTimestamps was imported by recovered sources but absent from sourcemap recovery.
export const getMissionMetadataTimestampMs: any = undefined as any;
export const getMissionUpdatedAtMs: any = undefined as any;
export const isMissionMetadataNewer: any = undefined as any;
