// @generated by drool.exe extraction
// Stub generated because packages/utils/src/mission/types was imported by recovered sources but absent from sourcemap recovery.
export type DeriveMissionWorkerSessionReferencesParams = any;
export type FormatMissionLogAgeOptions = any;
export type MissionArtifactReadError = any;
export type MissionElapsedProgressEntry = any;
export type MissionElapsedSnapshot = any;
export type MissionMetadataTimestamp = any;
export type MissionMetadataTimestampLike = any;
export type MissionMetadataTimestampValue = any;
export type MissionWorkerFeature = any;
export type MissionWorkerSessionReference = any;
export type ReadMissionArtifactMetadataOptions = any;
