// @generated by drool.exe extraction
// Generated from packages/utils/src/agentReadiness/enums; source module was missing in Bun sourcemap recovery.
export enum CriterionStatus {
  Failed = "failed", // medium-cluster; compactCamel; bundle hits=73
  Passed = "passed", // medium-cluster; compactCamel; bundle hits=17
  Skipped = "skipped", // medium-cluster; compactCamel; bundle hits=48
}

