/**
 * Agent Readiness Report - Markdown Export
 *
 * Exports a readiness report to markdown format for sharing and documentation.
 */

import { CriterionStatus } from './enums';
import {
  computeCategoriesData,
  getCategoryDisplayName,
  getStatusLabel,
} from './exportShared';
import {
  calculateRepoScore,
  calculateRepoLevelFromScore,
  extractRepoNameOnly,
} from './utils';

import type { IndustryAgentReadinessReport } from '@industry/common/agentReadiness/types';

function formatDate(timestamp: number): string {
  return `${
    new Date(timestamp).toISOString().replace('T', ' ').split('.')[0]
  } UTC`;
}

function escapeMarkdownTableCell(text: string): string {
  if (!text) return '';
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ').replace(/\r/g, '');
}

function truncateRationale(rationale: string, maxLength = 200): string {
  if (!rationale) return '-';
  const escaped = escapeMarkdownTableCell(rationale);
  if (escaped.length <= maxLength) return escaped;
  return `${escaped.slice(0, maxLength - 3)}...`;
}

function getStatusLabelForMarkdown(status: CriterionStatus): string {
  const label = getStatusLabel(status);

  if (status === CriterionStatus.Passed) return `🟢 ${label}`;
  if (status === CriterionStatus.Failed) return `🔴 ${label}`;

  return label;
}

/**
 * Export a readiness report to markdown format
 */
export function exportReadinessReportToMarkdown(
  report: IndustryAgentReadinessReport
): string {
  const repoName = extractRepoNameOnly(report.repoUrl || '');
  const scorePercent = calculateRepoScore(report);
  const level = calculateRepoLevelFromScore(scorePercent);
  const categoriesData = computeCategoriesData(report);

  const allCriteria = categoriesData.flatMap((category) => category.criteria);

  const totalCriteria = allCriteria.length;
  const passed = allCriteria.filter(
    (criterion) => criterion.status === CriterionStatus.Passed
  ).length;
  const failed = allCriteria.filter(
    (criterion) => criterion.status === CriterionStatus.Failed
  ).length;
  const skipped = allCriteria.filter(
    (criterion) => criterion.status === CriterionStatus.Skipped
  ).length;

  const commitLine = report.commitHash
    ? `**Commit:** \`${report.commitHash.slice(0, 7)}\`  \n`
    : '';

  const branchLine = report.branch ? `**Branch:** ${report.branch}  \n` : '';

  const passRateRows = categoriesData
    .map(
      (category) =>
        `| ${getCategoryDisplayName(category.categoryId)} | ${category.percentage}% |`
    )
    .join('\n');

  const categorySections = categoriesData
    .map((category) => {
      const criteriaRows = category.criteria
        .map((criterion) => {
          const name = escapeMarkdownTableCell(criterion.name);
          const rationale = truncateRationale(criterion.rationale || '');

          return `| ${name} | ${criterion.score} | ${getStatusLabelForMarkdown(criterion.status)} | ${rationale} |`;
        })
        .join('\n');

      return `## ${getCategoryDisplayName(category.categoryId)}

| Criterion | Score | Status | Rationale |
|-----------|-------|--------|-----------|
${criteriaRows}
`;
    })
    .join('\n');

  return `# Agent Readiness Report: ${repoName}

**Level:** ${level}/5  
**Overall Score:** ${Math.round(scorePercent)}%  
**Generated:** ${formatDate(report.createdAt)}  
${commitLine}${branchLine}
## Summary

| Metric | Value |
|--------|-------|
| Total Criteria | ${totalCriteria} |
| Passed | ${passed} |
| Failed | ${failed} |
| Skipped | ${skipped} |

## Pass Rate by Category

| Category | Pass Rate |
|----------|-----------|
${passRateRows}

${categorySections}
---

*Generated by Industry Agent Readiness*`;
}
