import { CriterionStatus } from './enums';
import {
  computeCategoriesData,
  getCategoryDisplayName,
  getLevelDifficulty,
  getStatusLabel,
} from './exportShared';
import {
  calculateRepoLevelFromScore,
  calculateRepoScore,
  extractRepoNameOnly,
} from './utils';
import { INDUSTRY_LOGO_SVG } from '../brand/constants';

import type { IndustryAgentReadinessReport } from '@industry/common/agentReadiness/types';

function escapeHtml(text: string): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Export a readiness report to HTML format (for PDF printing)
 * Styled to match the Industry dark theme UI
 */
export function exportReadinessReportToHtml(
  report: IndustryAgentReadinessReport
): string {
  const repoName = extractRepoNameOnly(report.repoUrl || '');
  const scorePercent = calculateRepoScore(report);
  const level = calculateRepoLevelFromScore(scorePercent);
  const categoriesData = computeCategoriesData(report);

  const headerHtml = `<div class="header-card">
  <div class="title-row">
    ${INDUSTRY_LOGO_SVG}
    <div class="title-text">
      <div class="report-title">Agent Readiness Report</div>
      <div class="report-subtitle">Evaluates ${escapeHtml(repoName)}'s readiness for AI-native development</div>
      <div class="repo-info">
        <span class="repo-name">${escapeHtml(repoName)}</span>
        <span class="header-separator">·</span>
        <span class="level-badge">Level ${level}</span>
        <span class="score-text">(${Math.round(scorePercent)}% overall pass rate)</span>
      </div>
    </div>
  </div>
</div>`;

  const categoriesHtml = categoriesData
    .map((category) => {
      const criteriaRowsHtml = category.criteria
        .map((criterion) => {
          const statusLabel = getStatusLabel(criterion.status);
          const rationale = criterion.rationale
            ? escapeHtml(criterion.rationale)
            : '-';
          const difficulty = getLevelDifficulty(criterion.level);

          // Colored text with icon for status
          let statusColor = '#9ca3af';
          let statusIcon = '-';
          if (criterion.status === CriterionStatus.Passed) {
            statusColor = '#16a34a';
            statusIcon = '✓';
          } else if (criterion.status === CriterionStatus.Failed) {
            statusColor = '#dc2626';
            statusIcon = '✗';
          }

          return `<tr>
  <td class="criterion-name-cell">${escapeHtml(criterion.name)}</td>
  <td class="center">${difficulty}</td>
  <td class="center">${criterion.score}</td>
  <td class="center" style="color: ${statusColor}; font-weight: 600;">${statusIcon} ${statusLabel}</td>
  <td class="rationale-cell">${rationale}</td>
</tr>`;
        })
        .join('\n');

      return `<div class="card category-card">
  <div class="category-header">
    <span class="category-name">${escapeHtml(getCategoryDisplayName(category.categoryId))}</span>
    <span class="category-divider"></span>
    <span class="category-percent">${category.percentage === 100 ? 'COMPLETE' : `${category.percentage}%`}</span>
  </div>

  <table class="criteria-table">
    <colgroup>
      <col class="col-criterion">
      <col class="col-difficulty">
      <col class="col-score">
      <col class="col-status">
      <col class="col-rationale">
    </colgroup>
    <thead>
      <tr><th>Criterion</th><th class="center">Difficulty</th><th class="center">Score</th><th class="center">Status</th><th>Rationale</th></tr>
    </thead>
    <tbody>
      ${criteriaRowsHtml}
    </tbody>
  </table>
</div>`;
    })
    .join('\n');

  return `${headerHtml}\n${categoriesHtml}\n<div class="footer">Generated by Industry Agent Readiness</div>`;
}
