// @generated by drool.exe extraction
// Stub generated because packages/utils/src/agentReadiness/types was imported by recovered sources but absent from sourcemap recovery.
export type CategoryExportData = any;
export type MissionReadinessGateResult = any;
export type MissionRepoInspection = any;
export type MissionRepoInspectionDeps = any;
