// @generated by drool.exe extraction
// Generated from src/commands/enums; source module was missing in Bun sourcemap recovery.
export enum ConnectionStatus {
  Connected = "connected", // high-inferred; compactCamel; bundle hits=61
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  NotConnected = "notConnected", // high-inferred; compactCamel; bundle hits=5
  lastFailure, // value unresolved
}

export enum InputFormat {
  StreamJson = "stream-json", // high-inferred; lower-kebab; bundle hits=11
  StreamJsonrpc = "stream-jsonrpc", // high-inferred; lower-kebab; bundle hits=14
}

export enum LoopIntervalParseFailureReason {
  InvalidFormat = "invalidFormat", // high-inferred; compactCamel; bundle hits=10
  TooLong = "tooLong", // high-inferred; compactCamel; bundle hits=5
  TooShort = "tooShort", // high-inferred; compactCamel; bundle hits=5
}

export enum OutputFormat {
  Acp = "acp", // medium-cluster; compactCamel; bundle hits=19
  AcpDaemon = "acp-daemon", // high-inferred; lower-kebab; bundle hits=6
  Debug = "debug", // medium-cluster; compactCamel; bundle hits=63
  Json = "json", // medium-cluster; compactCamel; bundle hits=51
  StreamJson = "stream-json", // high-inferred; lower-kebab; bundle hits=11
  StreamJsonrpc = "stream-jsonrpc", // high-inferred; lower-kebab; bundle hits=14
  Text = "text", // medium-cluster; compactCamel; bundle hits=92
}

