// @generated by drool.exe extraction
// Stub generated because src/commands/types was imported by recovered sources but absent from sourcemap recovery.
export const BugReportFile: any = undefined as any;
export const CommandContext: any = undefined as any;
export const CommandResult: any = undefined as any;
export const DeferredPromptResolutionResult: any = undefined as any;
export const DeferredPromptResolveContext: any = undefined as any;
export const ExecCommandOptions: any = undefined as any;
export const SlashCommand: any = undefined as any;
export const SlashCommandRegistry: any = undefined as any;
export const SlashCommandVisibilityOptions: any = undefined as any;
export const ToolSelectionResult: any = undefined as any;
