// @generated by drool.exe extraction
// Generated from src/services/daemon/enums; source module was missing in Bun sourcemap recovery.
export enum SystemdNotifyState {
  Ready = "ready", // medium-cluster; compactCamel; bundle hits=51
  Reloading = "reloading", // high-inferred; compactCamel; bundle hits=3
  Stopping = "stopping", // high-inferred; compactCamel; bundle hits=3
}

