// @generated by drool.exe extraction
// Stub generated because src/services/daemon/types was imported by recovered sources but absent from sourcemap recovery.
export type AuthedConnectionOptions = any;
export type CreateSameProcessDaemonClientOptions = any;
export type HydrateLocalSessionStateParams = any;
export type SameProcessDaemonClientHandle = any;
export type SessionSettingsStore = any;
export type SessionSettingsStoreSnapshot = any;
