// @generated by drool.exe extraction
// Stub generated because packages/common/src/sessionV2/constants was imported by recovered sources but absent from sourcemap recovery.
export const BULK_SESSION_MAX_PER_REQUEST: any = undefined as any;
