// @generated by drool.exe extraction
// Stub generated because packages/common/src/sessionV2/types was imported by recovered sources but absent from sourcemap recovery.
export type BulkArchiveRequest = any;
export type BulkArchiveResponse = any;
export type BulkPreviewResponse = any;
export type BulkSessionFilter = any;
export type BulkUnarchiveRequest = any;
export type BulkUnarchiveResponse = any;
export type IndustryDroolSession = any;
export type IndustryDroolSessionListItem = any;
export type PaginatedSessionListResponse = any;
export type PaginatedSessionsResponse = any;
export type RestartSandboxResponse = any;
export type SessionWorkspaceFacet = any;
export type SessionWorkspaceFacetsResponse = any;
