// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/tools/types was imported by recovered sources but absent from sourcemap recovery.
export const ClientToolExecutor: any = undefined as any;
export const DraftToolFeedback: any = undefined as any;
export const IndustryTool: any = undefined as any;
export type IndustryTool = any;
export const InputJSONSchema: any = undefined as any;
export const IsNativeToolEnabledParams: any = undefined as any;
export const LLMToolDescriptor: any = undefined as any;
export const LLMToolSpec: any = undefined as any;
export type SandboxSideEffects = any;
export const ToolExecutor: any = undefined as any;
export const ToolImplementation: any = undefined as any;
export const ToolOverrides: any = undefined as any;
export const ToolRegistryInterface: any = undefined as any;
