// @generated by drool.exe extraction
// Generated from packages/runtime/plugins/src/enums; source module was missing in Bun sourcemap recovery.
export enum GitProtocol {
  HTTPS = "https", // medium-cluster; compactCamel; bundle hits=64
  SSH = "ssh", // medium-cluster; compactCamel; bundle hits=32
}

