// @generated by drool.exe extraction
// Stub generated because packages/runtime/plugins/src/types was imported by recovered sources but absent from sourcemap recovery.
export const FailedMarketplaceInstall: any = undefined as any;
export const FailedPluginInstall: any = undefined as any;
export const GitCloneRefOptions: any = undefined as any;
export const MarketplaceOperationResult: any = undefined as any;
export const OnPluginEnabledCallback: any = undefined as any;
export const ParsedPluginId: any = undefined as any;
export const PluginInstallResult: any = undefined as any;
export const PluginLoadResult: any = undefined as any;
export const PluginLoadWarning: any = undefined as any;
