// @generated by drool.exe extraction
// Stub generated because src/commands/_helpers/types was imported by recovered sources but absent from sourcemap recovery.
export const MenuCommandOptions: any = undefined as any;
export const StartNewSessionOptions: any = undefined as any;
