// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/tools/types was imported by recovered sources but absent from sourcemap recovery.
export type AllOrNothing = any;
export type ToolCall = any;
export type ToolExecutionContent = any;
export type ToolResult = any;
export type ToolResultData = any;
export type ToolResultErrorType = any;
export type ToolResultStaticFields = any;
export type ToolResultSuccess = any;
export type ToolUpdate = any;
export type ToolUpdateData = any;
