// @generated by drool.exe extraction
// Generated from src/hooks/enums; source module was missing in Bun sourcemap recovery.
export enum AgentStatusState {
  Compressing = "compressing", // high-inferred; compactCamel; bundle hits=18
  ExecutingTool = "executing_tool", // high-inferred; lower_snake; bundle hits=19
  Idle = "idle", // medium-cluster; compactCamel; bundle hits=42
  PendingTool = "pending_tool", // high-inferred; lower_snake; bundle hits=1
  Streaming = "streaming", // high-inferred; compactCamel; bundle hits=21
  Thinking = "thinking", // high-inferred; compactCamel; bundle hits=70
  ToolConfirmation = "toolConfirmation", // high-inferred; compactCamel; bundle hits=2
}

export enum AuthStatus {
  Authenticated = "authenticated", // high-inferred; compactCamel; bundle hits=21
  AuthenticatedWithoutOrg, // value unresolved
  Checking = "checking", // high-inferred; compactCamel; bundle hits=33
  InvalidApiKey = "invalid-api-key", // high-inferred; lower-kebab; bundle hits=7
  NeedsAuth = "needsAuth", // high-inferred; compactCamel; bundle hits=19
  NotApplicable = "not_applicable", // high-inferred; lower_snake; bundle hits=3
}

export enum BackgroundTaskItemType {
  Agent = "agent", // medium-cluster; compactCamel; bundle hits=40
  Execute = "execute", // medium-cluster; compactCamel; bundle hits=61
  Process = "process", // medium-cluster; compactCamel; bundle hits=56
}

export enum BackgroundTaskStatus {
  Completed = "completed", // high-inferred; compactCamel; bundle hits=82
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Running = "running", // medium-cluster; compactCamel; bundle hits=69
  Stopped = "stopped", // medium-cluster; compactCamel; bundle hits=27
}

export enum DroolsFlow {
  Create = "create", // medium-cluster; compactCamel; bundle hits=68
  Delete = "delete", // medium-cluster; compactCamel; bundle hits=44
  Edit = "edit", // medium-cluster; compactCamel; bundle hits=55
  Import = "import", // medium-cluster; compactCamel; bundle hits=48
  Menu = "menu", // medium-cluster; compactCamel; bundle hits=31
}

export enum EditorStep {
  Command = "command", // medium-cluster; compactCamel; bundle hits=82
  CommandRegex = "commandRegex", // high-inferred; compactCamel; bundle hits=14
  Matcher = "matcher", // medium-cluster; compactCamel; bundle hits=43
}

export enum HookEventName {
  Notification = "notification", // high-inferred; compactCamel; bundle hits=60
  PostToolUse = "postToolUse", // high-inferred; compactCamel; bundle hits=5
  PreCompact = "preCompact", // high-inferred; compactCamel; bundle hits=5
  PreToolUse = "preToolUse", // high-inferred; compactCamel; bundle hits=5
  SessionEnd = "sessionEnd", // high-inferred; compactCamel; bundle hits=5
  SessionStart = "sessionStart", // high-inferred; compactCamel; bundle hits=5
  Stop = "stop", // medium-cluster; compactCamel; bundle hits=35
  SubagentStop = "subagentStop", // high-inferred; compactCamel; bundle hits=5
  UserPromptSubmit = "userPromptSubmit", // high-inferred; compactCamel; bundle hits=5
}

export enum HookExecutionStatus {
  Completed = "completed", // high-inferred; compactCamel; bundle hits=82
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Executing = "executing", // high-inferred; compactCamel; bundle hits=40
}

export enum HookMatcherType {
  Matcher = "matcher", // medium-cluster; compactCamel; bundle hits=43
  New = "new", // medium-cluster; compactCamel; bundle hits=61
}

export enum HooksFlow {
  Command = "command", // medium-cluster; compactCamel; bundle hits=82
  Matcher = "matcher", // medium-cluster; compactCamel; bundle hits=43
  Menu = "menu", // medium-cluster; compactCamel; bundle hits=31
}

export enum IdeConnectionStatus {
  Connected = "connected", // high-inferred; compactCamel; bundle hits=61
  Connecting = "connecting", // high-inferred; compactCamel; bundle hits=48
  Disconnected = "disconnected", // high-inferred; compactCamel; bundle hits=34
}

export enum MessageRole {
  Assistant = "assistant", // high-inferred; compactCamel; bundle hits=36
  System = "system", // medium-cluster; compactCamel; bundle hits=62
  Tool = "tool", // medium-cluster; compactCamel; bundle hits=63
  User = "user", // medium-cluster; compactCamel; bundle hits=80
}

export enum MessageType {
  ApprovalComment = "approval_comment", // high-inferred; lower_snake; bundle hits=2
  HookExecution = "hook_execution", // high-inferred; lower_snake; bundle hits=4
  Markdown = "markdown", // high-inferred; compactCamel; bundle hits=25
  SystemNotification = "system_notification", // high-inferred; lower_snake; bundle hits=30
  Text = "text", // medium-cluster; compactCamel; bundle hits=92
  Thinking = "thinking", // high-inferred; compactCamel; bundle hits=70
  ToolCall = "toolCall", // high-inferred; compactCamel; bundle hits=15
  ToolResult = "toolResult", // high-inferred; compactCamel; bundle hits=20
}

export enum PermissionMode {
  AutoHigh = "auto-high", // high-inferred; lower-kebab; bundle hits=31
  AutoLow = "auto-low", // high-inferred; lower-kebab; bundle hits=35
  AutoMedium = "auto-medium", // high-inferred; lower-kebab; bundle hits=31
  Off = "off", // medium-cluster; compactCamel; bundle hits=69
  Spec = "spec", // medium-cluster; compactCamel; bundle hits=71
}

export enum PluginFlow {
  AddMarketplace = "add-marketplace", // high-inferred; lower-kebab; bundle hits=2
  DeleteMarketplace = "deleteMarketplace", // high-inferred; compactCamel; bundle hits=5
  FailedPluginActions = "failed-plugin-actions", // high-inferred; lower-kebab; bundle hits=2
  InstallPlugin = "install-plugin", // high-inferred; lower-kebab; bundle hits=2
  PluginActions = "plugin-actions", // high-inferred; lower-kebab; bundle hits=2
  Tabs = "tabs", // medium-cluster; compactCamel; bundle hits=33
}

export enum PluginTab {
  Browse = "browse", // medium-cluster; compactCamel; bundle hits=31
  Installed = "installed", // high-inferred; compactCamel; bundle hits=30
  Marketplaces = "marketplaces", // high-inferred; compactCamel; bundle hits=10
}

export enum SkillsFlow {
  Menu = "menu", // medium-cluster; compactCamel; bundle hits=31
}

export enum SkillTab {
  Import = "import", // medium-cluster; compactCamel; bundle hits=48
  Personal = "personal", // high-inferred; compactCamel; bundle hits=36
  Project = "project", // medium-cluster; compactCamel; bundle hits=78
}

export enum ToolCallStatus {
  Completed = "completed", // high-inferred; compactCamel; bundle hits=82
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Executing = "executing", // high-inferred; compactCamel; bundle hits=40
  Pending = "pending", // medium-cluster; compactCamel; bundle hits=67
}

