// @generated by drool.exe extraction
// Stub generated because packages/logging/src/sentry/types was imported by recovered sources but absent from sourcemap recovery.
export const SentryAdapter: any = undefined as any;
