// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/session/handlers/types was imported by recovered sources but absent from sourcemap recovery.
export type AskUserRequestHandlerEvents = any;
export type NotificationDispatcherEvents = any;
export type PendingAskUserRequest = any;
export type PendingPermission = any;
export type PendingUserAction = any;
export type PermissionRequestHandlerEvents = any;
export type StoredAskUserAction = any;
export type StoredPermissionAction = any;
