// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/agent-effectiveness/types was imported by recovered sources but absent from sourcemap recovery.
export type AgentEffectivenessCodingUsageRow = any;
export type AgentEffectivenessDateRange = any;
export type AgentEffectivenessOrganizationTotal = any;
export type AgentEffectivenessRecentRunResponse = any;
export type AgentEffectivenessReportEntitlementResponse = any;
export type AgentEffectivenessUsageRequest = any;
export type AgentEffectivenessUsageResponse = any;
export type ResolvedAgentEffectivenessUsageRequest = any;
