// @generated by drool.exe extraction
// Stub generated because packages/runtime/auth/src/storage/common/types was imported by recovered sources but absent from sourcemap recovery.
export type CredentialsStorageConfig = any;
export type FileLockOptions = any;
export type KeyFileStorageAdapter = any;
export type KeyringStorageAdapter = any;
export type KeyringStorageOptions = any;
export type KeytarLoader = any;
export type KeytarModule = any;
export type StoredCredentials = any;
export type TokenWithSource = any;
export type WorkOSUserInfo = any;
