// @generated by drool.exe extraction
// Generated from src/utils/toolCatalog/enums; source module was missing in Bun sourcemap recovery.
export enum ToolCategory {
  Edit = "edit", // medium-cluster; compactCamel; bundle hits=55
  Execute = "execute", // medium-cluster; compactCamel; bundle hits=61
  Other = "other", // medium-cluster; compactCamel; bundle hits=65
  Read = "read", // medium-cluster; compactCamel; bundle hits=61
}

