// @generated by drool.exe extraction
// Generated from src/profiling/enums; source module was missing in Bun sourcemap recovery.
export enum ProfileEventKind {
  InkRender = "ink-render", // high-inferred; lower-kebab; bundle hits=1
  PhaseStart = "phase-start", // high-inferred; lower-kebab; bundle hits=1
  PhaseStop = "phase-stop", // high-inferred; lower-kebab; bundle hits=1
  ReactCommit = "react-commit", // high-inferred; lower-kebab; bundle hits=1
  Resource = "resource", // high-inferred; compactCamel; bundle hits=56
  RunStart = "run-start", // high-inferred; lower-kebab; bundle hits=1
  RunStop = "run-stop", // high-inferred; lower-kebab; bundle hits=1
}

export enum ProfilerMode {
  Benchmark = "benchmark", // high-inferred; compactCamel; bundle hits=2
  Interactive = "interactive", // high-inferred; compactCamel; bundle hits=17
}

