// @generated by drool.exe extraction
// Stub generated because src/profiling/types was imported by recovered sources but absent from sourcemap recovery.
export type InkRenderSample = any;
export type LiveProfilerStats = any;
export type ProfileEvent = any;
export type ProfileRunSnapshot = any;
export type ProfilerRunMetadata = any;
export type ReactCommitSample = any;
export type ResourceSample = any;
