// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/jsonl/types was imported by recovered sources but absent from sourcemap recovery.
export type BaseContentBlock = any;
export type CacheControlEphemeral = any;
export type CompactionStateEvent = any;
export type DroolMessageEvent = any;
export type DroolSessionEvent = any;
export type LocallyPersistedContentBlock = any;
export type LocallyPersistedDocumentBlock = any;
export type LocallyPersistedDroolMessage = any;
export type LocallyPersistedImageBlock = any;
export type LocallyPersistedRedactedThinkingBlock = any;
export type LocallyPersistedTextBlock = any;
export type LocallyPersistedThinkingBlock = any;
export type LocallyPersistedToolResultBlock = any;
export type LocallyPersistedToolUseBlock = any;
export type SessionSummaryEvent = any;
export type TodoStateEvent = any;
