// @generated by drool.exe extraction
// Stub generated because src/tools/executors/client/utils/types was imported by recovered sources but absent from sourcemap recovery.
export const SubagentEvent: any = undefined as any;
