// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/context/enums was imported by recovered sources but absent from sourcemap recovery.
export const ContextSource: any = undefined as any;
export const ContextType: any = undefined as any;
