// @generated by drool.exe extraction
// Generated from packages/common/src/policy/enums; source module was missing in Bun sourcemap recovery.
export enum ModelExplicitOptInRequirementKind {
  DataRetention = "data_retention", // high-inferred; lower_snake; bundle hits=1
}

