// @generated by drool.exe extraction
// Stub generated because packages/common/src/policy/types was imported by recovered sources but absent from sourcemap recovery.
export type ModelExplicitOptInRequirement = any;
export type ModelExplicitOptInTosVersion = any;
export type ModelPolicy = any;
export type ResolvedModelPolicy = any;
export type UserModelPolicy = any;
