// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/shared/types was imported by recovered sources but absent from sourcemap recovery.
export type AuthCredential = any;
export type ErrorResponse = any;
export type RequestOptions = any;
