// @generated by drool.exe extraction
// Generated from src/utils/toolRoundtripFailure/enums; source module was missing in Bun sourcemap recovery.
export enum ToolRoundtripFailureSource {
  Daemon = "daemon", // medium-cluster; compactCamel; bundle hits=12
  Protocol = "protocol", // high-inferred; compactCamel; bundle hits=43
}

