// @generated by drool.exe extraction
// Stub generated because src/utils/toolRoundtripFailure/types was imported by recovered sources but absent from sourcemap recovery.
export type ToolRoundtripFailure = any;
