// @generated by drool.exe extraction
// Stub generated because packages/common/src/settings/types was imported by recovered sources but absent from sourcemap recovery.
export const GeneralSettings: any = undefined as any;
export const RegistryServer: any = undefined as any;
const defaultExport: any = undefined as any;
export default defaultExport;
