// @generated by drool.exe extraction
// Stub generated because src/theme/types was imported by recovered sources but absent from sourcemap recovery.
export type AnsiPalette = any;
export type DroolTheme = any;
export type ResolvedTheme = any;
export type ThemeMarkdownColors = any;
