// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/daemon/types was imported by recovered sources but absent from sourcemap recovery.
export const DaemonHeartbeatRequest: any = undefined as any;
export const DaemonHeartbeatResponse: any = undefined as any;
