// @generated by drool.exe extraction
// Generated from src/types/enums; source module was missing in Bun sourcemap recovery.
export enum MissionProposalAction {
  Approve = "approve", // medium-cluster; compactCamel; bundle hits=8
  ApproveWithComment = "approve-with-comment", // high-inferred; lower-kebab; bundle hits=7
  Reject = "reject", // medium-cluster; compactCamel; bundle hits=41
}

export enum SpecModeAction {
  Approve = "approve", // medium-cluster; compactCamel; bundle hits=8
  ApproveHigh = "approve-high", // high-inferred; lower-kebab; bundle hits=3
  ApproveLow = "approve-low", // high-inferred; lower-kebab; bundle hits=3
  ApproveMedium = "approve-medium", // high-inferred; lower-kebab; bundle hits=3
  ApproveNewSession = "approve-new-session", // high-inferred; lower-kebab; bundle hits=4
  ApproveWithComment = "approve-with-comment", // high-inferred; lower-kebab; bundle hits=7
  Edit = "edit", // medium-cluster; compactCamel; bundle hits=55
  Reject = "reject", // medium-cluster; compactCamel; bundle hits=41
}

