// @generated by drool.exe extraction
// Stub generated because src/types/types was imported by recovered sources but absent from sourcemap recovery.
export const BatchToolConfirmationDetails: any = undefined as any;
export const ChatSubmitOptions: any = undefined as any;
export const ClipboardImageInfo: any = undefined as any;
export const CollapsedToolGroup: any = undefined as any;
export const GroupedItem: any = undefined as any;
export const ImageAttachment: any = undefined as any;
export const ImageFileDetection: any = undefined as any;
export const ImagePasteResult: any = undefined as any;
export const QueuedUserMessageRunParams: any = undefined as any;
export const ToolExecution: any = undefined as any;
