// @generated by drool.exe extraction
// Generated from src/tools/executors/client/enums; source module was missing in Bun sourcemap recovery.
export enum UpgradeFailureReason {
  NoEffectiveModel = "no_effective_model", // high-inferred; lower_snake; bundle hits=2
  TargetNotAllowed = "target_not_allowed", // high-inferred; lower_snake; bundle hits=2
  TargetNotAvailable = "target_not_available", // high-inferred; lower_snake; bundle hits=2
  UpgradeNotDefined = "upgrade_not_defined", // high-inferred; lower_snake; bundle hits=2
}

