// @generated by drool.exe extraction
// Generated from src/mcp/enums; source module was missing in Bun sourcemap recovery.
export enum CallToolCaller {
  AGENT, // value unresolved
  FILE_API, // value unresolved
}

export enum MCPNotificationMethods {
  ResourceChange = "resourceChange", // high-inferred; compactCamel; bundle hits=5
  ToolsChange = "toolsChange", // high-inferred; compactCamel; bundle hits=1
}

