// @generated by drool.exe extraction
// Stub generated because src/mcp/schema was imported by recovered sources but absent from sourcemap recovery.
export const MCPServerNotification: any = undefined as any;
export const McpTool: any = undefined as any;
export const ResourceChange: any = undefined as any;
