// @generated by drool.exe extraction
// Stub generated because src/mcp/types was imported by recovered sources but absent from sourcemap recovery.
export const GetOAuthDriver: any = undefined as any;
export const ILogger: any = undefined as any;
export const McpReloadResult: any = undefined as any;
export const McpReloadServerSettleCallback: any = undefined as any;
export const McpReloadServerSettleEvent: any = undefined as any;
export const McpSubserver: any = undefined as any;
