// @generated by drool.exe extraction
// Generated from packages/daemon-client/src/session/core/enums; source module was missing in Bun sourcemap recovery.
export enum OptimisticSubmitStatus {
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Pending = "pending", // medium-cluster; compactCamel; bundle hits=67
}

