// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/session/core/types was imported by recovered sources but absent from sourcemap recovery.
export type DaemonRequest = any;
export type MessageRouterEvents = any;
export type OutgoingMessage = any;
export type PendingOptimisticSubmit = any;
export type PendingRequest = any;
export type RequestManagerEvents = any;
