// @generated by drool.exe extraction
// Stub generated because packages/runtime/src/computer was imported by recovered sources but absent from sourcemap recovery.
export const ComputerRegistrationClearedReason: any = undefined as any;
export const ComputerRegistrationReconcileStatus: any = undefined as any;
export type RegisteredHostIdentity = any;
export const clearLocalComputerRegistration: any = undefined as any;
export const hasComputerRegistration: any = undefined as any;
export const reconcileComputerRegistration: any = undefined as any;
