// @generated by drool.exe extraction
// Stub generated because packages/runtime/src/plugins was imported by recovered sources but absent from sourcemap recovery.
export const FailedMarketplaceInstall: any = undefined as any;
export type FailedMarketplaceInstall = any;
export const FailedPluginInstall: any = undefined as any;
export const MarketplaceOperationResult: any = undefined as any;
export const PluginInstallResult: any = undefined as any;
export const PluginLoadWarning: any = undefined as any;
export const parseMarketplaceSource: any = undefined as any;
export const parsePluginId: any = undefined as any;
