// @generated by drool.exe extraction
// Generated from src/services/mission/enums; source module was missing in Bun sourcemap recovery.
export enum HandoffOutcome {
  Crash = "crash", // medium-cluster; compactCamel; bundle hits=7
  Failure = "failure", // medium-cluster; compactCamel; bundle hits=45
  IncompleteHandoff = "incomplete-handoff", // high-inferred; lower-kebab; bundle hits=1
  Partial = "partial", // medium-cluster; compactCamel; bundle hits=34
  Success = "success", // medium-cluster; compactCamel; bundle hits=81
}

export enum MissionErrorType {
  InvalidJson = "invalidJson", // high-inferred; compactCamel; bundle hits=10
  MissingTranscript = "missingTranscript", // high-inferred; compactCamel; bundle hits=10
  PermissionDenied = "permissionDenied", // high-inferred; compactCamel; bundle hits=30
  ReadError = "readError", // high-inferred; compactCamel; bundle hits=15
}

