// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/linear/types was imported by recovered sources but absent from sourcemap recovery.
export type LinearConfig = any;
export type LinearTeam = any;
export type LinearTeamsMap = any;
