// @generated by drool.exe extraction
// Generated from src/components/tools/enums; source module was missing in Bun sourcemap recovery.
export enum ToolPreviewTier {
  LG = "lg", // medium-cluster; compactCamel; bundle hits=16
  MD = "md", // medium-cluster; compactCamel; bundle hits=36
  SM = "sm", // medium-cluster; compactCamel; bundle hits=35
  XS = "xs", // medium-cluster; compactCamel; bundle hits=34
}

