// @generated by drool.exe extraction
// Stub generated because src/services/drools/types was imported by recovered sources but absent from sourcemap recovery.
export const DroolConfig: any = undefined as any;
export const ParsedDrool: any = undefined as any;
