// @generated by drool.exe extraction
// Stub generated because packages/common/src/integrations/scm/types was imported by recovered sources but absent from sourcemap recovery.
export type GithubConfig = any;
export type GithubEnterpriseConfig = any;
export type GitlabConfig = any;
export type GitlabSelfHostedConfig = any;
export type SCMConfig = any;
export type SCMIntegrationPayload = any;
export type SCMIntegrationType = any;
export type SCMOrganization = any;
export type SCMOrganizationMap = any;
export type UserControlsMap = any;
export type WebhookIdMap = any;
