// @generated by drool.exe extraction
// Stub generated because packages/utils/src/settings/types was imported by recovered sources but absent from sourcemap recovery.
export type MissionSettingKey = any;
export type MissionWorkerRole = any;
export type ResolutionEventDescriptor = any;
export type ResolutionEventId = any;
export type SubagentSettingKey = any;
export type SubagentTier = any;
