// @generated by drool.exe extraction
// Generated from packages/common/src/api/backend/enums; source module was missing in Bun sourcemap recovery.
export enum UpdateSessionMissionSyncMode {
  Backfill = "backfill", // high-inferred; compactCamel; bundle hits=4
}

