// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/backend/types was imported by recovered sources but absent from sourcemap recovery.
export const AutomationSyncResponse: any = undefined as any;
export const BugReportUploadResponse: any = undefined as any;
