// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/model-router/types was imported by recovered sources but absent from sourcemap recovery.
export type CandidateModel = any;
export type CandidateScore = any;
export type ClassifierResult = any;
export type ClassifierSignals = any;
export type ClassifierSignalsInput = any;
export type ClassifierSystemPromptOptions = any;
export type ConversationMessage = any;
export type ModelOption = any;
export type ModelRouter = any;
export type ModelSelector = any;
export type RecentMessage = any;
export type RouterDeps = any;
export type RoutingDecision = any;
export type ScoredCandidate = any;
export type TaskClassifierDeps = any;
export type TurnClassifier = any;
