// @generated by drool.exe extraction
// Stub generated because packages/drool-sdk-ext/src/protocol/node was imported by recovered sources but absent from sourcemap recovery.
export type IpcDisconnectListener = any;
export type IpcMessageListener = any;
export type IpcProcessRef = any;
