// @generated by drool.exe extraction
// Stub generated because packages/utils/src/git/types was imported by recovered sources but absent from sourcemap recovery.
export type CleanupWorktreeOptions = any;
export type CreateWorktreeResult = any;
export type WorktreeInfo = any;
export type WorktreeSessionInfo = any;
export type WorktreeSetupOptions = any;
