// @generated by drool.exe extraction
// Generated from src/tools/executors/client/file-tools/enums; source module was missing in Bun sourcemap recovery.
export enum FileType {
  AUDIO = "audio", // medium-cluster; compactCamel; bundle hits=14
  BINARY = "binary", // medium-cluster; compactCamel; bundle hits=62
  IMAGE = "image", // medium-cluster; compactCamel; bundle hits=71
  PDF = "pdf", // medium-cluster; compactCamel; bundle hits=39
  SVG = "svg", // medium-cluster; compactCamel; bundle hits=20
  TEXT = "text", // medium-cluster; compactCamel; bundle hits=92
  VIDEO = "video", // medium-cluster; compactCamel; bundle hits=13
}

