// @generated by drool.exe extraction
// Generated from src/keyboard/enums; source module was missing in Bun sourcemap recovery.
export enum KeyFlag {
  DownArrow = "downArrow", // high-inferred; compactCamel; bundle hits=9
  End = "end", // medium-cluster; compactCamel; bundle hits=65
  Home = "home", // medium-cluster; compactCamel; bundle hits=24
  LeftArrow = "leftArrow", // high-inferred; compactCamel; bundle hits=6
  PageDown = "pageDown", // high-inferred; compactCamel; bundle hits=8
  PageUp = "pageUp", // high-inferred; compactCamel; bundle hits=8
  Return = "return", // medium-cluster; compactCamel; bundle hits=41
  RightArrow = "rightArrow", // high-inferred; compactCamel; bundle hits=6
  Tab = "tab", // medium-cluster; compactCamel; bundle hits=44
  UpArrow = "upArrow", // high-inferred; compactCamel; bundle hits=9
}

