// @generated by drool.exe extraction
// Stub generated because src/keyboard/types was imported by recovered sources but absent from sourcemap recovery.
export type DocumentaryKeyboardChordDefinition = any;
export type KeyEventLike = any;
export type KeyboardChord = any;
export type KeyboardChordDefinition = any;
export type KeyboardChordId = any;
export type KeyboardMatchableChord = any;
export type KeyboardMatchableChordId = any;
export type KeyboardModifierRequirements = any;
export type KeyboardPrintableMatcherOptions = any;
export type MatchableKeyboardChordDefinition = any;
export type ParsedCsiUSequence = any;
