// @generated by drool.exe extraction
// Stub generated because packages/logging/src/metrics/types was imported by recovered sources but absent from sourcemap recovery.
export const MetricLabels: any = undefined as any;
