// @generated by drool.exe extraction
// Stub generated because packages/utils/src/userStats/dto was imported by recovered sources but absent from sourcemap recovery.
export const serializeStats: any = undefined as any;
