// @generated by drool.exe extraction
// Generated from packages/utils/src/userStats/enums; source module was missing in Bun sourcemap recovery.
export enum Chronotype {
  AfternoonCoder = "afternoonCoder", // high-inferred; compactCamel; bundle hits=6
  EarlyBird = "earlyBird", // high-inferred; compactCamel; bundle hits=6
  NightHacker = "nightHacker", // high-inferred; compactCamel; bundle hits=6
  NightOwl = "nightOwl", // high-inferred; compactCamel; bundle hits=6
}

