// @generated by drool.exe extraction
// Stub generated because packages/utils/src/userStats/types was imported by recovered sources but absent from sourcemap recovery.
export type AdditionalData = any;
export type Badge = any;
export type DateRange = any;
export type FetchFn = any;
export type GetStatsResponse = any;
export type ProjectStats = any;
export type SerializedSessionData = any;
export type SessionData = any;
export type SessionMessage = any;
export type StatsData = any;
export type StatsDataDTO = any;
export type UserConfig = any;
export type UserSettings = any;
