// @generated by drool.exe extraction
// Stub generated because packages/common/src/errors/types was imported by recovered sources but absent from sourcemap recovery.
export type ErrorMetadata = any;
export type LogMetadata = any;
export type LogOptions = any;
