// @generated by drool.exe extraction
// Stub generated because src/hooks/skill-creation/types was imported by recovered sources but absent from sourcemap recovery.
export type CreateSkillSessionParams = any;
export type CreateSkillSessionResult = any;
export type SkillCreatorMessageComponents = any;
