// @generated by drool.exe extraction
// Generated from src/components/enums; source module was missing in Bun sourcemap recovery.
export enum CopyQuickItem {
  FullTranscript = "fullTranscript", // high-inferred; compactCamel; bundle hits=7
  LastAssistant = "lastAssistant", // high-inferred; compactCamel; bundle hits=7
  LastUser = "lastUser", // high-inferred; compactCamel; bundle hits=7
  SessionId = "sessionId", // high-inferred; compactCamel; bundle hits=36
}

export enum CopySelectionKind {
  Quick = "quick", // medium-cluster; compactCamel; bundle hits=7
  Range = "range", // medium-cluster; compactCamel; bundle hits=41
}

export enum FileRestoreChoice {
  All = "all", // medium-cluster; compactCamel; bundle hits=68
  None = "none", // medium-cluster; compactCamel; bundle hits=55
  Select = "select", // medium-cluster; compactCamel; bundle hits=41
}

export enum SpecModeConfiguratorState {
  Asking = "asking", // medium-cluster; compactCamel; bundle hits=9
  ClearConfirm = "clearConfirm", // high-inferred; compactCamel; bundle hits=5
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  SelectingModel = "selecting-model", // high-inferred; lower-kebab; bundle hits=8
  SelectingReasoning = "selecting-reasoning", // high-inferred; lower-kebab; bundle hits=4
}

