// @generated by drool.exe extraction
// Stub generated because src/components/types was imported by recovered sources but absent from sourcemap recovery.
export type ActiveOrganizationOption = any;
export type ActiveOrganizationOptionsResult = any;
export type CopySelectorProps = any;
export type CopySelectorSelection = any;
export type LimitsBucketData = any;
export type RewindMenuProps = any;
export type RewindOption = any;
export type SelectableListItem = any;
export type SelectableListProps = any;
export type SpecModeModelConfiguratorProps = any;
export type SpecModeModelConfiguratorRef = any;
export type TextInputProps = any;
export type TimerPersistentState = any;
export type UsageLimitsPanelProps = any;
