// @generated by drool.exe extraction
// Generated from src/utils/enums; source module was missing in Bun sourcemap recovery.
export enum AgentContextDirName {
  Agent = "agent", // medium-cluster; compactCamel; bundle hits=40
  Agents = "agents", // medium-cluster; compactCamel; bundle hits=37
  Industry = "industry", // medium-cluster; compactCamel; bundle hits=43
  IndustryDev, // value unresolved
}

export enum ClientMode {
  TUI = "tui", // medium-cluster; compactCamel; bundle hits=12
}

export enum IdeType {
  CURSOR = "cursor", // medium-cluster; compactCamel; bundle hits=49
  VSCODE = "vscode", // medium-cluster; compactCamel; bundle hits=17
  WINDSURF = "windsurf", // high-inferred; compactCamel; bundle hits=21
}

export enum IncrementalRenderingReason {
  DevelopmentDefault = "development-default", // high-inferred; lower-kebab; bundle hits=1
  DisabledOverride = "disabled-override", // high-inferred; lower-kebab; bundle hits=1
  FeatureFlagOff = "feature-flag-off", // high-inferred; lower-kebab; bundle hits=1
  FeatureFlagOn = "feature-flag-on", // high-inferred; lower-kebab; bundle hits=1
  UnpatchedInk = "unpatched-ink", // high-inferred; lower-kebab; bundle hits=1
  Windows = "windows", // medium-cluster; compactCamel; bundle hits=25
}

export enum ManagedEnvironmentConfidence {
  Likely = "likely", // medium-cluster; compactCamel; bundle hits=3
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
}

export enum MissionArtifactKind {
  Features = "features", // high-inferred; compactCamel; bundle hits=51
  RuntimeCustomModels = "runtime-custom-models", // high-inferred; lower-kebab; bundle hits=9
  State = "state", // medium-cluster; compactCamel; bundle hits=60
  WorkerHandoff = "worker-handoff", // high-inferred; lower-kebab; bundle hits=10
}

export enum MissionFileErrorType {
  NotFound = "notFound", // high-inferred; compactCamel; bundle hits=30
  ParseError = "parseError", // high-inferred; compactCamel; bundle hits=4
  PermissionError = "permission_error", // high-inferred; lower_snake; bundle hits=1
  ReadError = "readError", // high-inferred; compactCamel; bundle hits=15
}

export enum NpmDepKind {
  AgentBrowser = "agent-browser", // high-inferred; lower-kebab; bundle hits=12
  Keytar = "keytar", // medium-cluster; compactCamel; bundle hits=4
  Ripgrep = "ripgrep", // medium-cluster; compactCamel; bundle hits=5
}

export enum ShutdownReason {
  Other = "other", // medium-cluster; compactCamel; bundle hits=65
  PromptInputExit = "prompt_input_exit", // high-inferred; lower_snake; bundle hits=2
}

export enum ShutdownSignal {
  SIGINT, // value unresolved
  SIGTERM, // value unresolved
}

export enum SupportedTerminal {
  Cursor = "cursor", // medium-cluster; compactCamel; bundle hits=49
  Iterm2 = "iterm2", // medium-cluster; compactCamel; bundle hits=6
  MacosTerminal = "macos-terminal", // high-inferred; lower-kebab; bundle hits=5
  Powershell = "powershell", // high-inferred; compactCamel; bundle hits=16
  Tmux = "tmux", // medium-cluster; compactCamel; bundle hits=12
  Vscode = "vscode", // medium-cluster; compactCamel; bundle hits=17
  Warp = "warp", // medium-cluster; compactCamel; bundle hits=5
  WindowsTerminal = "windows-terminal", // high-inferred; lower-kebab; bundle hits=10
  Windsurf = "windsurf", // high-inferred; compactCamel; bundle hits=21
}

export enum TaskInvocationStatus {
  Cancelled = "cancelled", // high-inferred; compactCamel; bundle hits=76
  Completed = "completed", // high-inferred; compactCamel; bundle hits=82
  Failed = "failed", // medium-cluster; compactCamel; bundle hits=73
  Pending = "pending", // medium-cluster; compactCamel; bundle hits=67
  Running = "running", // medium-cluster; compactCamel; bundle hits=69
}

export enum TerminalDisconnectReason {
  Sighup = "sighup", // medium-cluster; compactCamel; bundle hits=1
  StderrError = "stderr_error", // high-inferred; lower_snake; bundle hits=1
  StdinClose = "stdin_close", // high-inferred; lower_snake; bundle hits=1
  StdinEnd = "stdin_end", // high-inferred; lower_snake; bundle hits=1
  StdinError = "stdin_error", // high-inferred; lower_snake; bundle hits=1
  StdoutError = "stdout_error", // high-inferred; lower_snake; bundle hits=1
  TtyPoll = "tty_poll", // high-inferred; lower_snake; bundle hits=1
}

