// @generated by drool.exe extraction
// Generated from src/services/slack/enums; source module was missing in Bun sourcemap recovery.
export enum SlackConnectionMessageKey {
  AlreadyConnected = "alreadyConnected", // high-inferred; compactCamel; bundle hits=14
  BrowserFailed = "browserFailed", // high-inferred; compactCamel; bundle hits=7
  Connected = "connected", // high-inferred; compactCamel; bundle hits=61
  Error = "error", // medium-cluster; compactCamel; bundle hits=96
  Opening = "opening", // medium-cluster; compactCamel; bundle hits=31
  Timeout = "timeout", // medium-cluster; compactCamel; bundle hits=61
}

