// @generated by drool.exe extraction
// Stub generated because src/services/slack/types was imported by recovered sources but absent from sourcemap recovery.
export type EnsureSlackConnectedOptions = any;
export type EnsureSlackConnectedResult = any;
export type IncidentResponseSetupData = any;
export type SlackCheckResult = any;
