// @generated by drool.exe extraction
// Generated from src/entrypoints/daemon/enums; source module was missing in Bun sourcemap recovery.
export enum DaemonListenMode {
  Ipc = "ipc", // medium-cluster; compactCamel; bundle hits=9
  WebSocket = "websocket", // high-inferred; lowerflat; bundle hits=8
}

