// @generated by drool.exe extraction
// Stub generated because packages/common/src/sessionV2/messages/types was imported by recovered sources but absent from sourcemap recovery.
export type FirestoreDroolMessage = any;
