// @generated by drool.exe extraction
// Generated from src/utils/terminalTheme/enums; source module was missing in Bun sourcemap recovery.
export enum TerminalTheme {
  Dark = "dark", // medium-cluster; compactCamel; bundle hits=22
  Light = "light", // medium-cluster; compactCamel; bundle hits=52
}

