// @generated by drool.exe extraction
// Generated from src/utils/mermaid/enums; source module was missing in Bun sourcemap recovery.
export enum DetectedMermaidType {
  Block = "block", // medium-cluster; compactCamel; bundle hits=49
  C4 = "c4", // medium-cluster; compactCamel; bundle hits=2
  ClassDiagram = "classDiagram", // high-inferred; compactCamel; bundle hits=2
  ErDiagram = "erDiagram", // high-inferred; compactCamel; bundle hits=2
  Flowchart = "flowchart", // high-inferred; compactCamel; bundle hits=10
  Gantt = "gantt", // medium-cluster; compactCamel; bundle hits=2
  GitGraph = "gitGraph", // high-inferred; compactCamel; bundle hits=1
  Journey = "journey", // medium-cluster; compactCamel; bundle hits=2
  Mindmap = "mindmap", // medium-cluster; compactCamel; bundle hits=2
  Pie = "pie", // medium-cluster; compactCamel; bundle hits=2
  QuadrantChart = "quadrantChart", // high-inferred; compactCamel; bundle hits=1
  RequirementDiagram = "requirementDiagram", // high-inferred; compactCamel; bundle hits=1
  Sankey = "sankey", // medium-cluster; compactCamel; bundle hits=2
  SequenceDiagram = "sequenceDiagram", // high-inferred; compactCamel; bundle hits=2
  StateDiagram = "stateDiagram", // high-inferred; compactCamel; bundle hits=2
  Timeline = "timeline", // high-inferred; compactCamel; bundle hits=2
  Unknown = "unknown", // medium-cluster; compactCamel; bundle hits=71
  XyChart, // value unresolved
}

