// @generated by drool.exe extraction
// Stub generated because packages/utils/src/promise/types was imported by recovered sources but absent from sourcemap recovery.
export const PromisePoolOptions: any = undefined as any;
