// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server/core/types was imported by recovered sources but absent from sourcemap recovery.
export type CapabilityToolbox = any;
export type ChildIpcAttacher = any;
export type DaemonCapability = any;
export type DaemonRequestCore = any;
export type DaemonRequestCoreConfig = any;
export type DaemonRequestCoreEnv = any;
export type DaemonRequestMethod = any;
