// @generated by drool.exe extraction
// Generated from packages/daemon-client/src/session/state/enums; source module was missing in Bun sourcemap recovery.
export enum QueuedUserMessageDisplayGroup {
  Queued = "queued", // medium-cluster; compactCamel; bundle hits=8
  Steering = "steering", // high-inferred; compactCamel; bundle hits=4
}

export enum QueuedUserMessageKind {
  DaemonQueuedDiscardable = "daemon_queued_discardable", // high-inferred; lower_snake; bundle hits=4
  DaemonQueuedEndOfLoop = "daemon_queued_end_of_loop", // high-inferred; lower_snake; bundle hits=4
  LocalDeferredAfterEsc = "local_deferred_after_esc", // high-inferred; lower_snake; bundle hits=4
  LocalDeferredDuringManualCompaction = "local_deferred_during_manual_compaction", // high-inferred; lower_snake; bundle hits=4
  LocalPausedAfterEsc = "local_paused_after_esc", // high-inferred; lower_snake; bundle hits=13
}

