// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/session/state/types was imported by recovered sources but absent from sourcemap recovery.
export type QueuedUserMessageState = any;
export type SessionTodoItem = any;
export type SessionTodoList = any;
