/**
 * Constants for the Drool sandbox system.
 */

export const DROOL_SANDBOXED_ENV = 'DROOL_SANDBOXED';

export const DROOL_WHOLE_PROCESS_SANDBOX_GUARD_PATH_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_GUARD_PATH';

export const DROOL_WHOLE_PROCESS_SANDBOX_GUARD_TOKEN_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_GUARD_TOKEN';

export const DROOL_WHOLE_PROCESS_SANDBOX_PERMISSION_REQUEST_FIFO_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_PERMISSION_REQUEST_FIFO';

export const DROOL_WHOLE_PROCESS_SANDBOX_PERMISSION_RESPONSE_FIFO_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_PERMISSION_RESPONSE_FIFO';

export const DROOL_WHOLE_PROCESS_SANDBOX_ATTESTATION_REQUEST_FIFO_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_ATTESTATION_REQUEST_FIFO';

export const DROOL_WHOLE_PROCESS_SANDBOX_ATTESTATION_RESPONSE_FIFO_ENV =
  'DROOL_WHOLE_PROCESS_SANDBOX_ATTESTATION_RESPONSE_FIFO';
