// @generated by drool.exe extraction
// Generated from src/sandbox/enums; source module was missing in Bun sourcemap recovery.
export enum SandboxDenyListKind {
  Write = "write", // medium-cluster; compactCamel; bundle hits=55
}

export enum SandboxPromptResult {
  AllowAlways = "allow_always", // high-inferred; lower_snake; bundle hits=17
  AllowAlwaysForExactPath, // value unresolved
  AllowOnce = "allow_once", // high-inferred; lower_snake; bundle hits=13
  Deny = "deny", // medium-cluster; compactCamel; bundle hits=30
}

