// @generated by drool.exe extraction
// Stub generated because src/sandbox/types was imported by recovered sources but absent from sourcemap recovery.
export type DependencyCheckResult = any;
export type PlatformSupportResult = any;
export type SandboxConfig = any;
export type SandboxPermissionRequestFn = any;
export type SandboxViolation = any;
