// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/capabilities/drool/types was imported by recovered sources but absent from sourcemap recovery.
export type DroolCapability = any;
export type DroolCapabilityDeps = any;
export type DroolCapabilityHostDeps = any;
