// @generated by drool.exe extraction
// Stub generated because src/hooks/useBlockingOverlay/types was imported by recovered sources but absent from sourcemap recovery.
export type BlockingOverlayFlags = any;
export type BlockingOverlayState = any;
