// @generated by drool.exe extraction
// Generated from packages/logging/src/enums; source module was missing in Bun sourcemap recovery.
export enum ExecutionEnvironment {
  CLIENT = "client", // medium-cluster; compactCamel; bundle hits=72
  SERVER = "server", // medium-cluster; compactCamel; bundle hits=61
}

export enum LogLevel {
  ERROR = "error", // medium-cluster; compactCamel; bundle hits=96
  INFO = "info", // medium-cluster; compactCamel; bundle hits=69
  WARN = "warn", // medium-cluster; compactCamel; bundle hits=66
}

export enum TelemetryEventType {
  LOG = "log", // medium-cluster; compactCamel; bundle hits=61
  METRIC = "metric", // medium-cluster; compactCamel; bundle hits=29
}

