// @generated by drool.exe extraction
// Stub generated because packages/logging/src/types was imported by recovered sources but absent from sourcemap recovery.
export const LogToConsoleFunction: any = undefined as any;
export const LoggerConfig: any = undefined as any;
export const LoggerConfigInput: any = undefined as any;
export const PrivateAttributes: any = undefined as any;
export const RequestLocalContext: any = undefined as any;
export const TelemetryClientConfig: any = undefined as any;
export const TelemetryEvent: any = undefined as any;
