// @generated by drool.exe extraction
// Generated from src/services/TerminalService/enums; source module was missing in Bun sourcemap recovery.
export enum TerminalServiceMode {
  Host = "host", // medium-cluster; compactCamel; bundle hits=60
  Local = "local", // medium-cluster; compactCamel; bundle hits=63
}

