// @generated by drool.exe extraction
// Stub generated because src/services/TerminalService/types was imported by recovered sources but absent from sourcemap recovery.
export type ITerminalService = any;
export type TerminalCreateParams = any;
export type TerminalOutputOptions = any;
export type TerminalServiceConfig = any;
