// @generated by drool.exe extraction
// Stub generated because packages/utils/src/bugReport/types was imported by recovered sources but absent from sourcemap recovery.
export type BugReportFile = any;
