// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/llms/errors/types was imported by recovered sources but absent from sourcemap recovery.
export type EmptyResponseTelemetry = any;
export type IndustryDisplayable402Body = any;
