// @generated by drool.exe extraction
// Stub generated because packages/common/src/relay/types was imported by recovered sources but absent from sourcemap recovery.
export type RelayAuthenticateRequest = any;
export type RelayAuthenticateResponse = any;
export type RelayComputerStatus = any;
export type RelayEnvelope = any;
export type RelayHealthResponse = any;
