// @generated by drool.exe extraction
// Stub generated because src/commands/mcp/types was imported by recovered sources but absent from sourcemap recovery.
export const AddCommandOptions: any = undefined as any;
export const McpCommandResult: any = undefined as any;
