// @generated by drool.exe extraction
// Stub generated because packages/common/src/session/process/schema was imported by recovered sources but absent from sourcemap recovery.
export type LocalProcess = any;
