// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server/ipc/types was imported by recovered sources but absent from sourcemap recovery.
export type AttachChildProcessParams = any;
export type ChildIpcConnection = any;
export type DaemonIpcConnectionServerParams = any;
