// @generated by drool.exe extraction
// Generated from packages/runtime/auth/src/credentials/enums; source module was missing in Bun sourcemap recovery.
export enum CredentialsSource {
  KeyfileV2, // value unresolved
  KeyringV2, // value unresolved
  LegacyEncrypted = "legacy-encrypted", // high-inferred; lower-kebab; bundle hits=9
  LegacyPlain = "legacy-plain", // high-inferred; lower-kebab; bundle hits=8
}

