// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/act-as-grants was imported by recovered sources but absent from sourcemap recovery.
export const VerifyActAsGrantRequest: any = undefined as any;
export const VerifyActAsGrantResponse: any = undefined as any;
