// @generated by drool.exe extraction
// Generated from packages/common/src/agentReadiness/enums; source module was missing in Bun sourcemap recovery.
export enum MissionReadinessGateState {
  LowScore = "low_score", // high-inferred; lower_snake; bundle hits=4
  NoGit = "no_git", // high-inferred; lower_snake; bundle hits=3
  NoRemote = "no_remote", // high-inferred; lower_snake; bundle hits=3
  NoReport = "no_report", // high-inferred; lower_snake; bundle hits=4
  Ok = "ok", // medium-cluster; compactCamel; bundle hits=71
}

export enum ReadinessCategoryId {
  Build = "build", // medium-cluster; compactCamel; bundle hits=60
  Debugging = "debugging", // high-inferred; compactCamel; bundle hits=12
  DevEnv = "dev_env", // high-inferred; lower_snake; bundle hits=6
  Docs = "docs", // medium-cluster; compactCamel; bundle hits=16
  Product = "product", // medium-cluster; compactCamel; bundle hits=8
  Security = "security", // high-inferred; compactCamel; bundle hits=31
  Style = "style", // medium-cluster; compactCamel; bundle hits=70
  TaskDiscovery = "task_discovery", // high-inferred; lower_snake; bundle hits=5
  Testing = "testing", // medium-cluster; compactCamel; bundle hits=11
}

export enum ReadinessCriterionId {
  AgenticDevelopment = "agentic_development", // high-inferred; lower_snake; bundle hits=1
  AgentsMd = "agentsMd", // high-inferred; compactCamel; bundle hits=5
  AgentsMdValidation = "agents_md_validation", // high-inferred; lower_snake; bundle hits=1
  AlertingConfigured = "alerting_configured", // high-inferred; lower_snake; bundle hits=1
  ApiSchemaDocs = "api_schema_docs", // high-inferred; lower_snake; bundle hits=1
  AutomatedDocGeneration = "automated_doc_generation", // high-inferred; lower_snake; bundle hits=1
  AutomatedPrReview = "automated_pr_review", // high-inferred; lower_snake; bundle hits=1
  AutomatedSecurityReview = "automated_security_review", // high-inferred; lower_snake; bundle hits=1
  BacklogHealth = "backlog_health", // high-inferred; lower_snake; bundle hits=1
  BranchProtection = "branch_protection", // high-inferred; lower_snake; bundle hits=1
  BuildCmdDoc = "build_cmd_doc", // high-inferred; lower_snake; bundle hits=1
  BuildPerformanceTracking = "build_performance_tracking", // high-inferred; lower_snake; bundle hits=1
  CircuitBreakers = "circuit_breakers", // high-inferred; lower_snake; bundle hits=1
  CodeModularization = "code_modularization", // high-inferred; lower_snake; bundle hits=1
  CodeQualityMetrics = "code_quality_metrics", // high-inferred; lower_snake; bundle hits=1
  Codeowners = "codeowners", // high-inferred; compactCamel; bundle hits=1
  CyclomaticComplexity = "cyclomatic_complexity", // high-inferred; lower_snake; bundle hits=1
  DastScanning = "dast_scanning", // high-inferred; lower_snake; bundle hits=1
  DatabaseSchema = "database_schema", // high-inferred; lower_snake; bundle hits=1
  DeadCodeDetection = "dead_code_detection", // high-inferred; lower_snake; bundle hits=1
  DeadFeatureFlagDetection = "dead_feature_flag_detection", // high-inferred; lower_snake; bundle hits=1
  DependencyUpdateAutomation = "dependency_update_automation", // high-inferred; lower_snake; bundle hits=1
  DeploymentFrequency = "deployment_frequency", // high-inferred; lower_snake; bundle hits=1
  DeploymentObservability = "deployment_observability", // high-inferred; lower_snake; bundle hits=1
  DepsPinned = "deps_pinned", // high-inferred; lower_snake; bundle hits=1
  Devcontainer = "devcontainer", // high-inferred; compactCamel; bundle hits=1
  DevcontainerRunnable = "devcontainer_runnable", // high-inferred; lower_snake; bundle hits=1
  DistributedTracing = "distributed_tracing", // high-inferred; lower_snake; bundle hits=1
  DocumentationFreshness = "documentation_freshness", // high-inferred; lower_snake; bundle hits=1
  DuplicateCodeDetection = "duplicate_code_detection", // high-inferred; lower_snake; bundle hits=1
  EnvTemplate = "env_template", // high-inferred; lower_snake; bundle hits=2
  ErrorToInsightPipeline = "error_to_insight_pipeline", // high-inferred; lower_snake; bundle hits=1
  ErrorTrackingContextualized = "error_tracking_contextualized", // high-inferred; lower_snake; bundle hits=1
  FastCiFeedback = "fast_ci_feedback", // high-inferred; lower_snake; bundle hits=1
  FeatureFlagInfrastructure = "feature_flag_infrastructure", // high-inferred; lower_snake; bundle hits=1
  FlakyTestDetection = "flaky_test_detection", // high-inferred; lower_snake; bundle hits=1
  Formatter = "formatter", // high-inferred; compactCamel; bundle hits=6
  GitignoreComprehensive = "gitignore_comprehensive", // high-inferred; lower_snake; bundle hits=1
  HealthChecks = "health_checks", // high-inferred; lower_snake; bundle hits=1
  HeavyDependencyDetection = "heavy_dependency_detection", // high-inferred; lower_snake; bundle hits=1
  IntegrationTestsExist = "integration_tests_exist", // high-inferred; lower_snake; bundle hits=1
  IssueLabelingSystem = "issue_labeling_system", // high-inferred; lower_snake; bundle hits=1
  IssueTemplates = "issue_templates", // high-inferred; lower_snake; bundle hits=1
  LargeFileDetection = "large_file_detection", // high-inferred; lower_snake; bundle hits=1
  LintConfig = "lint_config", // high-inferred; lower_snake; bundle hits=4
  LocalServicesSetup = "local_services_setup", // high-inferred; lower_snake; bundle hits=1
  LogScrubbing = "log_scrubbing", // high-inferred; lower_snake; bundle hits=1
  MetricsCollection = "metrics_collection", // high-inferred; lower_snake; bundle hits=1
  MinReleaseAge = "min_release_age", // high-inferred; lower_snake; bundle hits=1
  MonorepoTooling = "monorepo_tooling", // high-inferred; lower_snake; bundle hits=1
  NPlusOneDetection = "n_plus_one_detection", // high-inferred; lower_snake; bundle hits=1
  NamingConsistency = "naming_consistency", // high-inferred; lower_snake; bundle hits=1
  PiiHandling = "pii_handling", // high-inferred; lower_snake; bundle hits=1
  PrTemplates = "pr_templates", // high-inferred; lower_snake; bundle hits=1
  PreCommitHooks = "pre_commit_hooks", // high-inferred; lower_snake; bundle hits=1
  PrivacyCompliance = "privacy_compliance", // high-inferred; lower_snake; bundle hits=1
  ProductAnalyticsInstrumentation = "product_analytics_instrumentation", // high-inferred; lower_snake; bundle hits=1
  ProfilingInstrumentation = "profiling_instrumentation", // high-inferred; lower_snake; bundle hits=1
  ProgressiveRollout = "progressive_rollout", // high-inferred; lower_snake; bundle hits=1
  Readme = "readme", // medium-cluster; compactCamel; bundle hits=2
  ReleaseAutomation = "release_automation", // high-inferred; lower_snake; bundle hits=1
  ReleaseNotesAutomation = "release_notes_automation", // high-inferred; lower_snake; bundle hits=1
  RollbackAutomation = "rollback_automation", // high-inferred; lower_snake; bundle hits=1
  RunbooksDocumented = "runbooks_documented", // high-inferred; lower_snake; bundle hits=1
  SecretScanning = "secret_scanning", // high-inferred; lower_snake; bundle hits=1
  SecretsManagement = "secrets_management", // high-inferred; lower_snake; bundle hits=1
  ServiceFlowDocumented = "service_flow_documented", // high-inferred; lower_snake; bundle hits=1
  SingleCommandSetup = "single_command_setup", // high-inferred; lower_snake; bundle hits=1
  Skills = "skills", // medium-cluster; compactCamel; bundle hits=60
  StrictTyping = "strict_typing", // high-inferred; lower_snake; bundle hits=1
  StructuredLogging = "structured_logging", // high-inferred; lower_snake; bundle hits=1
  TechDebtTracking = "tech_debt_tracking", // high-inferred; lower_snake; bundle hits=1
  TestCoverageThresholds = "test_coverage_thresholds", // high-inferred; lower_snake; bundle hits=1
  TestIsolation = "test_isolation", // high-inferred; lower_snake; bundle hits=1
  TestNamingConventions = "test_naming_conventions", // high-inferred; lower_snake; bundle hits=1
  TestPerformanceTracking = "test_performance_tracking", // high-inferred; lower_snake; bundle hits=1
  TypeCheck = "type_check", // high-inferred; lower_snake; bundle hits=2
  UnitTestsExist = "unit_tests_exist", // high-inferred; lower_snake; bundle hits=3
  UnitTestsRunnable = "unit_tests_runnable", // high-inferred; lower_snake; bundle hits=1
  UnusedDependenciesDetection = "unused_dependencies_detection", // high-inferred; lower_snake; bundle hits=1
  VcsCliTools = "vcs_cli_tools", // high-inferred; lower_snake; bundle hits=1
  VersionDriftDetection = "version_drift_detection", // high-inferred; lower_snake; bundle hits=1
}

export enum ReadinessCriterionScope {
  Application = "application", // high-inferred; compactCamel; bundle hits=30
  Repository = "repository", // high-inferred; compactCamel; bundle hits=60
}

export enum ReadinessLevel {
  Level1, // value unresolved
  Level2, // value unresolved
  Level3, // value unresolved
  Level4, // value unresolved
  Level5, // value unresolved
}

