// @generated by drool.exe extraction
// Stub generated because packages/common/src/agentReadiness/types was imported by recovered sources but absent from sourcemap recovery.
export const IndustryAgentReadinessReport: any = undefined as any;
export const LevelBreakdown: any = undefined as any;
export const ReadinessCategory: any = undefined as any;
export const ReadinessCriterion: any = undefined as any;
export const ReadinessLevelDefinition: any = undefined as any;
export const ReadinessOrganizationLevel: any = undefined as any;
export const ReadinessScoreResult: any = undefined as any;
export const SignalEvaluation: any = undefined as any;
