// @generated by drool.exe extraction
// Stub generated because src/components/squad/types was imported by recovered sources but absent from sourcemap recovery.
export type SquadModeOverlayRef = any;
