// @generated by drool.exe extraction
// Stub generated because src/utils/images/types was imported by recovered sources but absent from sourcemap recovery.
export type CompressedImageResult = any;
export type ImageCompressionOptions = any;
