// @generated by drool.exe extraction
// Generated from packages/daemon-core/src/server/enums; source module was missing in Bun sourcemap recovery.
export enum WebSocketType {
  JSONRPC = "jsonrpc", // medium-cluster; compactCamel; bundle hits=37
  PORT_PROXY = "port_proxy", // high-inferred; lower_snake; bundle hits=4
}

