// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/server/types was imported by recovered sources but absent from sourcemap recovery.
export const AuthGateConnection: any = undefined as any;
export const AuthGateResponse: any = undefined as any;
export const AuthedDaemonConnectionParams: any = undefined as any;
export const ConnectionCleanupHook: any = undefined as any;
export const CreateAuthedDaemonConnectionParams: any = undefined as any;
export const DaemonActAsReverifyFn: any = undefined as any;
export const DaemonConfig: any = undefined as any;
export const DaemonConnectionHandlerConfig: any = undefined as any;
export const DaemonConnectionLifecycleHandler: any = undefined as any;
export const DaemonConnectionTracingMetadata: any = undefined as any;
export const DaemonTransportServer: any = undefined as any;
export const DaemonUser: any = undefined as any;
export const DaemonWebSocket: any = undefined as any;
export const DispatchResult: any = undefined as any;
export const IAuthedDaemonConnection: any = undefined as any;
export const JsonRpcWebSocketHandler: any = undefined as any;
export const JsonRpcWsData: any = undefined as any;
export const PortProxyWsData: any = undefined as any;
export const RelayConfig: any = undefined as any;
export const ServerTransport: any = undefined as any;
export const UnauthedDaemonConnection: any = undefined as any;
export const WebSocketData: any = undefined as any;
