// @generated by drool.exe extraction
// Stub generated because packages/logging/src/metadata/types was imported by recovered sources but absent from sourcemap recovery.
export const ErrorMetadata: any = undefined as any;
export const LogMetadata: any = undefined as any;
export type LogMetadata = any;
export const LogOptions: any = undefined as any;
export type LogOptions = any;
