// @generated by drool.exe extraction
// Stub generated because packages/drool-core/src/api/types was imported by recovered sources but absent from sourcemap recovery.
export const IndustryApiConfig: any = undefined as any;
export const FetchPreviousReadinessReportResult: any = undefined as any;
export const UpdateDroolStatusApiParams: any = undefined as any;
export const UpdateDroolStatusRequestBody: any = undefined as any;
export const UpdateDroolStatusResponse: any = undefined as any;
