// @generated by drool.exe extraction
// Stub generated because packages/logging/src/node/log-rotation was imported by recovered sources but absent from sourcemap recovery.
export const rotateLogFileIfNeededSync: any = undefined as any;
