// @generated by drool.exe extraction
// Stub generated because packages/logging/src/node/types was imported by recovered sources but absent from sourcemap recovery.
export const LogRotationOptions: any = undefined as any;
export const RotationError: any = undefined as any;
