// @generated by drool.exe extraction
// Generated from packages/daemon-client/src/transports/enums; source module was missing in Bun sourcemap recovery.
export enum DaemonClientTransportKind {
  InProcess = "in_process", // high-inferred; lower_snake; bundle hits=4
  Ipc = "ipc", // medium-cluster; compactCamel; bundle hits=9
  WebSocket = "websocket", // high-inferred; lowerflat; bundle hits=8
}

