// @generated by drool.exe extraction
// Stub generated because packages/daemon-client/src/transports/types was imported by recovered sources but absent from sourcemap recovery.
export type DaemonClientTransport = any;
export type DaemonClientTransportEvents = any;
export type DaemonIpcMessageChannel = any;
export type InProcessDaemonClientTransportOptions = any;
export type InProcessMessageHandler = any;
export type WebSocketDaemonTransportConfig = any;
