// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/v0/git-ai was imported by recovered sources but absent from sourcemap recovery.
export const GitAiCheckpoint: any = undefined as any;
export const PushGitAiCheckpointsRequest: any = undefined as any;
export type PushGitAiNotesRequest = any;
export const PushGitAiPullRequestRequest: any = undefined as any;
