// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/v0/machine-templates was imported by recovered sources but absent from sourcemap recovery.
export type MachineTemplate = any;
