// @generated by drool.exe extraction
// Stub generated because packages/runtime/auth/src/auth/common/types was imported by recovered sources but absent from sourcemap recovery.
export type AuthIdentity = any;
export type AuthedUser = any;
export type RuntimeAuthConfig = any;
