// @generated by drool.exe extraction
// Stub generated because packages/common/src/wiki was imported by recovered sources but absent from sourcemap recovery.
export type PageTreeNode = any;
export type WikiPage = any;
