export {
  McpServerConfigSchema,
  McpServerInfoSchema,
  McpSuccessResultSchema,
  DaemonGetMcpConfigRequestSchema,
  DaemonGetMcpConfigResultSchema,
  DaemonUpdateMcpConfigRequestParamsSchema,
  DaemonUpdateMcpConfigRequestSchema,
  DaemonUpdateMcpConfigResultSchema,
  DaemonToggleMcpServerRequestSchema,
  DaemonAuthenticateMcpServerRequestSchema,
  DaemonCancelMcpAuthRequestSchema,
  DaemonClearMcpAuthRequestSchema,
  DaemonAddMcpServerRequestSchema,
  DaemonRemoveMcpServerRequestSchema,
  DaemonListMcpRegistryRequestSchema,
  DaemonMcpRegistryServerSchema,
  DaemonListMcpRegistryResultSchema,
  DaemonListMcpToolsRequestSchema,
  DaemonMcpToolInfoSchema,
  DaemonListMcpToolsResultSchema,
  DaemonToggleMcpToolRequestSchema,
  DaemonListMcpServersRequestSchema,
  DaemonListMcpServersResultSchema,
  DaemonSubmitMcpAuthCodeRequestSchema,
  DaemonSubmitMcpAuthErrorRequestSchema,
} from '@industry/drool-sdk-ext/protocol/daemon';
