// @generated by drool.exe extraction
// Stub generated because src/utils/askUser/types was imported by recovered sources but absent from sourcemap recovery.
export type AskUserParsedQuestion = any;
export type AskUserParsedQuestionnaire = any;
