// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/relay/types was imported by recovered sources but absent from sourcemap recovery.
export type RelayConnectTimings = any;
export type RelayConnectionConfig = any;
export type RelayTransport = any;
