// @generated by drool.exe extraction
// Stub generated because packages/utils/src/fuzzy/types was imported by recovered sources but absent from sourcemap recovery.
export type FuseSearchOptions = any;
export type ProcessedQuery = any;
export type SearchResult = any;
