// @generated by drool.exe extraction
// Stub generated because packages/common/src/sessionV2/display/enums was imported by recovered sources but absent from sourcemap recovery.
export const SessionDisplayDataSource: any = undefined as any;
export const SessionGroupStatus: any = undefined as any;
