// @generated by drool.exe extraction
// Stub generated because packages/common/src/sessionV2/display/types was imported by recovered sources but absent from sourcemap recovery.
export type SessionDisplayInfo = any;
