// @generated by drool.exe extraction
// Stub generated because packages/utils/src/file-suggestions/types was imported by recovered sources but absent from sourcemap recovery.
export type FileSuggestionDisplayParts = any;
