// @generated by drool.exe extraction
// Stub generated because packages/utils/src/models/types was imported by recovered sources but absent from sourcemap recovery.
export type AnnotatedModelConfig = any;
export type FeatureFlagFetcher = any;
export type HttpCustomModel = any;
