// @generated by drool.exe extraction
// Stub generated because packages/runtime/auth/src/auth/workos/login/types was imported by recovered sources but absent from sourcemap recovery.
export type DeviceAuthorizationResponse = any;
export type DeviceCodeStatus = any;
export type PKCELoginFlow = any;
