// Country options for billing and tax forms
export const COUNTRIES = [
  { value: '', label: 'Select country' },
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AL', label: 'Albania' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BH', label: 'Bahrain' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BO', label: 'Bolivia' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BR', label: 'Brazil' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'CA', label: 'Canada' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'HR', label: 'Croatia' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DK', label: 'Denmark' },
  { value: 'DO', label: 'Dominican Republic' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egypt' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'EE', label: 'Estonia' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GE', label: 'Georgia' },
  { value: 'DE', label: 'Germany' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GR', label: 'Greece' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IS', label: 'Iceland' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IL', label: 'Israel' },
  { value: 'IT', label: 'Italy' },
  { value: 'JP', label: 'Japan' },
  { value: 'JO', label: 'Jordan' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KR', label: 'South Korea' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LB', label: 'Lebanon' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MT', label: 'Malta' },
  { value: 'MX', label: 'Mexico' },
  { value: 'MD', label: 'Moldova' },
  { value: 'MC', label: 'Monaco' },
  { value: 'MA', label: 'Morocco' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NO', label: 'Norway' },
  { value: 'OM', label: 'Oman' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PA', label: 'Panama' },
  { value: 'PE', label: 'Peru' },
  { value: 'PH', label: 'Philippines' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'QA', label: 'Qatar' },
  { value: 'RO', label: 'Romania' },
  { value: 'RU', label: 'Russia' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SG', label: 'Singapore' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'ES', label: 'Spain' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TH', label: 'Thailand' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'AE', label: 'United Arab Emirates' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Vietnam' },
];

// Tax ID types and country mappings from Orb billing API
// https://docs.withorb.com/api-reference/customer/create-customer

// All tax ID types with human-readable labels
export const TAX_ID_TYPE_LABELS: Record<string, string> = {
  ad_nrt: 'Andorran NRT',
  ae_trn: 'UAE TRN',
  al_tin: 'Albania TIN',
  am_tin: 'Armenia TIN',
  ao_tin: 'Angola TIN',
  ar_cuit: 'Argentina CUIT',
  au_abn: 'Australian ABN',
  au_arn: 'Australian ARN',
  ba_tin: 'Bosnia TIN',
  bd_bin: 'Bangladesh BIN',
  bg_uic: 'Bulgaria UIC',
  bh_vat: 'Bahrain VAT',
  bo_tin: 'Bolivia TIN',
  br_cnpj: 'Brazil CNPJ',
  br_cpf: 'Brazil CPF',
  ca_bn: 'Canadian BN',
  ca_gst_hst: 'Canadian GST/HST',
  ca_pst_bc: 'Canadian PST (BC)',
  ca_pst_mb: 'Canadian PST (MB)',
  ca_pst_sk: 'Canadian PST (SK)',
  ca_qst: 'Canadian QST',
  ch_uid: 'Switzerland UID',
  ch_vat: 'Switzerland VAT',
  cl_tin: 'Chile TIN',
  cn_tin: 'China TIN',
  co_nit: 'Colombia NIT',
  cr_tin: 'Costa Rica TIN',
  de_stn: 'German Tax Number',
  do_rcn: 'Dominican RCN',
  ec_ruc: 'Ecuador RUC',
  eg_tin: 'Egypt TIN',
  es_cif: 'Spain CIF',
  eu_vat: 'EU VAT',
  gb_vat: 'UK VAT',
  ge_vat: 'Georgia VAT',
  hk_br: 'Hong Kong BR',
  hr_oib: 'Croatia OIB',
  hu_tin: 'Hungary TIN',
  id_npwp: 'Indonesia NPWP',
  il_vat: 'Israel VAT',
  in_gst: 'India GST',
  is_vat: 'Iceland VAT',
  jp_cn: 'Japan Corporate Number',
  jp_rn: 'Japan Registered Number',
  jp_trn: 'Japan Tax Reg Number',
  ke_pin: 'Kenya PIN',
  kr_brn: 'South Korea BRN',
  kz_bin: 'Kazakhstan BIN',
  li_uid: 'Liechtenstein UID',
  li_vat: 'Liechtenstein VAT',
  ma_vat: 'Morocco VAT',
  md_vat: 'Moldova VAT',
  me_pib: 'Montenegro PIB',
  mx_rfc: 'Mexico RFC',
  my_frp: 'Malaysia FRP',
  my_itn: 'Malaysia ITN',
  my_sst: 'Malaysia SST',
  ng_tin: 'Nigeria TIN',
  no_vat: 'Norway VAT',
  no_voec: 'Norway VOEC',
  nz_gst: 'New Zealand GST',
  om_vat: 'Oman VAT',
  pe_ruc: 'Peru RUC',
  ph_tin: 'Philippines TIN',
  ro_tin: 'Romania TIN',
  rs_pib: 'Serbia PIB',
  ru_inn: 'Russia INN',
  ru_kpp: 'Russia KPP',
  sa_vat: 'Saudi Arabia VAT',
  sg_gst: 'Singapore GST',
  sg_uen: 'Singapore UEN',
  si_tin: 'Slovenia TIN',
  sv_nit: 'El Salvador NIT',
  th_vat: 'Thailand VAT',
  tr_tin: 'Turkey TIN',
  tw_vat: 'Taiwan VAT',
  ua_vat: 'Ukraine VAT',
  us_ein: 'US EIN',
  uy_ruc: 'Uruguay RUC',
  ve_rif: 'Venezuela RIF',
  vn_tin: 'Vietnam TIN',
  za_vat: 'South Africa VAT',
};

// Tax ID types available per country (from Orb docs)
export const COUNTRY_TAX_ID_TYPES: Record<string, string[]> = {
  AD: ['ad_nrt'],
  AE: ['ae_trn'],
  AL: ['al_tin'],
  AM: ['am_tin'],
  AO: ['ao_tin'],
  AR: ['ar_cuit'],
  AT: ['eu_vat'],
  AU: ['au_abn', 'au_arn'],
  BA: ['ba_tin'],
  BD: ['bd_bin'],
  BE: ['eu_vat'],
  BG: ['eu_vat', 'bg_uic'],
  BH: ['bh_vat'],
  BO: ['bo_tin'],
  BR: ['br_cnpj', 'br_cpf'],
  CA: ['ca_bn', 'ca_gst_hst', 'ca_pst_bc', 'ca_pst_mb', 'ca_pst_sk', 'ca_qst'],
  CH: ['ch_vat', 'ch_uid'],
  CL: ['cl_tin'],
  CN: ['cn_tin'],
  CO: ['co_nit'],
  CR: ['cr_tin'],
  CY: ['eu_vat'],
  CZ: ['eu_vat'],
  DE: ['eu_vat', 'de_stn'],
  DK: ['eu_vat'],
  DO: ['do_rcn'],
  EC: ['ec_ruc'],
  EE: ['eu_vat'],
  EG: ['eg_tin'],
  ES: ['eu_vat', 'es_cif'],
  FI: ['eu_vat'],
  FR: ['eu_vat'],
  GB: ['gb_vat'],
  GE: ['ge_vat'],
  GR: ['eu_vat'],
  HK: ['hk_br'],
  HR: ['eu_vat', 'hr_oib'],
  HU: ['eu_vat', 'hu_tin'],
  ID: ['id_npwp'],
  IE: ['eu_vat'],
  IL: ['il_vat'],
  IN: ['in_gst'],
  IS: ['is_vat'],
  IT: ['eu_vat'],
  JP: ['jp_cn', 'jp_rn', 'jp_trn'],
  KE: ['ke_pin'],
  KR: ['kr_brn'],
  KZ: ['kz_bin'],
  LI: ['li_uid', 'li_vat'],
  LT: ['eu_vat'],
  LU: ['eu_vat'],
  LV: ['eu_vat'],
  MA: ['ma_vat'],
  MD: ['md_vat'],
  ME: ['me_pib'],
  MT: ['eu_vat'],
  MX: ['mx_rfc'],
  MY: ['my_sst', 'my_frp', 'my_itn'],
  NG: ['ng_tin'],
  NL: ['eu_vat'],
  NO: ['no_vat', 'no_voec'],
  NZ: ['nz_gst'],
  OM: ['om_vat'],
  PE: ['pe_ruc'],
  PH: ['ph_tin'],
  PL: ['eu_vat'],
  PT: ['eu_vat'],
  RO: ['eu_vat', 'ro_tin'],
  RS: ['rs_pib'],
  RU: ['ru_inn', 'ru_kpp'],
  SA: ['sa_vat'],
  SE: ['eu_vat'],
  SG: ['sg_uen', 'sg_gst'],
  SI: ['eu_vat', 'si_tin'],
  SK: ['eu_vat'],
  SV: ['sv_nit'],
  TH: ['th_vat'],
  TR: ['tr_tin'],
  TW: ['tw_vat'],
  UA: ['ua_vat'],
  US: ['us_ein'],
  UY: ['uy_ruc'],
  VE: ['ve_rif'],
  VN: ['vn_tin'],
  ZA: ['za_vat'],
};

// Default tax ID type per country (first/most common type)
export const DEFAULT_TAX_ID_TYPE_BY_COUNTRY: Record<string, string> = {
  AD: 'ad_nrt',
  AE: 'ae_trn',
  AL: 'al_tin',
  AM: 'am_tin',
  AO: 'ao_tin',
  AR: 'ar_cuit',
  AT: 'eu_vat',
  AU: 'au_abn',
  BA: 'ba_tin',
  BD: 'bd_bin',
  BE: 'eu_vat',
  BG: 'eu_vat',
  BH: 'bh_vat',
  BO: 'bo_tin',
  BR: 'br_cnpj',
  CA: 'ca_bn',
  CH: 'ch_vat',
  CL: 'cl_tin',
  CN: 'cn_tin',
  CO: 'co_nit',
  CR: 'cr_tin',
  CY: 'eu_vat',
  CZ: 'eu_vat',
  DE: 'eu_vat',
  DK: 'eu_vat',
  DO: 'do_rcn',
  EC: 'ec_ruc',
  EE: 'eu_vat',
  EG: 'eg_tin',
  ES: 'eu_vat',
  FI: 'eu_vat',
  FR: 'eu_vat',
  GB: 'gb_vat',
  GE: 'ge_vat',
  GR: 'eu_vat',
  HK: 'hk_br',
  HR: 'eu_vat',
  HU: 'eu_vat',
  ID: 'id_npwp',
  IE: 'eu_vat',
  IL: 'il_vat',
  IN: 'in_gst',
  IS: 'is_vat',
  IT: 'eu_vat',
  JP: 'jp_cn',
  KE: 'ke_pin',
  KR: 'kr_brn',
  KZ: 'kz_bin',
  LI: 'li_uid',
  LT: 'eu_vat',
  LU: 'eu_vat',
  LV: 'eu_vat',
  MA: 'ma_vat',
  MD: 'md_vat',
  ME: 'me_pib',
  MT: 'eu_vat',
  MX: 'mx_rfc',
  MY: 'my_sst',
  NG: 'ng_tin',
  NL: 'eu_vat',
  NO: 'no_vat',
  NZ: 'nz_gst',
  OM: 'om_vat',
  PE: 'pe_ruc',
  PH: 'ph_tin',
  PL: 'eu_vat',
  PT: 'eu_vat',
  RO: 'eu_vat',
  RS: 'rs_pib',
  RU: 'ru_inn',
  SA: 'sa_vat',
  SE: 'eu_vat',
  SG: 'sg_uen',
  SI: 'eu_vat',
  SK: 'eu_vat',
  SV: 'sv_nit',
  TH: 'th_vat',
  TR: 'tr_tin',
  TW: 'tw_vat',
  UA: 'ua_vat',
  US: 'us_ein',
  UY: 'uy_ruc',
  VE: 've_rif',
  VN: 'vn_tin',
  ZA: 'za_vat',
};

// Set of countries supported by Orb for tax ID
export const ORB_TAX_ID_COUNTRIES = new Set(Object.keys(COUNTRY_TAX_ID_TYPES));
