// @generated by drool.exe extraction
// Generated from packages/common/src/billing/enums; source module was missing in Bun sourcemap recovery.
export enum UsageMode {
  Blocked = "blocked", // medium-cluster; compactCamel; bundle hits=28
  DroolCore = "droolCore", // high-inferred; compactCamel; bundle hits=19
  ExtraUsage = "extraUsage", // high-inferred; compactCamel; bundle hits=12
  Standard = "standard", // high-inferred; compactCamel; bundle hits=43
}

