// @generated by drool.exe extraction
// Stub generated because packages/common/src/billing/types was imported by recovered sources but absent from sourcemap recovery.
export type BillingAddress = any;
export type BillingLimitsBucketData = any;
export type BillingTokenLimitsResponse = any;
export type BillingUnpaidInvoicesResponse = any;
export type BucketTiersData = any;
export type ExtraUsagePurchaseStatusResult = any;
export type LimitPreference = any;
export type PurchaseExtraUsageBody = any;
export type PurchaseExtraUsageResult = any;
export type UsageLimitInfo = any;
export type UsageStatusParams = any;
export type UsageStatusResult = any;
