// @generated by drool.exe extraction
// Stub generated because src/utils/staticRenderCache/types was imported by recovered sources but absent from sourcemap recovery.
export type CacheEntry = any;
export type StaticRenderCacheOptions = any;
export type StaticRenderCacheStats = any;
