// @generated by drool.exe extraction
// Stub generated because packages/drool-sdk-ext/src/protocol/tools/types was imported by recovered sources but absent from sourcemap recovery.
const defaultExport: any = undefined as any;
export default defaultExport;
