// @generated by drool.exe extraction
// Stub generated because packages/utils/src/computers/relay-config was imported by recovered sources but absent from sourcemap recovery.
export const buildRegisteredComputerConfig: any = undefined as any;
