// @generated by drool.exe extraction
// Stub generated because packages/utils/src/computers/types was imported by recovered sources but absent from sourcemap recovery.
export type ComputerConfig = any;
