// @generated by drool.exe extraction
// Stub generated because packages/common/src/api/v0/computers/types was imported by recovered sources but absent from sourcemap recovery.
export type ComputeUsageResponse = any;
export type Computer = any;
export type ComputerListResponse = any;
export type ComputerMetric = any;
export type ComputerMetricsQuery = any;
export type ComputerMetricsResponse = any;
export type CreateComputerRequest = any;
export type CreateComputerRequestInput = any;
export type CreateComputerSource = any;
export type ListComputersQuery = any;
export type ProvisioningStep = any;
export type UpdateComputerRequest = any;
