// @generated by drool.exe extraction
// Stub generated because src/entrypoints/plugin/types was imported by recovered sources but absent from sourcemap recovery.
export const PluginCommandOptions: any = undefined as any;
export const PluginCommandResult: any = undefined as any;
