/**
 * Constants for repo metadata telemetry collection
 */

/** Timeout for git commands and file listing in milliseconds */
export const TIMEOUT_MS = 5000;

/** Config file patterns for detection, grouped by category */
export const CONFIG_PATTERNS: Record<string, string[]> = {
  linters: [
    '.eslintrc',
    '.eslintrc.js',
    '.eslintrc.json',
    '.eslintrc.yml',
    '.eslintrc.yaml',
    'eslint.config.js',
    'eslint.config.mjs',
    '.prettierrc',
    '.prettierrc.js',
    '.prettierrc.json',
    '.prettierrc.yml',
    'prettier.config.js',
    '.editorconfig',
    '.flake8',
    'ruff.toml',
    '.pylintrc',
    'pylintrc',
    '.golangci.yml',
    '.golangci.yaml',
    'clippy.toml',
    '.rubocop.yml',
    'phpcs.xml',
    '.stylelintrc',
    '.stylelintrc.json',
    'biome.json',
    // Python ecosystem
    'pyproject.toml',
    'mypy.ini',
    'setup.cfg',
    'pyrightconfig.json',
    // Rust
    'rustfmt.toml',
    // Java
    'checkstyle.xml',
    'spotbugs.xml',
    'pmd.xml',
    // Legacy
    'tslint.json',
  ],
  frameworks: [
    'next.config.js',
    'next.config.mjs',
    'next.config.ts',
    'nuxt.config.js',
    'nuxt.config.ts',
    'vite.config.ts',
    'vite.config.js',
    'angular.json',
    'vue.config.js',
    'svelte.config.js',
    'remix.config.js',
    'astro.config.mjs',
    'gatsby-config.js',
    'tailwind.config.js',
    'tailwind.config.ts',
  ],
  buildTools: [
    'package.json',
    'tsconfig.json',
    'webpack.config.js',
    'rollup.config.js',
    'esbuild.config.js',
    'turbo.json',
    'nx.json',
    'lerna.json',
    'pnpm-workspace.yaml',
    'Makefile',
    'CMakeLists.txt',
    'build.gradle',
    'build.gradle.kts',
    'pom.xml',
    'Cargo.toml',
    'go.mod',
    'go.work',
    'Gemfile',
    'composer.json',
    'mix.exs',
    'BUILD',
    'BUILD.bazel',
    'WORKSPACE',
    'Dockerfile',
    'docker-compose.yml',
    'docker-compose.yaml',
  ],
  testFrameworks: [
    'jest.config.js',
    'jest.config.ts',
    'jest.config.mjs',
    'jest.config.cjs',
    'vitest.config.ts',
    'vitest.config.js',
    'playwright.config.ts',
    'playwright.config.js',
    'cypress.config.js',
    'cypress.config.ts',
    'pytest.ini',
    'setup.cfg',
    'conftest.py',
    'phpunit.xml',
    '.rspec',
    'karma.conf.js',
  ],
  docs: [
    'README.md',
    'README',
    'readme.md',
    'AGENTS.md',
    'CONTRIBUTING.md',
    'CONTRIBUTING',
    'ARCHITECTURE.md',
    'CHANGELOG.md',
    'CHANGELOG',
    'CODE_OF_CONDUCT.md',
    'SECURITY.md',
    'LICENSE',
    'LICENSE.md',
    'TROUBLESHOOTING.md',
    'CODEOWNERS',
  ],
  devContainers: ['.devcontainer.json', 'devcontainer.json'],
  cicd: [
    '.gitlab-ci.yml',
    'Jenkinsfile',
    'azure-pipelines.yml',
    'bitbucket-pipelines.yml',
    '.travis.yml',
    '.circleci/config.yml',
  ],
  security: [
    '.gitleaks.toml',
    'gitleaks.toml',
    '.github/dependabot.yml',
    'dependabot.yml',
    'snyk.json',
    '.snyk',
    '.trivyignore',
    'security.txt',
  ],
  observability: [
    'prometheus.yml',
    'prometheus.yaml',
    'opentelemetry.yaml',
    'otel-collector-config.yaml',
    'datadog.yaml',
    'sentry.properties',
    'newrelic.yml',
  ],
  docsGen: [
    'mkdocs.yml',
    'docusaurus.config.js',
    'docusaurus.config.ts',
    'conf.py',
    '.readthedocs.yaml',
    '.readthedocs.yml',
    'openapi.yaml',
    'openapi.json',
    'swagger.yaml',
    'swagger.json',
    'typedoc.json',
    'jsdoc.json',
  ],
  preCommit: [
    '.pre-commit-config.yaml',
    '.huskyrc',
    '.huskyrc.json',
    '.lintstagedrc',
    '.lintstagedrc.json',
    'lint-staged.config.js',
  ],
};

/** Flattened set of all config file names for fast lookup */
export const ALL_CONFIG_FILES = new Set(Object.values(CONFIG_PATTERNS).flat());

/** Test file patterns for detection */
export const TEST_PATTERNS = [
  // JavaScript/TypeScript
  '*.test.ts',
  '*.test.tsx',
  '*.test.js',
  '*.test.jsx',
  '*.spec.ts',
  '*.spec.tsx',
  '*.spec.js',
  '*.spec.jsx',
  // Python
  '*_test.py',
  'test_*.py',
  // Go
  '*_test.go',
  // Java/Kotlin
  '*Test.java',
  '*Tests.java',
  '*Test.kt',
  '*Tests.kt',
  // Ruby
  '*_spec.rb',
  '*_test.rb',
  // Rust
  '*_test.rs',
  // C#/.NET
  '*Tests.cs',
  '*Test.cs',
  // BDD/Cucumber
  '*.feature',
];

/** Workspace indicator files - presence indicates monorepo type */
export const WORKSPACE_INDICATORS: Record<string, string> = {
  'pnpm-workspace.yaml': 'pnpm',
  'turbo.json': 'turborepo',
  'nx.json': 'nx',
  'lerna.json': 'lerna',
  'go.work': 'go-workspace',
  WORKSPACE: 'bazel',
  'WORKSPACE.bazel': 'bazel',
  'MODULE.bazel': 'bazel',
  'rush.json': 'rush',
  'pants.toml': 'pants',
};
