// @generated by drool.exe extraction
// Generated from src/telemetry/customer/enums; source module was missing in Bun sourcemap recovery.
export enum AttributeName {
  AUTONOMY_MODE = "autonomyMode", // high-inferred; compactCamel; bundle hits=34
  COMMIT_HASH = "commit.hash", // high-inferred; domain.rest_snake; bundle hits=2
  ENVIRONMENT_TYPE = "environment.type", // high-inferred; domain.rest_snake; bundle hits=6
  FILE_EXTENSION = "file.extension", // high-inferred; domain.rest_snake; bundle hits=9
  HOOK_EVENT_NAME = "hook.event_name", // high-inferred; domain.rest_snake; bundle hits=2
  HOOK_INVOCATION_ID = "hook.invocation_id", // high-inferred; domain.rest_snake; bundle hits=2
  HOOK_MATCHER = "hook.matcher", // high-inferred; domain.rest_snake; bundle hits=2
  LOGIN_METHOD, // value unresolved
  MCP_SERVER = "mcp.server", // high-inferred; domain.rest_snake; bundle hits=3
  OPERATION = "operation", // high-inferred; compactCamel; bundle hits=34
  PR_NUMBER = "pr.number", // high-inferred; domain.rest_snake; bundle hits=2
  PR_URL = "pr.url", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_AGE_DAYS = "repo.age_days", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_BUILD_TOOLS = "repo.build_tools", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_CICD = "repo.cicd", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_COMMIT_VELOCITY_30D = "repo.commit_velocity_30d", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_CONTRIBUTOR_COUNT_90D = "repo.contributor_count_90d", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_DEFAULT_BRANCH = "repo.default_branch", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_DEV_CONTAINERS = "repo.dev_containers", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_DIRECTORY_COUNT = "repo.directory_count", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_DOCS = "repo.docs", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_DOCS_GEN = "repo.docs_gen", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_FILE_COUNT = "repo.file_count", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_FRAMEWORKS = "repo.frameworks", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_HAS_GIT = "repo.has_git", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_LANGUAGE_COUNT = "repo.language_count", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_LANGUAGE_FILE_COUNTS = "repo.language_file_counts", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_LANGUAGE_LOC_ESTIMATE = "repo.language_loc_estimate", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_LINTERS = "repo.linters", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_LOC_ESTIMATE = "repo.loc_estimate", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_MAX_DEPTH = "repo.max_depth", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_NAME = "repo.name", // high-inferred; domain.rest_snake; bundle hits=4
  REPO_OBSERVABILITY = "repo.observability", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_PRE_COMMIT = "repo.pre_commit", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_PRIMARY_LANGUAGE = "repo.primary_language", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_REMOTE_URL_HASH = "repo.remote_url_hash", // high-inferred; domain.rest_snake; bundle hits=1
  REPO_SECURITY = "repo.security", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_TEST_FRAMEWORKS = "repo.test_frameworks", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_TEST_PATTERNS = "repo.test_patterns", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_TEST_PATTERN_COUNT = "repo.test_pattern_count", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_WORKSPACE_PACKAGE_COUNT = "repo.workspace_package_count", // high-inferred; domain.rest_snake; bundle hits=2
  REPO_WORKSPACE_TYPE = "repo.workspace_type", // high-inferred; domain.rest_snake; bundle hits=2
  SKILL_LOCATION = "skill.location", // high-inferred; domain.rest_snake; bundle hits=2
  SKILL_NAME = "skill.name", // high-inferred; domain.rest_snake; bundle hits=4
  SLASH_COMMAND_NAME, // value unresolved
  TOOL_CATEGORY = "tool.category", // high-inferred; domain.rest_snake; bundle hits=6
  TOOL_NAME = "tool.name", // high-inferred; domain.rest_snake; bundle hits=12
  TOOL_RUNTIME = "tool.runtime", // high-inferred; domain.rest_snake; bundle hits=6
  TOOL_SUCCEEDED = "tool.succeeded", // high-inferred; domain.rest_snake; bundle hits=8
}

export enum LoginMethod {
  SLASH_COMMAND = "slash_command", // high-inferred; lower_snake; bundle hits=4
}

export enum MetricName {
  CODE_FILES_MODIFIED = "drool.code.files_modified", // high-inferred; drool.domain.rest_snake; bundle hits=1
  CODE_FILES_READ = "drool.code.files_read", // high-inferred; drool.domain.rest_snake; bundle hits=1
  CODE_LINES_MODIFIED = "drool.code.lines_modified", // high-inferred; drool.domain.rest_snake; bundle hits=2
  COMMAND_BLOCKED = "drool.command.blocked", // high-inferred; drool.domain.rest_snake; bundle hits=2
  GIT_COMMITS = "drool.git.commits", // high-inferred; drool.domain.rest_snake; bundle hits=1
  GIT_PULL_REQUESTS = "drool.git.pull_requests", // high-inferred; drool.domain.rest_snake; bundle hits=1
  HOOK_INVOCATIONS = "drool.hook.invocations", // high-inferred; drool.domain.rest_snake; bundle hits=1
  LOGIN_SUCCESS, // value unresolved
  MCP_TOOL_INVOCATIONS = "drool.mcp.tool_invocations", // high-inferred; drool.domain.rest_snake; bundle hits=1
  REPO_METADATA = "drool.repo.metadata", // high-inferred; drool.domain.rest_snake; bundle hits=1
  SESSION_MESSAGE_COUNT, // value unresolved
  SKILL_INSTALLED = "drool.skill.installed", // high-inferred; drool.domain.rest_snake; bundle hits=1
  SKILL_INVOCATIONS = "drool.skill.invocations", // high-inferred; drool.domain.rest_snake; bundle hits=1
  SLASH_COMMAND_INVOCATIONS, // value unresolved
  TOOL_EXECUTION_COUNT = "tool_execution_count", // high-inferred; lower_snake; bundle hits=2
  TOOL_EXECUTION_DURATION, // value unresolved
  TOOL_EXECUTION_TIME = "drool.tool.execution_time", // high-inferred; drool.domain.rest_snake; bundle hits=3
  TOOL_INVOCATIONS = "drool.tool.invocations", // high-inferred; drool.domain.rest_snake; bundle hits=3
}

export enum MissionFailureCategory {
  DAEMON_CONNECTIVITY = "daemon_connectivity", // high-inferred; lower_snake; bundle hits=2
  MISSION_STATE = "missionState", // high-inferred; compactCamel; bundle hits=9
  OTHER = "other", // medium-cluster; compactCamel; bundle hits=65
  TIMEOUT = "timeout", // medium-cluster; compactCamel; bundle hits=61
  USER_ACTION = "user_action", // high-inferred; lower_snake; bundle hits=1
  WORKER_EXECUTION = "worker_execution", // high-inferred; lower_snake; bundle hits=1
  WORKER_SESSION = "worker_session", // high-inferred; lower_snake; bundle hits=1
}

export enum MissionFailureReasonCode {
  DAEMON_NOT_REACHABLE = "daemonNotReachable", // high-inferred; compactCamel; bundle hits=5
  DAEMON_RPC_TIMEOUT = "daemon_rpc_timeout", // high-inferred; lower_snake; bundle hits=3
  DAEMON_UNAVAILABLE_DURING_RUN = "daemon_unavailable_during_run", // high-inferred; lower_snake; bundle hits=3
  DAEMON_UNREACHABLE = "daemon_unreachable", // high-inferred; lower_snake; bundle hits=8
  MISSING_MISSION_ID = "missing_mission_id", // high-inferred; lower_snake; bundle hits=3
  OTHER = "other", // medium-cluster; compactCamel; bundle hits=65
  TIMEOUT = "timeout", // medium-cluster; compactCamel; bundle hits=61
  WORKER_INACTIVITY_TIMEOUT = "worker_inactivity_timeout", // high-inferred; lower_snake; bundle hits=3
  WORKER_INTERRUPTED = "worker_interrupted", // high-inferred; lower_snake; bundle hits=3
  WORKER_KILLED_BY_USER = "worker_killed_by_user", // high-inferred; lower_snake; bundle hits=3
  WORKER_LOAD_SESSION_ERROR = "worker_load_session_error", // high-inferred; lower_snake; bundle hits=3
  WORKER_ORPHAN_CLEANUP = "worker_orphan_cleanup", // high-inferred; lower_snake; bundle hits=3
  WORKER_PROCESS_EXIT = "worker_process_exit", // high-inferred; lower_snake; bundle hits=3
  WORKER_RESUME_ERROR = "worker_resume_error", // high-inferred; lower_snake; bundle hits=3
  WORKER_SPAWN_ERROR = "worker_spawn_error", // high-inferred; lower_snake; bundle hits=3
}

