// @generated by drool.exe extraction
// Stub generated because packages/utils/src/jsonRender/types was imported by recovered sources but absent from sourcemap recovery.
export type ContentSegment = any;
export type JsonRenderSpec = any;
