// @generated by drool.exe extraction
// Stub generated because packages/runtime/session-search/src/types was imported by recovered sources but absent from sourcemap recovery.
export type BlockExtractor = any;
export type DroolFindHit = any;
export type DroolFindOptions = any;
export type DroolFindResults = any;
export type DroolFindSessionResult = any;
export type DroolMessageEvent = any;
export type DroolSessionEvent = any;
export type ExtractorContext = any;
export type ExtractorOptions = any;
export type ExtractorRegistration = any;
export type LocallyPersistedDroolMessage = any;
export type SessionJsonlFileHandle = any;
export type SessionSearchDoc = any;
