import type { MessageForThinkingGuards } from './types';

/**
 * Guards to prevent API errors when thinking is enabled but messages don't support it.
 *
 * Model-specific behavior:
 * - Standard Claude models: guards needed to prevent API errors
 * - Apex: guards NOT needed - preserves thinking blocks by default (new behavior)
 *
 * Use shouldApplyThinkingGuards() from @industry/utils/llm to check if these
 * guards should be applied for a given model.
 */

// Disable thinking only for compaction scenarios where NO assistant messages
// have thinking blocks.
//
// This guard is specifically for post-compaction conversations where the
// preserved "anchor" assistant message was generated without thinking (e.g.,
// from effort mode choosing not to emit thinking, or from a non-thinking model).
//
// IMPORTANT: This guard should NOT trigger for normal effort mode conversations
// where some turns have thinking and some don't. The Anthropic API allows this
// pattern - it only requires the FINAL assistant message to have thinking when
// thinking is enabled, and it ignores thinking blocks from previous turns.
//
// The guard only triggers when ALL assistant messages lack thinking, indicating
// this is a compaction scenario where thinking was never present.
export function shouldDisableThinkingForCompaction(
  messages: MessageForThinkingGuards[]
): boolean {
  let hasAnyAssistantWithContent = false;
  let hasAnyThinking = false;

  for (const msg of messages) {
    if (msg.role !== 'assistant') {
      continue;
    }

    // Skip assistant messages with empty content - API accepts these with thinking enabled
    if (!Array.isArray(msg.content) || msg.content.length === 0) {
      continue;
    }

    hasAnyAssistantWithContent = true;

    // Check if the first content is a thinking block
    // API requires thinking to be FIRST: "If an assistant message contains any thinking blocks,
    // the first block must be `thinking` or `redacted_thinking`"
    const firstContent = msg.content[0];
    if (typeof firstContent === 'object') {
      const contentType =
        'type' in firstContent ? (firstContent.type as string) : undefined;
      if (contentType === 'thinking' || contentType === 'redacted_thinking') {
        hasAnyThinking = true;
        break; // Found thinking, no need to check further
      }
    }
  }

  // Only disable thinking if there ARE assistant messages with content but NONE have thinking.
  // Empty assistant content arrays are OK - API accepts them with thinking enabled.
  // This indicates a compaction scenario, not normal effort mode behavior.
  return hasAnyAssistantWithContent && !hasAnyThinking;
}

// Disable thinking when switching from a non-thinking model to a thinking model.
// This happens when previous requests were generated by models that do not support thinking.
// Specifically, check if the first assistant message after the last user message
// doesn't contain a thinking block, which indicates the previous model didn't support thinking.
export function shouldDisableThinkingForModelSwitching(
  messages: MessageForThinkingGuards[]
): boolean {
  // Find the last user message
  let lastUserIndex = -1;
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === 'user') {
      lastUserIndex = i;
      break;
    }
  }

  // If there's no user message or the last message is a user message, don't disable thinking
  if (lastUserIndex === -1 || lastUserIndex === messages.length - 1) {
    return false;
  }

  // Check if the message after the last user message is an assistant message
  const nextMessage = messages[lastUserIndex + 1];

  if (nextMessage.role !== 'assistant') {
    return false;
  }

  // Check if the assistant message has contents
  if (!Array.isArray(nextMessage.content) || nextMessage.content.length === 0) {
    return false;
  }

  // Check if the first content is a thinking block
  // API requires thinking to be FIRST: "If an assistant message contains any thinking blocks,
  // the first block must be `thinking` or `redacted_thinking`"
  const firstContent = nextMessage.content[0];
  if (typeof firstContent === 'object') {
    const contentType =
      'type' in firstContent ? (firstContent.type as string) : undefined;
    if (contentType !== 'thinking' && contentType !== 'redacted_thinking') {
      return true;
    }
  }

  return false;
}

/**
 * Strip thinking and redacted_thinking blocks from assistant messages.
 *
 * When thinking is disabled by a guard but the conversation history contains
 * assistant messages with thinking blocks from previous requests (when thinking
 * was enabled), the API will reject the request with:
 * "When thinking is disabled, an assistant message cannot contain thinking"
 *
 * This function removes thinking blocks from all assistant messages so the
 * request can succeed.
 *
 * @param messages - The conversation history to modify
 * @returns A new array with thinking blocks stripped from assistant messages
 */
export function stripThinkingFromHistory<T extends MessageForThinkingGuards>(
  messages: T[]
): T[] {
  return messages.map((msg) => {
    if (msg.role !== 'assistant') {
      return msg;
    }

    if (!Array.isArray(msg.content) || msg.content.length === 0) {
      return msg;
    }

    // Filter out thinking and redacted_thinking blocks
    const filteredContent = msg.content.filter((block) => {
      if (typeof block !== 'object' || block === null) {
        return true;
      }
      const blockType = 'type' in block ? block.type : undefined;
      return blockType !== 'thinking' && blockType !== 'redacted_thinking';
    });

    // If no content was filtered, return original message
    if (filteredContent.length === msg.content.length) {
      return msg;
    }

    // Return new message with filtered content
    return {
      ...msg,
      content: filteredContent,
    };
  });
}
