// @generated by drool.exe extraction
// Stub generated because packages/utils/src/llm/vertex was imported by recovered sources but absent from sourcemap recovery.
export const asVertexLocation: any = undefined as any;
