// @generated by drool.exe extraction
// Stub generated because packages/common/src/shared/constants was imported by recovered sources but absent from sourcemap recovery.
export const DEV_INDUSTRY_API_BASE_URL: any = undefined as any;
export const DEV_INDUSTRY_APP_BASE_URL: any = undefined as any;
export const DEV_INDUSTRY_RELAY_BASE_URL: any = undefined as any;
export const PROD_INDUSTRY_API_BASE_URL: any = undefined as any;
export const PROD_INDUSTRY_APP_BASE_URL: any = undefined as any;
export const PROD_INDUSTRY_RELAY_BASE_URL: any = undefined as any;
