// @generated by drool.exe extraction
// Stub generated because packages/common/src/shared/types was imported by recovered sources but absent from sourcemap recovery.
export type FirestoreSchemaWithId = any;
export type GenericFirestoreData = any;
