// @generated by drool.exe extraction
// Stub generated because packages/daemon-core/src/capabilities/management/types was imported by recovered sources but absent from sourcemap recovery.
export type ManagementCapabilityDeps = any;
export type ManagementCapabilityHostDeps = any;
