// @generated by drool.exe extraction
// Stub generated because src/tools/types was imported by recovered sources but absent from sourcemap recovery.
export const CliClientSpecificToolDependencies: any = undefined as any;
export const CliClientToolDependencies: any = undefined as any;
